-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity display_shift_display_shift_label1_proc5 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    width : IN STD_LOGIC_VECTOR (31 downto 0);
    xstart : IN STD_LOGIC_VECTOR (31 downto 0);
    y_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    ystart : IN STD_LOGIC_VECTOR (31 downto 0);
    frame_size : IN STD_LOGIC_VECTOR (31 downto 0);
    ddr_copy : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_copy_AWVALID : OUT STD_LOGIC;
    m_axi_copy_AWREADY : IN STD_LOGIC;
    m_axi_copy_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_copy_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_copy_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_copy_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_copy_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_copy_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_copy_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_copy_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_copy_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_copy_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_copy_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_copy_WVALID : OUT STD_LOGIC;
    m_axi_copy_WREADY : IN STD_LOGIC;
    m_axi_copy_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_copy_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_copy_WLAST : OUT STD_LOGIC;
    m_axi_copy_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_copy_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_copy_ARVALID : OUT STD_LOGIC;
    m_axi_copy_ARREADY : IN STD_LOGIC;
    m_axi_copy_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_copy_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_copy_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_copy_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_copy_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_copy_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_copy_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_copy_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_copy_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_copy_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_copy_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_copy_RVALID : IN STD_LOGIC;
    m_axi_copy_RREADY : OUT STD_LOGIC;
    m_axi_copy_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_copy_RLAST : IN STD_LOGIC;
    m_axi_copy_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_copy_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_copy_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_copy_BVALID : IN STD_LOGIC;
    m_axi_copy_BREADY : OUT STD_LOGIC;
    m_axi_copy_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_copy_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_copy_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    copy_V1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    copy_V1_ce0 : OUT STD_LOGIC;
    copy_V1_we0 : OUT STD_LOGIC;
    copy_V1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    xend : IN STD_LOGIC_VECTOR (31 downto 0);
    yend : IN STD_LOGIC_VECTOR (31 downto 0);
    ddr_update : IN STD_LOGIC_VECTOR (63 downto 0);
    width_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    width_out_full_n : IN STD_LOGIC;
    width_out_write : OUT STD_LOGIC;
    y_2_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    y_2_out_full_n : IN STD_LOGIC;
    y_2_out_write : OUT STD_LOGIC;
    frame_size_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    frame_size_out_full_n : IN STD_LOGIC;
    frame_size_out_write : OUT STD_LOGIC;
    xend_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xend_out_full_n : IN STD_LOGIC;
    xend_out_write : OUT STD_LOGIC;
    yend_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    yend_out_full_n : IN STD_LOGIC;
    yend_out_write : OUT STD_LOGIC;
    ddr_update_out_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    ddr_update_out_full_n : IN STD_LOGIC;
    ddr_update_out_write : OUT STD_LOGIC );
end;


architecture behav of display_shift_display_shift_label1_proc5 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (12 downto 0) := "0000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (12 downto 0) := "0000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (12 downto 0) := "0000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (12 downto 0) := "0000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (12 downto 0) := "0000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (12 downto 0) := "0000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (12 downto 0) := "0001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (12 downto 0) := "0010000000000";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (12 downto 0) := "0100000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal copy_blk_n_AR : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal copy_blk_n_R : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln878_reg_363 : STD_LOGIC_VECTOR (0 downto 0);
    signal width_out_blk_n : STD_LOGIC;
    signal y_2_out_blk_n : STD_LOGIC;
    signal frame_size_out_blk_n : STD_LOGIC;
    signal xend_out_blk_n : STD_LOGIC;
    signal yend_out_blk_n : STD_LOGIC;
    signal ddr_update_out_blk_n : STD_LOGIC;
    signal x_reg_224 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_reg_224_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state12_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ret_1_i_i_fu_244_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal ret_1_i_i_reg_332 : STD_LOGIC_VECTOR (33 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_fu_256_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal mul_ln534_reg_347 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal copy_addr_reg_352 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal add_ln37_fu_305_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln37_reg_358 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal icmp_ln878_fu_311_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_reg_363_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal copy_addr_read_reg_367 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state12 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_phi_mux_x_phi_fu_228_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln37_fu_316_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln324_fu_295_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal lhs_1_i_i_fu_236_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal lhs_1_i_i_fu_236_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal rhs_1_i_i_fu_240_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_256_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln534_2_fu_262_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal add_ln324_fu_266_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal shl_ln324_1_fu_271_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln324_1_fu_279_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln324_1_fu_285_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal grp_fu_256_p10 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component display_shift_mul_34s_32ns_62_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (33 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (61 downto 0) );
    end component;



begin
    mul_34s_32ns_62_2_1_U1 : component display_shift_mul_34s_32ns_62_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 34,
        din1_WIDTH => 32,
        dout_WIDTH => 62)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ret_1_i_i_reg_332,
        din1 => grp_fu_256_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_256_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state12) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state12)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state12);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    x_reg_224_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                x_reg_224 <= ap_const_lv32_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln878_reg_363 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                x_reg_224 <= add_ln37_reg_358;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln37_reg_358 <= add_ln37_fu_305_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln878_reg_363 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                copy_addr_read_reg_367 <= m_axi_copy_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                copy_addr_reg_352 <= sext_ln324_fu_295_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln878_reg_363 <= icmp_ln878_fu_311_p2;
                icmp_ln878_reg_363_pp0_iter1_reg <= icmp_ln878_reg_363;
                x_reg_224_pp0_iter1_reg <= x_reg_224;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                mul_ln534_reg_347 <= grp_fu_256_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                ret_1_i_i_reg_332 <= ret_1_i_i_fu_244_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, m_axi_copy_ARREADY, width_out_full_n, y_2_out_full_n, frame_size_out_full_n, xend_out_full_n, yend_out_full_n, ddr_update_out_full_n, ap_CS_fsm_state5, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0, icmp_ln878_fu_311_p2, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or (ddr_update_out_full_n = ap_const_logic_0) or (yend_out_full_n = ap_const_logic_0) or (xend_out_full_n = ap_const_logic_0) or (frame_size_out_full_n = ap_const_logic_0) or (y_2_out_full_n = ap_const_logic_0) or (width_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((m_axi_copy_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((icmp_ln878_fu_311_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) and not(((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)) or ((icmp_ln878_fu_311_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state15;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXX";
        end case;
    end process;
    add_ln324_1_fu_279_p2 <= std_logic_vector(unsigned(shl_ln324_1_fu_271_p3) + unsigned(ddr_copy));
    add_ln324_fu_266_p2 <= std_logic_vector(unsigned(mul_ln534_reg_347) + unsigned(zext_ln534_2_fu_262_p1));
    add_ln37_fu_305_p2 <= std_logic_vector(unsigned(ap_phi_mux_x_phi_fu_228_p4) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(11);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state15 <= ap_CS_fsm(12);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(m_axi_copy_RVALID, ap_enable_reg_pp0_iter1, icmp_ln878_reg_363)
    begin
                ap_block_pp0_stage0_11001 <= ((m_axi_copy_RVALID = ap_const_logic_0) and (icmp_ln878_reg_363 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(m_axi_copy_RVALID, ap_enable_reg_pp0_iter1, icmp_ln878_reg_363)
    begin
                ap_block_pp0_stage0_subdone <= ((m_axi_copy_RVALID = ap_const_logic_0) and (icmp_ln878_reg_363 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, width_out_full_n, y_2_out_full_n, frame_size_out_full_n, xend_out_full_n, yend_out_full_n, ddr_update_out_full_n)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or (ddr_update_out_full_n = ap_const_logic_0) or (yend_out_full_n = ap_const_logic_0) or (xend_out_full_n = ap_const_logic_0) or (frame_size_out_full_n = ap_const_logic_0) or (y_2_out_full_n = ap_const_logic_0) or (width_out_full_n = ap_const_logic_0));
    end process;

        ap_block_state12_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state13_pp0_stage0_iter1_assign_proc : process(m_axi_copy_RVALID, icmp_ln878_reg_363)
    begin
                ap_block_state13_pp0_stage0_iter1 <= ((m_axi_copy_RVALID = ap_const_logic_0) and (icmp_ln878_reg_363 = ap_const_lv1_0));
    end process;

        ap_block_state14_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state12_assign_proc : process(icmp_ln878_fu_311_p2)
    begin
        if ((icmp_ln878_fu_311_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state12 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state12 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state15)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_x_phi_fu_228_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln878_reg_363, x_reg_224, add_ln37_reg_358)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln878_reg_363 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            ap_phi_mux_x_phi_fu_228_p4 <= add_ln37_reg_358;
        else 
            ap_phi_mux_x_phi_fu_228_p4 <= x_reg_224;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state15)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    copy_V1_address0 <= zext_ln37_fu_316_p1(10 - 1 downto 0);

    copy_V1_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            copy_V1_ce0 <= ap_const_logic_1;
        else 
            copy_V1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    copy_V1_d0 <= copy_addr_read_reg_367;

    copy_V1_we0_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln878_reg_363_pp0_iter1_reg, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln878_reg_363_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            copy_V1_we0 <= ap_const_logic_1;
        else 
            copy_V1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    copy_blk_n_AR_assign_proc : process(m_axi_copy_ARREADY, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            copy_blk_n_AR <= m_axi_copy_ARREADY;
        else 
            copy_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    copy_blk_n_R_assign_proc : process(m_axi_copy_RVALID, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln878_reg_363)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln878_reg_363 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            copy_blk_n_R <= m_axi_copy_RVALID;
        else 
            copy_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    ddr_update_out_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, ddr_update_out_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ddr_update_out_blk_n <= ddr_update_out_full_n;
        else 
            ddr_update_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    ddr_update_out_din <= ddr_update;

    ddr_update_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, width_out_full_n, y_2_out_full_n, frame_size_out_full_n, xend_out_full_n, yend_out_full_n, ddr_update_out_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or (ddr_update_out_full_n = ap_const_logic_0) or (yend_out_full_n = ap_const_logic_0) or (xend_out_full_n = ap_const_logic_0) or (frame_size_out_full_n = ap_const_logic_0) or (y_2_out_full_n = ap_const_logic_0) or (width_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ddr_update_out_write <= ap_const_logic_1;
        else 
            ddr_update_out_write <= ap_const_logic_0;
        end if; 
    end process;


    frame_size_out_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, frame_size_out_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            frame_size_out_blk_n <= frame_size_out_full_n;
        else 
            frame_size_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    frame_size_out_din <= frame_size;

    frame_size_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, width_out_full_n, y_2_out_full_n, frame_size_out_full_n, xend_out_full_n, yend_out_full_n, ddr_update_out_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or (ddr_update_out_full_n = ap_const_logic_0) or (yend_out_full_n = ap_const_logic_0) or (xend_out_full_n = ap_const_logic_0) or (frame_size_out_full_n = ap_const_logic_0) or (y_2_out_full_n = ap_const_logic_0) or (width_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            frame_size_out_write <= ap_const_logic_1;
        else 
            frame_size_out_write <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_256_p1 <= grp_fu_256_p10(32 - 1 downto 0);
    grp_fu_256_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(frame_size),62));
    icmp_ln878_fu_311_p2 <= "1" when (ap_phi_mux_x_phi_fu_228_p4 = width) else "0";
    lhs_1_i_i_fu_236_p0 <= y_2;
        lhs_1_i_i_fu_236_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(lhs_1_i_i_fu_236_p0),34));

    m_axi_copy_ARADDR <= copy_addr_reg_352;
    m_axi_copy_ARBURST <= ap_const_lv2_0;
    m_axi_copy_ARCACHE <= ap_const_lv4_0;
    m_axi_copy_ARID <= ap_const_lv1_0;
    m_axi_copy_ARLEN <= width;
    m_axi_copy_ARLOCK <= ap_const_lv2_0;
    m_axi_copy_ARPROT <= ap_const_lv3_0;
    m_axi_copy_ARQOS <= ap_const_lv4_0;
    m_axi_copy_ARREGION <= ap_const_lv4_0;
    m_axi_copy_ARSIZE <= ap_const_lv3_0;
    m_axi_copy_ARUSER <= ap_const_lv1_0;

    m_axi_copy_ARVALID_assign_proc : process(m_axi_copy_ARREADY, ap_CS_fsm_state5)
    begin
        if (((m_axi_copy_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            m_axi_copy_ARVALID <= ap_const_logic_1;
        else 
            m_axi_copy_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_copy_AWADDR <= ap_const_lv64_0;
    m_axi_copy_AWBURST <= ap_const_lv2_0;
    m_axi_copy_AWCACHE <= ap_const_lv4_0;
    m_axi_copy_AWID <= ap_const_lv1_0;
    m_axi_copy_AWLEN <= ap_const_lv32_0;
    m_axi_copy_AWLOCK <= ap_const_lv2_0;
    m_axi_copy_AWPROT <= ap_const_lv3_0;
    m_axi_copy_AWQOS <= ap_const_lv4_0;
    m_axi_copy_AWREGION <= ap_const_lv4_0;
    m_axi_copy_AWSIZE <= ap_const_lv3_0;
    m_axi_copy_AWUSER <= ap_const_lv1_0;
    m_axi_copy_AWVALID <= ap_const_logic_0;
    m_axi_copy_BREADY <= ap_const_logic_0;

    m_axi_copy_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln878_reg_363, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln878_reg_363 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            m_axi_copy_RREADY <= ap_const_logic_1;
        else 
            m_axi_copy_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_copy_WDATA <= ap_const_lv32_0;
    m_axi_copy_WID <= ap_const_lv1_0;
    m_axi_copy_WLAST <= ap_const_logic_0;
    m_axi_copy_WSTRB <= ap_const_lv4_0;
    m_axi_copy_WUSER <= ap_const_lv1_0;
    m_axi_copy_WVALID <= ap_const_logic_0;
    ret_1_i_i_fu_244_p2 <= std_logic_vector(signed(lhs_1_i_i_fu_236_p1) + signed(rhs_1_i_i_fu_240_p1));
    rhs_1_i_i_fu_240_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ystart),34));
        sext_ln324_fu_295_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln324_1_fu_285_p4),64));

    shl_ln324_1_fu_271_p3 <= (add_ln324_fu_266_p2 & ap_const_lv2_0);
    trunc_ln324_1_fu_285_p4 <= add_ln324_1_fu_279_p2(63 downto 2);

    width_out_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, width_out_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            width_out_blk_n <= width_out_full_n;
        else 
            width_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    width_out_din <= width;

    width_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, width_out_full_n, y_2_out_full_n, frame_size_out_full_n, xend_out_full_n, yend_out_full_n, ddr_update_out_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or (ddr_update_out_full_n = ap_const_logic_0) or (yend_out_full_n = ap_const_logic_0) or (xend_out_full_n = ap_const_logic_0) or (frame_size_out_full_n = ap_const_logic_0) or (y_2_out_full_n = ap_const_logic_0) or (width_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            width_out_write <= ap_const_logic_1;
        else 
            width_out_write <= ap_const_logic_0;
        end if; 
    end process;


    xend_out_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, xend_out_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            xend_out_blk_n <= xend_out_full_n;
        else 
            xend_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xend_out_din <= xend;

    xend_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, width_out_full_n, y_2_out_full_n, frame_size_out_full_n, xend_out_full_n, yend_out_full_n, ddr_update_out_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or (ddr_update_out_full_n = ap_const_logic_0) or (yend_out_full_n = ap_const_logic_0) or (xend_out_full_n = ap_const_logic_0) or (frame_size_out_full_n = ap_const_logic_0) or (y_2_out_full_n = ap_const_logic_0) or (width_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            xend_out_write <= ap_const_logic_1;
        else 
            xend_out_write <= ap_const_logic_0;
        end if; 
    end process;


    y_2_out_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, y_2_out_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            y_2_out_blk_n <= y_2_out_full_n;
        else 
            y_2_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    y_2_out_din <= y_2;

    y_2_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, width_out_full_n, y_2_out_full_n, frame_size_out_full_n, xend_out_full_n, yend_out_full_n, ddr_update_out_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or (ddr_update_out_full_n = ap_const_logic_0) or (yend_out_full_n = ap_const_logic_0) or (xend_out_full_n = ap_const_logic_0) or (frame_size_out_full_n = ap_const_logic_0) or (y_2_out_full_n = ap_const_logic_0) or (width_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            y_2_out_write <= ap_const_logic_1;
        else 
            y_2_out_write <= ap_const_logic_0;
        end if; 
    end process;


    yend_out_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, yend_out_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            yend_out_blk_n <= yend_out_full_n;
        else 
            yend_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    yend_out_din <= yend;

    yend_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, width_out_full_n, y_2_out_full_n, frame_size_out_full_n, xend_out_full_n, yend_out_full_n, ddr_update_out_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or (ddr_update_out_full_n = ap_const_logic_0) or (yend_out_full_n = ap_const_logic_0) or (xend_out_full_n = ap_const_logic_0) or (frame_size_out_full_n = ap_const_logic_0) or (y_2_out_full_n = ap_const_logic_0) or (width_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            yend_out_write <= ap_const_logic_1;
        else 
            yend_out_write <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln37_fu_316_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_reg_224_pp0_iter1_reg),64));
    zext_ln534_2_fu_262_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xstart),62));
end behav;
