webtalk_init -webtalk_dir /home/koutakimura/workspace/ProjectFolder/Xilinx/workspace/ArtyS7/SignalTraining/mSignal.sim/sim_1/behav/xsim/xsim.dir/nv_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Nov 21 14:16:59 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "185e2bdb-ca6a-4337-a90e-b3845e533580" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "68407fe69acf4b0ea622c97fef32fc1f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "36" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2600.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "108220 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "116368_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1095156249 -regid "" -xml /home/koutakimura/workspace/ProjectFolder/Xilinx/workspace/ArtyS7/SignalTraining/mSignal.sim/sim_1/behav/xsim/xsim.dir/nv_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/koutakimura/workspace/ProjectFolder/Xilinx/workspace/ArtyS7/SignalTraining/mSignal.sim/sim_1/behav/xsim/xsim.dir/nv_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/koutakimura/workspace/ProjectFolder/Xilinx/workspace/ArtyS7/SignalTraining/mSignal.sim/sim_1/behav/xsim/xsim.dir/nv_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
