
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xsound_operation.h"

/*
* The configuration table for devices
*/

XSound_operation_Config XSound_operation_ConfigTable[XPAR_XSOUND_OPERATION_NUM_INSTANCES] =
{
	{
		XPAR_SOUND_OPERATION_0_DEVICE_ID,
		XPAR_SOUND_OPERATION_0_S_AXI_CONTROL_BASEADDR
	}
};


