/*
 * Create 2021/07/15
 * Author koutakimura
 * Editor VSCode ver1.57.1
 * Build  Vitis20.2
 * Borad  ArtyZ7-20
 * -
 * IC      XC7Z020-1CLG400C
 * ROM     256KB
 * RAM     512KB
 * L1Cache 32KB
 * -
 * ファイルデータにアクセスするとぃすうをまとめたヘッダーファイル
 */

#ifndef cmd_msg_macro_h   /* prevent circular inclusions */
#define cmd_msg_macro_h   /* by using protection macros */


/*
 * コマンドメッセージ定数を定義
 */
typedef enum
{
	CMD_MSG_ID_0,
	CMD_MSG_ID_1,
	CMD_MSG_ID_2,
	CMD_MSG_ID_3,
	CMD_MSG_ID_4,
	CMD_MSG_ID_5,
	CMD_MSG_ID_6,
	CMD_MSG_ID_7,
	CMD_MSG_ID_8,
	CMD_MSG_ID_9,
	CMD_MSG_ID_MINORIKO,
	CMD_MSG_ID_SIZUHA,
	CMD_MSG_ID_KANAKO,
	CMD_MSG_ID_KOGASA,
	CMD_MSG_ID_YUUKA,
	CMD_MSG_ID_REMIRIA,
	CMD_MSG_ID_SATORI,
	CMD_MSG_ID_TENSI,
	CMD_MSG_ID_MAGIC_POWER,
	CMD_MSG_ID_SLASH,
	CMD_MSG_ID_FIGHT,
	CMD_MSG_ID_MAGIC,
	CMD_MSG_ID_ITEM,
	CMD_MSG_ID_CHANGE,
	CMD_MSG_ID_TOLK,
	CMD_MSG_ID_ESCAPE,
	CMD_MSG_ID_GET_EXP,
	CMD_MSG_ID_GET_GOLD,
	CMD_MSG_ID_LV_UP_MINORIKO,
	CMD_MSG_ID_LV_UP_SIZUHA,
	CMD_MSG_ID_LV_UP_KANAKO,
	CMD_MSG_ID_LV_UP_KOGASA,
	CMD_MSG_ID_LV_UP_YUUKA,
	CMD_MSG_ID_LV_UP_REMIRIA,
	CMD_MSG_ID_LV_UP_SATORI,
	CMD_MSG_ID_LV_UP_TENSI,
    CMD_MSG_ID_SKILL_MINORIKO,
    CMD_MSG_ID_SKILL_SIZUHA,
    CMD_MSG_ID_SKILL_KANAKO,
    CMD_MSG_ID_SKILL_KOGASA,
    CMD_MSG_ID_SKILL_YUUKA,
    CMD_MSG_ID_SKILL_REMIRIA,
    CMD_MSG_ID_SKILL_SATRI,
    CMD_MSG_ID_SKILL_TENSI,
    CMD_MSG_ID_LOAD_GAME_1,
    CMD_MSG_ID_BATTLE_DEATH,
    CMD_MSG_ID_BATTLE_ESCAPE,
    CMD_MSG_ID_MENU_SELECT,
	CMD_MSG_ID_MENU_EART,
    CMD_MSG_ID_MENU_MASTER,
    CMD_MSG_ID_MENU_MASTER_LV1,
    CMD_MSG_ID_MENU_MASTER_LV2,
    CMD_MSG_ID_MENU_MASTER_LV3,
    CMD_MSG_ID_MENU_MASTER_LV4,
    CMD_MSG_ID_MENU_MASTER_LV5,
    CMD_MSG_ID_MENU_COOK_SUCCESS,
    CMD_MSG_ID_MENU_COOK_FAILD,
    CMD_MSG_ID_MENU_PATY_EQUIP,
    CMD_MSG_ID_MENU_PATY_STATUS,
    CMD_MSG_ID_MENU_PATY_WEAPON_ATK,
    CMD_MSG_ID_MENU_PATY_ARMOR_DEF,
	CMD_MSG_ID_END,
} CmdMsgID;

#endif