// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module background_loop_dataflow_parent_loop_proc4 (
        height,
        ycopy_V_address0,
        ycopy_V_ce0,
        ycopy_V_d0,
        ycopy_V_q0,
        ycopy_V_we0,
        ycopy_V_address1,
        ycopy_V_ce1,
        ycopy_V_d1,
        ycopy_V_q1,
        ycopy_V_we1,
        m_axi_update_AWVALID,
        m_axi_update_AWREADY,
        m_axi_update_AWADDR,
        m_axi_update_AWID,
        m_axi_update_AWLEN,
        m_axi_update_AWSIZE,
        m_axi_update_AWBURST,
        m_axi_update_AWLOCK,
        m_axi_update_AWCACHE,
        m_axi_update_AWPROT,
        m_axi_update_AWQOS,
        m_axi_update_AWREGION,
        m_axi_update_AWUSER,
        m_axi_update_WVALID,
        m_axi_update_WREADY,
        m_axi_update_WDATA,
        m_axi_update_WSTRB,
        m_axi_update_WLAST,
        m_axi_update_WID,
        m_axi_update_WUSER,
        m_axi_update_ARVALID,
        m_axi_update_ARREADY,
        m_axi_update_ARADDR,
        m_axi_update_ARID,
        m_axi_update_ARLEN,
        m_axi_update_ARSIZE,
        m_axi_update_ARBURST,
        m_axi_update_ARLOCK,
        m_axi_update_ARCACHE,
        m_axi_update_ARPROT,
        m_axi_update_ARQOS,
        m_axi_update_ARREGION,
        m_axi_update_ARUSER,
        m_axi_update_RVALID,
        m_axi_update_RREADY,
        m_axi_update_RDATA,
        m_axi_update_RLAST,
        m_axi_update_RID,
        m_axi_update_RUSER,
        m_axi_update_RRESP,
        m_axi_update_BVALID,
        m_axi_update_BREADY,
        m_axi_update_BRESP,
        m_axi_update_BID,
        m_axi_update_BUSER,
        frame_size,
        ddr_update,
        ap_clk,
        ap_rst,
        frame_size_ap_vld,
        ddr_update_ap_vld,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [31:0] height;
output  [9:0] ycopy_V_address0;
output   ycopy_V_ce0;
output  [31:0] ycopy_V_d0;
input  [31:0] ycopy_V_q0;
output   ycopy_V_we0;
output  [9:0] ycopy_V_address1;
output   ycopy_V_ce1;
output  [31:0] ycopy_V_d1;
input  [31:0] ycopy_V_q1;
output   ycopy_V_we1;
output   m_axi_update_AWVALID;
input   m_axi_update_AWREADY;
output  [63:0] m_axi_update_AWADDR;
output  [0:0] m_axi_update_AWID;
output  [31:0] m_axi_update_AWLEN;
output  [2:0] m_axi_update_AWSIZE;
output  [1:0] m_axi_update_AWBURST;
output  [1:0] m_axi_update_AWLOCK;
output  [3:0] m_axi_update_AWCACHE;
output  [2:0] m_axi_update_AWPROT;
output  [3:0] m_axi_update_AWQOS;
output  [3:0] m_axi_update_AWREGION;
output  [0:0] m_axi_update_AWUSER;
output   m_axi_update_WVALID;
input   m_axi_update_WREADY;
output  [31:0] m_axi_update_WDATA;
output  [3:0] m_axi_update_WSTRB;
output   m_axi_update_WLAST;
output  [0:0] m_axi_update_WID;
output  [0:0] m_axi_update_WUSER;
output   m_axi_update_ARVALID;
input   m_axi_update_ARREADY;
output  [63:0] m_axi_update_ARADDR;
output  [0:0] m_axi_update_ARID;
output  [31:0] m_axi_update_ARLEN;
output  [2:0] m_axi_update_ARSIZE;
output  [1:0] m_axi_update_ARBURST;
output  [1:0] m_axi_update_ARLOCK;
output  [3:0] m_axi_update_ARCACHE;
output  [2:0] m_axi_update_ARPROT;
output  [3:0] m_axi_update_ARQOS;
output  [3:0] m_axi_update_ARREGION;
output  [0:0] m_axi_update_ARUSER;
input   m_axi_update_RVALID;
output   m_axi_update_RREADY;
input  [31:0] m_axi_update_RDATA;
input   m_axi_update_RLAST;
input  [0:0] m_axi_update_RID;
input  [0:0] m_axi_update_RUSER;
input  [1:0] m_axi_update_RRESP;
input   m_axi_update_BVALID;
output   m_axi_update_BREADY;
input  [1:0] m_axi_update_BRESP;
input  [0:0] m_axi_update_BID;
input  [0:0] m_axi_update_BUSER;
input  [31:0] frame_size;
input  [63:0] ddr_update;
input   ap_clk;
input   ap_rst;
input   frame_size_ap_vld;
input   ddr_update_ap_vld;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

reg ap_done;
reg ap_ready;
reg ap_idle;

wire   [9:0] dataflow_in_loop_copy2_U0_ycopy_V_address0;
wire    dataflow_in_loop_copy2_U0_ycopy_V_ce0;
wire   [31:0] dataflow_in_loop_copy2_U0_ycopy_V_d0;
wire    dataflow_in_loop_copy2_U0_ycopy_V_we0;
wire   [9:0] dataflow_in_loop_copy2_U0_ycopy_V_address1;
wire    dataflow_in_loop_copy2_U0_ycopy_V_ce1;
wire   [31:0] dataflow_in_loop_copy2_U0_ycopy_V_d1;
wire    dataflow_in_loop_copy2_U0_ycopy_V_we1;
wire    dataflow_in_loop_copy2_U0_m_axi_update_AWVALID;
wire   [63:0] dataflow_in_loop_copy2_U0_m_axi_update_AWADDR;
wire   [0:0] dataflow_in_loop_copy2_U0_m_axi_update_AWID;
wire   [31:0] dataflow_in_loop_copy2_U0_m_axi_update_AWLEN;
wire   [2:0] dataflow_in_loop_copy2_U0_m_axi_update_AWSIZE;
wire   [1:0] dataflow_in_loop_copy2_U0_m_axi_update_AWBURST;
wire   [1:0] dataflow_in_loop_copy2_U0_m_axi_update_AWLOCK;
wire   [3:0] dataflow_in_loop_copy2_U0_m_axi_update_AWCACHE;
wire   [2:0] dataflow_in_loop_copy2_U0_m_axi_update_AWPROT;
wire   [3:0] dataflow_in_loop_copy2_U0_m_axi_update_AWQOS;
wire   [3:0] dataflow_in_loop_copy2_U0_m_axi_update_AWREGION;
wire   [0:0] dataflow_in_loop_copy2_U0_m_axi_update_AWUSER;
wire    dataflow_in_loop_copy2_U0_m_axi_update_WVALID;
wire   [31:0] dataflow_in_loop_copy2_U0_m_axi_update_WDATA;
wire   [3:0] dataflow_in_loop_copy2_U0_m_axi_update_WSTRB;
wire    dataflow_in_loop_copy2_U0_m_axi_update_WLAST;
wire   [0:0] dataflow_in_loop_copy2_U0_m_axi_update_WID;
wire   [0:0] dataflow_in_loop_copy2_U0_m_axi_update_WUSER;
wire    dataflow_in_loop_copy2_U0_m_axi_update_ARVALID;
wire   [63:0] dataflow_in_loop_copy2_U0_m_axi_update_ARADDR;
wire   [0:0] dataflow_in_loop_copy2_U0_m_axi_update_ARID;
wire   [31:0] dataflow_in_loop_copy2_U0_m_axi_update_ARLEN;
wire   [2:0] dataflow_in_loop_copy2_U0_m_axi_update_ARSIZE;
wire   [1:0] dataflow_in_loop_copy2_U0_m_axi_update_ARBURST;
wire   [1:0] dataflow_in_loop_copy2_U0_m_axi_update_ARLOCK;
wire   [3:0] dataflow_in_loop_copy2_U0_m_axi_update_ARCACHE;
wire   [2:0] dataflow_in_loop_copy2_U0_m_axi_update_ARPROT;
wire   [3:0] dataflow_in_loop_copy2_U0_m_axi_update_ARQOS;
wire   [3:0] dataflow_in_loop_copy2_U0_m_axi_update_ARREGION;
wire   [0:0] dataflow_in_loop_copy2_U0_m_axi_update_ARUSER;
wire    dataflow_in_loop_copy2_U0_m_axi_update_RREADY;
wire    dataflow_in_loop_copy2_U0_m_axi_update_BREADY;
wire    dataflow_in_loop_copy2_U0_ap_start;
wire    dataflow_in_loop_copy2_U0_ap_done;
wire    dataflow_in_loop_copy2_U0_ap_ready;
wire    dataflow_in_loop_copy2_U0_ap_idle;
reg    dataflow_in_loop_copy2_U0_ap_continue;
wire    ap_sync_continue;
wire    ap_sync_done;
wire    ap_sync_ready;
reg   [31:0] loop_dataflow_input_count;
reg   [31:0] loop_dataflow_output_count;
wire   [31:0] bound_minus_1;
wire    dataflow_in_loop_copy2_U0_start_full_n;
wire    dataflow_in_loop_copy2_U0_start_write;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 loop_dataflow_input_count = 32'd0;
#0 loop_dataflow_output_count = 32'd0;
end

background_loop_dataflow_in_loop_copy2 dataflow_in_loop_copy2_U0(
    .ycopy_V_address0(dataflow_in_loop_copy2_U0_ycopy_V_address0),
    .ycopy_V_ce0(dataflow_in_loop_copy2_U0_ycopy_V_ce0),
    .ycopy_V_d0(dataflow_in_loop_copy2_U0_ycopy_V_d0),
    .ycopy_V_q0(ycopy_V_q0),
    .ycopy_V_we0(dataflow_in_loop_copy2_U0_ycopy_V_we0),
    .ycopy_V_address1(dataflow_in_loop_copy2_U0_ycopy_V_address1),
    .ycopy_V_ce1(dataflow_in_loop_copy2_U0_ycopy_V_ce1),
    .ycopy_V_d1(dataflow_in_loop_copy2_U0_ycopy_V_d1),
    .ycopy_V_q1(32'd0),
    .ycopy_V_we1(dataflow_in_loop_copy2_U0_ycopy_V_we1),
    .trunc_ln329(loop_dataflow_input_count),
    .m_axi_update_AWVALID(dataflow_in_loop_copy2_U0_m_axi_update_AWVALID),
    .m_axi_update_AWREADY(m_axi_update_AWREADY),
    .m_axi_update_AWADDR(dataflow_in_loop_copy2_U0_m_axi_update_AWADDR),
    .m_axi_update_AWID(dataflow_in_loop_copy2_U0_m_axi_update_AWID),
    .m_axi_update_AWLEN(dataflow_in_loop_copy2_U0_m_axi_update_AWLEN),
    .m_axi_update_AWSIZE(dataflow_in_loop_copy2_U0_m_axi_update_AWSIZE),
    .m_axi_update_AWBURST(dataflow_in_loop_copy2_U0_m_axi_update_AWBURST),
    .m_axi_update_AWLOCK(dataflow_in_loop_copy2_U0_m_axi_update_AWLOCK),
    .m_axi_update_AWCACHE(dataflow_in_loop_copy2_U0_m_axi_update_AWCACHE),
    .m_axi_update_AWPROT(dataflow_in_loop_copy2_U0_m_axi_update_AWPROT),
    .m_axi_update_AWQOS(dataflow_in_loop_copy2_U0_m_axi_update_AWQOS),
    .m_axi_update_AWREGION(dataflow_in_loop_copy2_U0_m_axi_update_AWREGION),
    .m_axi_update_AWUSER(dataflow_in_loop_copy2_U0_m_axi_update_AWUSER),
    .m_axi_update_WVALID(dataflow_in_loop_copy2_U0_m_axi_update_WVALID),
    .m_axi_update_WREADY(m_axi_update_WREADY),
    .m_axi_update_WDATA(dataflow_in_loop_copy2_U0_m_axi_update_WDATA),
    .m_axi_update_WSTRB(dataflow_in_loop_copy2_U0_m_axi_update_WSTRB),
    .m_axi_update_WLAST(dataflow_in_loop_copy2_U0_m_axi_update_WLAST),
    .m_axi_update_WID(dataflow_in_loop_copy2_U0_m_axi_update_WID),
    .m_axi_update_WUSER(dataflow_in_loop_copy2_U0_m_axi_update_WUSER),
    .m_axi_update_ARVALID(dataflow_in_loop_copy2_U0_m_axi_update_ARVALID),
    .m_axi_update_ARREADY(1'b0),
    .m_axi_update_ARADDR(dataflow_in_loop_copy2_U0_m_axi_update_ARADDR),
    .m_axi_update_ARID(dataflow_in_loop_copy2_U0_m_axi_update_ARID),
    .m_axi_update_ARLEN(dataflow_in_loop_copy2_U0_m_axi_update_ARLEN),
    .m_axi_update_ARSIZE(dataflow_in_loop_copy2_U0_m_axi_update_ARSIZE),
    .m_axi_update_ARBURST(dataflow_in_loop_copy2_U0_m_axi_update_ARBURST),
    .m_axi_update_ARLOCK(dataflow_in_loop_copy2_U0_m_axi_update_ARLOCK),
    .m_axi_update_ARCACHE(dataflow_in_loop_copy2_U0_m_axi_update_ARCACHE),
    .m_axi_update_ARPROT(dataflow_in_loop_copy2_U0_m_axi_update_ARPROT),
    .m_axi_update_ARQOS(dataflow_in_loop_copy2_U0_m_axi_update_ARQOS),
    .m_axi_update_ARREGION(dataflow_in_loop_copy2_U0_m_axi_update_ARREGION),
    .m_axi_update_ARUSER(dataflow_in_loop_copy2_U0_m_axi_update_ARUSER),
    .m_axi_update_RVALID(1'b0),
    .m_axi_update_RREADY(dataflow_in_loop_copy2_U0_m_axi_update_RREADY),
    .m_axi_update_RDATA(32'd0),
    .m_axi_update_RLAST(1'b0),
    .m_axi_update_RID(1'd0),
    .m_axi_update_RUSER(1'd0),
    .m_axi_update_RRESP(2'd0),
    .m_axi_update_BVALID(m_axi_update_BVALID),
    .m_axi_update_BREADY(dataflow_in_loop_copy2_U0_m_axi_update_BREADY),
    .m_axi_update_BRESP(m_axi_update_BRESP),
    .m_axi_update_BID(m_axi_update_BID),
    .m_axi_update_BUSER(m_axi_update_BUSER),
    .frame_size(frame_size),
    .ddr_update(ddr_update),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .trunc_ln329_ap_vld(1'b0),
    .frame_size_ap_vld(frame_size_ap_vld),
    .ddr_update_ap_vld(ddr_update_ap_vld),
    .ap_start(dataflow_in_loop_copy2_U0_ap_start),
    .ap_done(dataflow_in_loop_copy2_U0_ap_done),
    .ap_ready(dataflow_in_loop_copy2_U0_ap_ready),
    .ap_idle(dataflow_in_loop_copy2_U0_ap_idle),
    .ap_continue(dataflow_in_loop_copy2_U0_ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        loop_dataflow_input_count <= 32'd0;
    end else begin
        if ((~(loop_dataflow_input_count == bound_minus_1) & (ap_start == 1'b1) & (dataflow_in_loop_copy2_U0_ap_ready == 1'b1))) begin
            loop_dataflow_input_count <= (loop_dataflow_input_count + 32'd1);
        end else if (((loop_dataflow_input_count == bound_minus_1) & (ap_start == 1'b1) & (dataflow_in_loop_copy2_U0_ap_ready == 1'b1))) begin
            loop_dataflow_input_count <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        loop_dataflow_output_count <= 32'd0;
    end else begin
        if ((~(loop_dataflow_output_count == bound_minus_1) & (dataflow_in_loop_copy2_U0_ap_continue == 1'b1) & (dataflow_in_loop_copy2_U0_ap_done == 1'b1))) begin
            loop_dataflow_output_count <= (loop_dataflow_output_count + 32'd1);
        end else if (((loop_dataflow_output_count == bound_minus_1) & (dataflow_in_loop_copy2_U0_ap_continue == 1'b1) & (dataflow_in_loop_copy2_U0_ap_done == 1'b1))) begin
            loop_dataflow_output_count <= 32'd0;
        end
    end
end

always @ (*) begin
    if (((loop_dataflow_output_count == bound_minus_1) & (dataflow_in_loop_copy2_U0_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((loop_dataflow_output_count == 32'd0) & (ap_start == 1'b0) & (dataflow_in_loop_copy2_U0_ap_idle == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((loop_dataflow_input_count == bound_minus_1) & (ap_start == 1'b1) & (dataflow_in_loop_copy2_U0_ap_ready == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~(loop_dataflow_output_count == bound_minus_1) | (ap_continue == 1'b1))) begin
        dataflow_in_loop_copy2_U0_ap_continue = 1'b1;
    end else begin
        dataflow_in_loop_copy2_U0_ap_continue = 1'b0;
    end
end

assign ap_sync_continue = ap_continue;

assign ap_sync_done = dataflow_in_loop_copy2_U0_ap_done;

assign ap_sync_ready = dataflow_in_loop_copy2_U0_ap_ready;

assign bound_minus_1 = (height - 32'd1);

assign dataflow_in_loop_copy2_U0_ap_start = ap_start;

assign dataflow_in_loop_copy2_U0_start_full_n = 1'b1;

assign dataflow_in_loop_copy2_U0_start_write = 1'b0;

assign m_axi_update_ARADDR = 64'd0;

assign m_axi_update_ARBURST = 2'd0;

assign m_axi_update_ARCACHE = 4'd0;

assign m_axi_update_ARID = 1'd0;

assign m_axi_update_ARLEN = 32'd0;

assign m_axi_update_ARLOCK = 2'd0;

assign m_axi_update_ARPROT = 3'd0;

assign m_axi_update_ARQOS = 4'd0;

assign m_axi_update_ARREGION = 4'd0;

assign m_axi_update_ARSIZE = 3'd0;

assign m_axi_update_ARUSER = 1'd0;

assign m_axi_update_ARVALID = 1'b0;

assign m_axi_update_AWADDR = dataflow_in_loop_copy2_U0_m_axi_update_AWADDR;

assign m_axi_update_AWBURST = dataflow_in_loop_copy2_U0_m_axi_update_AWBURST;

assign m_axi_update_AWCACHE = dataflow_in_loop_copy2_U0_m_axi_update_AWCACHE;

assign m_axi_update_AWID = dataflow_in_loop_copy2_U0_m_axi_update_AWID;

assign m_axi_update_AWLEN = dataflow_in_loop_copy2_U0_m_axi_update_AWLEN;

assign m_axi_update_AWLOCK = dataflow_in_loop_copy2_U0_m_axi_update_AWLOCK;

assign m_axi_update_AWPROT = dataflow_in_loop_copy2_U0_m_axi_update_AWPROT;

assign m_axi_update_AWQOS = dataflow_in_loop_copy2_U0_m_axi_update_AWQOS;

assign m_axi_update_AWREGION = dataflow_in_loop_copy2_U0_m_axi_update_AWREGION;

assign m_axi_update_AWSIZE = dataflow_in_loop_copy2_U0_m_axi_update_AWSIZE;

assign m_axi_update_AWUSER = dataflow_in_loop_copy2_U0_m_axi_update_AWUSER;

assign m_axi_update_AWVALID = dataflow_in_loop_copy2_U0_m_axi_update_AWVALID;

assign m_axi_update_BREADY = dataflow_in_loop_copy2_U0_m_axi_update_BREADY;

assign m_axi_update_RREADY = 1'b0;

assign m_axi_update_WDATA = dataflow_in_loop_copy2_U0_m_axi_update_WDATA;

assign m_axi_update_WID = dataflow_in_loop_copy2_U0_m_axi_update_WID;

assign m_axi_update_WLAST = dataflow_in_loop_copy2_U0_m_axi_update_WLAST;

assign m_axi_update_WSTRB = dataflow_in_loop_copy2_U0_m_axi_update_WSTRB;

assign m_axi_update_WUSER = dataflow_in_loop_copy2_U0_m_axi_update_WUSER;

assign m_axi_update_WVALID = dataflow_in_loop_copy2_U0_m_axi_update_WVALID;

assign ycopy_V_address0 = dataflow_in_loop_copy2_U0_ycopy_V_address0;

assign ycopy_V_address1 = 10'd0;

assign ycopy_V_ce0 = dataflow_in_loop_copy2_U0_ycopy_V_ce0;

assign ycopy_V_ce1 = 1'b0;

assign ycopy_V_d0 = 32'd0;

assign ycopy_V_d1 = 32'd0;

assign ycopy_V_we0 = 1'b0;

assign ycopy_V_we1 = 1'b0;

endmodule //background_loop_dataflow_parent_loop_proc4
