-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mapchip_png_dstout_loop_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    mapchip_draw_xsize_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    mapchip_draw_xsize_empty_n : IN STD_LOGIC;
    mapchip_draw_xsize_read : OUT STD_LOGIC;
    src_V1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    src_V1_ce0 : OUT STD_LOGIC;
    src_V1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    dst_V2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    dst_V2_ce0 : OUT STD_LOGIC;
    dst_V2_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    alpha_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    alpha_empty_n : IN STD_LOGIC;
    alpha_read : OUT STD_LOGIC;
    y_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    y_empty_n : IN STD_LOGIC;
    y_read : OUT STD_LOGIC;
    frame_size_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    frame_size_empty_n : IN STD_LOGIC;
    frame_size_read : OUT STD_LOGIC;
    dstout_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    dstout_empty_n : IN STD_LOGIC;
    dstout_read : OUT STD_LOGIC;
    m_axi_dst_AWVALID : OUT STD_LOGIC;
    m_axi_dst_AWREADY : IN STD_LOGIC;
    m_axi_dst_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_dst_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dst_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_dst_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_dst_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_dst_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_dst_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_dst_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_dst_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_dst_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_dst_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dst_WVALID : OUT STD_LOGIC;
    m_axi_dst_WREADY : IN STD_LOGIC;
    m_axi_dst_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_dst_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_dst_WLAST : OUT STD_LOGIC;
    m_axi_dst_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dst_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dst_ARVALID : OUT STD_LOGIC;
    m_axi_dst_ARREADY : IN STD_LOGIC;
    m_axi_dst_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_dst_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dst_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_dst_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_dst_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_dst_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_dst_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_dst_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_dst_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_dst_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_dst_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dst_RVALID : IN STD_LOGIC;
    m_axi_dst_RREADY : OUT STD_LOGIC;
    m_axi_dst_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_dst_RLAST : IN STD_LOGIC;
    m_axi_dst_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dst_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dst_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_dst_BVALID : IN STD_LOGIC;
    m_axi_dst_BREADY : OUT STD_LOGIC;
    m_axi_dst_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_dst_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dst_BUSER : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of mapchip_png_dstout_loop_proc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (10 downto 0) := "00000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (10 downto 0) := "00000010000";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (10 downto 0) := "00000100000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (10 downto 0) := "00001000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (10 downto 0) := "00010000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (10 downto 0) := "00100000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (10 downto 0) := "01000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv33_10102 : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000010000000100000010";
    constant ap_const_lv35_20203 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000100000001000000011";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal mapchip_draw_xsize_blk_n : STD_LOGIC;
    signal alpha_blk_n : STD_LOGIC;
    signal y_blk_n : STD_LOGIC;
    signal frame_size_blk_n : STD_LOGIC;
    signal dstout_blk_n : STD_LOGIC;
    signal dst_blk_n_AW : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal dst_blk_n_W : STD_LOGIC;
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln878_reg_617 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_reg_617_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal dst_blk_n_B : STD_LOGIC;
    signal ap_CS_fsm_state22 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state22 : signal is "none";
    signal x_reg_183 : STD_LOGIC_VECTOR (31 downto 0);
    signal mapchip_draw_xsize_read_reg_558 : STD_LOGIC_VECTOR (31 downto 0);
    signal alpha_read_reg_564 : STD_LOGIC_VECTOR (7 downto 0);
    signal y_read_reg_569 : STD_LOGIC_VECTOR (31 downto 0);
    signal frame_size_read_reg_574 : STD_LOGIC_VECTOR (31 downto 0);
    signal dstout_read_reg_579 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_fu_200_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal mul_i_i70_i_reg_594 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal dst_addr_reg_599 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal zext_ln63_fu_238_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln63_reg_605 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln75_fu_241_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_state6_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state16_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state17_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_state17_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln878_fu_247_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_reg_617_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_reg_617_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_reg_617_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_reg_617_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_reg_617_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_reg_617_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_reg_617_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_reg_617_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_reg_617_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln75_fu_252_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln75_reg_621 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln75_reg_621_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln75_reg_621_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal src_g_V_fu_257_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_g_V_reg_631 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln_reg_636 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln_reg_636_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln_reg_636_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln_reg_636_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln_reg_636_pp0_iter5_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln1_reg_642 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_reg_647 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1345_3_fu_368_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_reg_694 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_1_reg_699 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_2_reg_704 : STD_LOGIC_VECTOR (8 downto 0);
    signal dst_r_V_reg_739 : STD_LOGIC_VECTOR (7 downto 0);
    signal dst_b_V_reg_744 : STD_LOGIC_VECTOR (7 downto 0);
    signal dst_g_V_reg_749 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state6 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal sext_ln329_fu_228_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_block_state1 : BOOLEAN;
    signal grp_fu_200_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_200_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln329_1_fu_206_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln329_fu_213_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln329_1_fu_218_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal mul_ln1364_fu_300_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1364_fu_300_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1364_fu_300_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1364_1_fu_309_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1364_1_fu_309_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1364_1_fu_309_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1364_2_fu_318_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1364_2_fu_318_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1364_2_fu_318_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal dst_g_V_2_fu_327_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln1345_1_fu_335_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_1_fu_349_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_9_fu_363_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_489_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal grp_fu_496_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal grp_fu_503_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal ret_8_fu_405_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal ret_8_fu_405_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1345_1_fu_399_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ret_8_fu_405_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ret_11_fu_418_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal ret_11_fu_418_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_11_fu_418_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ret_13_fu_431_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal ret_13_fu_431_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_13_fu_431_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_528_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_519_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_510_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_537_p2 : STD_LOGIC_VECTOR (34 downto 0);
    signal grp_fu_544_p2 : STD_LOGIC_VECTOR (34 downto 0);
    signal grp_fu_551_p2 : STD_LOGIC_VECTOR (34 downto 0);
    signal color_V_fu_477_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_fu_489_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_489_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_496_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_496_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_503_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_503_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_510_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_510_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_510_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_519_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_519_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_519_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_528_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_528_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_528_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_537_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_537_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_544_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_544_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_551_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_551_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_489_ce : STD_LOGIC;
    signal grp_fu_496_ce : STD_LOGIC;
    signal grp_fu_503_ce : STD_LOGIC;
    signal grp_fu_510_ce : STD_LOGIC;
    signal grp_fu_519_ce : STD_LOGIC;
    signal grp_fu_528_ce : STD_LOGIC;
    signal grp_fu_537_ce : STD_LOGIC;
    signal grp_fu_544_ce : STD_LOGIC;
    signal grp_fu_551_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal grp_fu_200_p00 : STD_LOGIC_VECTOR (61 downto 0);
    signal grp_fu_200_p10 : STD_LOGIC_VECTOR (61 downto 0);
    signal grp_fu_489_p00 : STD_LOGIC_VECTOR (32 downto 0);
    signal grp_fu_496_p00 : STD_LOGIC_VECTOR (32 downto 0);
    signal grp_fu_503_p00 : STD_LOGIC_VECTOR (32 downto 0);
    signal grp_fu_510_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_510_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_519_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_519_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_528_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_528_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_537_p00 : STD_LOGIC_VECTOR (34 downto 0);
    signal grp_fu_544_p00 : STD_LOGIC_VECTOR (34 downto 0);
    signal grp_fu_551_p00 : STD_LOGIC_VECTOR (34 downto 0);
    signal mul_ln1364_1_fu_309_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1364_2_fu_318_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1364_fu_300_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal ret_11_fu_418_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal ret_13_fu_431_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal ret_8_fu_405_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component mapchip_png_mul_32ns_32ns_62_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (61 downto 0) );
    end component;


    component mapchip_png_mul_8ns_8ns_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component mapchip_png_mul_9ns_8ns_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component mapchip_png_mul_mul_16ns_18ns_33_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (17 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (32 downto 0) );
    end component;


    component mapchip_png_mac_muladd_8ns_8ns_16ns_17_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component mapchip_png_mul_mul_17ns_19ns_35_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (18 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (34 downto 0) );
    end component;



begin
    mul_32ns_32ns_62_2_1_U52 : component mapchip_png_mul_32ns_32ns_62_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 62)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_200_p0,
        din1 => grp_fu_200_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_200_p2);

    mul_8ns_8ns_16_1_1_U53 : component mapchip_png_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln1364_fu_300_p0,
        din1 => mul_ln1364_fu_300_p1,
        dout => mul_ln1364_fu_300_p2);

    mul_8ns_8ns_16_1_1_U54 : component mapchip_png_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln1364_1_fu_309_p0,
        din1 => mul_ln1364_1_fu_309_p1,
        dout => mul_ln1364_1_fu_309_p2);

    mul_8ns_8ns_16_1_1_U55 : component mapchip_png_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln1364_2_fu_318_p0,
        din1 => mul_ln1364_2_fu_318_p1,
        dout => mul_ln1364_2_fu_318_p2);

    mul_9ns_8ns_16_1_1_U56 : component mapchip_png_mul_9ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 9,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => ret_8_fu_405_p0,
        din1 => ret_8_fu_405_p1,
        dout => ret_8_fu_405_p2);

    mul_9ns_8ns_16_1_1_U57 : component mapchip_png_mul_9ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 9,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => ret_11_fu_418_p0,
        din1 => ret_11_fu_418_p1,
        dout => ret_11_fu_418_p2);

    mul_9ns_8ns_16_1_1_U58 : component mapchip_png_mul_9ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 9,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => ret_13_fu_431_p0,
        din1 => ret_13_fu_431_p1,
        dout => ret_13_fu_431_p2);

    mul_mul_16ns_18ns_33_4_1_U59 : component mapchip_png_mul_mul_16ns_18ns_33_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 18,
        dout_WIDTH => 33)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_489_p0,
        din1 => grp_fu_489_p1,
        ce => grp_fu_489_ce,
        dout => grp_fu_489_p2);

    mul_mul_16ns_18ns_33_4_1_U60 : component mapchip_png_mul_mul_16ns_18ns_33_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 18,
        dout_WIDTH => 33)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_496_p0,
        din1 => grp_fu_496_p1,
        ce => grp_fu_496_ce,
        dout => grp_fu_496_p2);

    mul_mul_16ns_18ns_33_4_1_U61 : component mapchip_png_mul_mul_16ns_18ns_33_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 18,
        dout_WIDTH => 33)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_503_p0,
        din1 => grp_fu_503_p1,
        ce => grp_fu_503_ce,
        dout => grp_fu_503_p2);

    mac_muladd_8ns_8ns_16ns_17_4_1_U62 : component mapchip_png_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_510_p0,
        din1 => grp_fu_510_p1,
        din2 => grp_fu_510_p2,
        ce => grp_fu_510_ce,
        dout => grp_fu_510_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U63 : component mapchip_png_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_519_p0,
        din1 => grp_fu_519_p1,
        din2 => grp_fu_519_p2,
        ce => grp_fu_519_ce,
        dout => grp_fu_519_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U64 : component mapchip_png_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_528_p0,
        din1 => grp_fu_528_p1,
        din2 => grp_fu_528_p2,
        ce => grp_fu_528_ce,
        dout => grp_fu_528_p3);

    mul_mul_17ns_19ns_35_4_1_U65 : component mapchip_png_mul_mul_17ns_19ns_35_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 17,
        din1_WIDTH => 19,
        dout_WIDTH => 35)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_537_p0,
        din1 => grp_fu_537_p1,
        ce => grp_fu_537_ce,
        dout => grp_fu_537_p2);

    mul_mul_17ns_19ns_35_4_1_U66 : component mapchip_png_mul_mul_17ns_19ns_35_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 17,
        din1_WIDTH => 19,
        dout_WIDTH => 35)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_544_p0,
        din1 => grp_fu_544_p1,
        ce => grp_fu_544_ce,
        dout => grp_fu_544_p2);

    mul_mul_17ns_19ns_35_4_1_U67 : component mapchip_png_mul_mul_17ns_19ns_35_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 17,
        din1_WIDTH => 19,
        dout_WIDTH => 35)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_551_p0,
        din1 => grp_fu_551_p1,
        ce => grp_fu_551_ce,
        dout => grp_fu_551_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state22) and (m_axi_dst_BVALID = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state6) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((m_axi_dst_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state6)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state6);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                elsif (((m_axi_dst_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    x_reg_183_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((m_axi_dst_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                x_reg_183 <= ap_const_lv32_0;
            elsif (((icmp_ln878_fu_247_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                x_reg_183 <= add_ln75_fu_241_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                alpha_read_reg_564 <= alpha_dout;
                dstout_read_reg_579 <= dstout_dout;
                frame_size_read_reg_574 <= frame_size_dout;
                mapchip_draw_xsize_read_reg_558 <= mapchip_draw_xsize_dout;
                y_read_reg_569 <= y_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                dst_addr_reg_599 <= sext_ln329_fu_228_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln878_reg_617_pp0_iter9_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                dst_b_V_reg_744 <= grp_fu_544_p2(32 downto 25);
                dst_g_V_reg_749 <= grp_fu_551_p2(32 downto 25);
                dst_r_V_reg_739 <= grp_fu_537_p2(32 downto 25);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln878_reg_617 <= icmp_ln878_fu_247_p2;
                icmp_ln878_reg_617_pp0_iter1_reg <= icmp_ln878_reg_617;
                    zext_ln75_reg_621_pp0_iter1_reg(31 downto 0) <= zext_ln75_reg_621(31 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln878_reg_617_pp0_iter10_reg <= icmp_ln878_reg_617_pp0_iter9_reg;
                icmp_ln878_reg_617_pp0_iter2_reg <= icmp_ln878_reg_617_pp0_iter1_reg;
                icmp_ln878_reg_617_pp0_iter3_reg <= icmp_ln878_reg_617_pp0_iter2_reg;
                icmp_ln878_reg_617_pp0_iter4_reg <= icmp_ln878_reg_617_pp0_iter3_reg;
                icmp_ln878_reg_617_pp0_iter5_reg <= icmp_ln878_reg_617_pp0_iter4_reg;
                icmp_ln878_reg_617_pp0_iter6_reg <= icmp_ln878_reg_617_pp0_iter5_reg;
                icmp_ln878_reg_617_pp0_iter7_reg <= icmp_ln878_reg_617_pp0_iter6_reg;
                icmp_ln878_reg_617_pp0_iter8_reg <= icmp_ln878_reg_617_pp0_iter7_reg;
                icmp_ln878_reg_617_pp0_iter9_reg <= icmp_ln878_reg_617_pp0_iter8_reg;
                trunc_ln_reg_636_pp0_iter2_reg <= trunc_ln_reg_636;
                trunc_ln_reg_636_pp0_iter3_reg <= trunc_ln_reg_636_pp0_iter2_reg;
                trunc_ln_reg_636_pp0_iter4_reg <= trunc_ln_reg_636_pp0_iter3_reg;
                trunc_ln_reg_636_pp0_iter5_reg <= trunc_ln_reg_636_pp0_iter4_reg;
                    zext_ln75_reg_621_pp0_iter2_reg(31 downto 0) <= zext_ln75_reg_621_pp0_iter1_reg(31 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                mul_i_i70_i_reg_594 <= grp_fu_200_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln878_reg_617 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                r_reg_647 <= src_V1_q0(15 downto 8);
                src_g_V_reg_631 <= src_g_V_fu_257_p1;
                trunc_ln1_reg_642 <= src_V1_q0(23 downto 16);
                trunc_ln_reg_636 <= src_V1_q0(31 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln878_reg_617_pp0_iter4_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_1_reg_699 <= grp_fu_496_p2(32 downto 24);
                tmp_2_reg_704 <= grp_fu_503_p2(32 downto 24);
                tmp_reg_694 <= grp_fu_489_p2(32 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                    zext_ln63_reg_605(7 downto 0) <= zext_ln63_fu_238_p1(7 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln878_fu_247_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                    zext_ln75_reg_621(31 downto 0) <= zext_ln75_fu_252_p1(31 downto 0);
            end if;
        end if;
    end process;
    zext_ln63_reg_605(15 downto 8) <= "00000000";
    zext_ln75_reg_621(63 downto 32) <= "00000000000000000000000000000000";
    zext_ln75_reg_621_pp0_iter1_reg(63 downto 32) <= "00000000000000000000000000000000";
    zext_ln75_reg_621_pp0_iter2_reg(63 downto 32) <= "00000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, mapchip_draw_xsize_empty_n, alpha_empty_n, y_empty_n, frame_size_empty_n, dstout_empty_n, m_axi_dst_AWREADY, m_axi_dst_BVALID, ap_CS_fsm_state5, ap_enable_reg_pp0_iter11, ap_CS_fsm_state22, ap_enable_reg_pp0_iter0, icmp_ln878_fu_247_p2, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter10)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((dstout_empty_n = ap_const_logic_0) or (frame_size_empty_n = ap_const_logic_0) or (y_empty_n = ap_const_logic_0) or (mapchip_draw_xsize_empty_n = ap_const_logic_0) or (ap_const_logic_0 = alpha_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((m_axi_dst_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (icmp_ln878_fu_247_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) and not(((ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (icmp_ln878_fu_247_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then
                    ap_NS_fsm <= ap_ST_fsm_state18;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state22) and (m_axi_dst_BVALID = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state22;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXX";
        end case;
    end process;
    add_ln329_fu_213_p2 <= std_logic_vector(unsigned(dstout_read_reg_579) + unsigned(shl_ln329_1_fu_206_p3));
    add_ln75_fu_241_p2 <= std_logic_vector(unsigned(x_reg_183) + unsigned(ap_const_lv32_1));

    alpha_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, alpha_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            alpha_blk_n <= alpha_empty_n;
        else 
            alpha_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    alpha_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, mapchip_draw_xsize_empty_n, alpha_empty_n, y_empty_n, frame_size_empty_n, dstout_empty_n)
    begin
        if ((not(((dstout_empty_n = ap_const_logic_0) or (frame_size_empty_n = ap_const_logic_0) or (y_empty_n = ap_const_logic_0) or (mapchip_draw_xsize_empty_n = ap_const_logic_0) or (ap_const_logic_0 = alpha_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            alpha_read <= ap_const_logic_1;
        else 
            alpha_read <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(5);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state22 <= ap_CS_fsm(10);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_state17_io)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_const_boolean_1 = ap_block_state17_io) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_state17_io)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_const_boolean_1 = ap_block_state17_io) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, mapchip_draw_xsize_empty_n, alpha_empty_n, y_empty_n, frame_size_empty_n, dstout_empty_n)
    begin
                ap_block_state1 <= ((dstout_empty_n = ap_const_logic_0) or (frame_size_empty_n = ap_const_logic_0) or (y_empty_n = ap_const_logic_0) or (mapchip_draw_xsize_empty_n = ap_const_logic_0) or (ap_const_logic_0 = alpha_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;

        ap_block_state10_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state17_io_assign_proc : process(m_axi_dst_WREADY, icmp_ln878_reg_617_pp0_iter10_reg)
    begin
                ap_block_state17_io <= ((m_axi_dst_WREADY = ap_const_logic_0) and (icmp_ln878_reg_617_pp0_iter10_reg = ap_const_lv1_0));
    end process;

        ap_block_state17_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state6_assign_proc : process(icmp_ln878_fu_247_p2)
    begin
        if ((icmp_ln878_fu_247_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state6 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state6 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, m_axi_dst_BVALID, ap_CS_fsm_state22)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state22) and (m_axi_dst_BVALID = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(m_axi_dst_BVALID, ap_CS_fsm_state22)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state22) and (m_axi_dst_BVALID = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    color_V_fu_477_p4 <= ((dst_r_V_reg_739 & dst_b_V_reg_744) & dst_g_V_reg_749);
    dst_V2_address0 <= zext_ln75_reg_621_pp0_iter2_reg(10 - 1 downto 0);

    dst_V2_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            dst_V2_ce0 <= ap_const_logic_1;
        else 
            dst_V2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    dst_blk_n_AW_assign_proc : process(m_axi_dst_AWREADY, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            dst_blk_n_AW <= m_axi_dst_AWREADY;
        else 
            dst_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    dst_blk_n_B_assign_proc : process(m_axi_dst_BVALID, ap_CS_fsm_state22)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
            dst_blk_n_B <= m_axi_dst_BVALID;
        else 
            dst_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    dst_blk_n_W_assign_proc : process(m_axi_dst_WREADY, ap_enable_reg_pp0_iter11, ap_block_pp0_stage0, icmp_ln878_reg_617_pp0_iter10_reg)
    begin
        if (((icmp_ln878_reg_617_pp0_iter10_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1))) then 
            dst_blk_n_W <= m_axi_dst_WREADY;
        else 
            dst_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    dst_g_V_2_fu_327_p1 <= dst_V2_q0(8 - 1 downto 0);

    dstout_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, dstout_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dstout_blk_n <= dstout_empty_n;
        else 
            dstout_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    dstout_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, mapchip_draw_xsize_empty_n, alpha_empty_n, y_empty_n, frame_size_empty_n, dstout_empty_n)
    begin
        if ((not(((dstout_empty_n = ap_const_logic_0) or (frame_size_empty_n = ap_const_logic_0) or (y_empty_n = ap_const_logic_0) or (mapchip_draw_xsize_empty_n = ap_const_logic_0) or (ap_const_logic_0 = alpha_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dstout_read <= ap_const_logic_1;
        else 
            dstout_read <= ap_const_logic_0;
        end if; 
    end process;


    frame_size_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, frame_size_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            frame_size_blk_n <= frame_size_empty_n;
        else 
            frame_size_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    frame_size_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, mapchip_draw_xsize_empty_n, alpha_empty_n, y_empty_n, frame_size_empty_n, dstout_empty_n)
    begin
        if ((not(((dstout_empty_n = ap_const_logic_0) or (frame_size_empty_n = ap_const_logic_0) or (y_empty_n = ap_const_logic_0) or (mapchip_draw_xsize_empty_n = ap_const_logic_0) or (ap_const_logic_0 = alpha_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            frame_size_read <= ap_const_logic_1;
        else 
            frame_size_read <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_200_p0 <= grp_fu_200_p00(32 - 1 downto 0);
    grp_fu_200_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_read_reg_569),62));
    grp_fu_200_p1 <= grp_fu_200_p10(32 - 1 downto 0);
    grp_fu_200_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(frame_size_read_reg_574),62));

    grp_fu_489_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_489_ce <= ap_const_logic_1;
        else 
            grp_fu_489_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_489_p0 <= grp_fu_489_p00(16 - 1 downto 0);
    grp_fu_489_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1364_fu_300_p2),33));
    grp_fu_489_p1 <= ap_const_lv33_10102(18 - 1 downto 0);

    grp_fu_496_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_496_ce <= ap_const_logic_1;
        else 
            grp_fu_496_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_496_p0 <= grp_fu_496_p00(16 - 1 downto 0);
    grp_fu_496_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1364_1_fu_309_p2),33));
    grp_fu_496_p1 <= ap_const_lv33_10102(18 - 1 downto 0);

    grp_fu_503_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_503_ce <= ap_const_logic_1;
        else 
            grp_fu_503_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_503_p0 <= grp_fu_503_p00(16 - 1 downto 0);
    grp_fu_503_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1364_2_fu_318_p2),33));
    grp_fu_503_p1 <= ap_const_lv33_10102(18 - 1 downto 0);

    grp_fu_510_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_510_ce <= ap_const_logic_1;
        else 
            grp_fu_510_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_510_p0 <= zext_ln1345_3_fu_368_p1(8 - 1 downto 0);
    grp_fu_510_p1 <= grp_fu_510_p10(8 - 1 downto 0);
    grp_fu_510_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(dst_g_V_2_fu_327_p1),16));
    grp_fu_510_p2 <= grp_fu_510_p20(16 - 1 downto 0);
    grp_fu_510_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_13_fu_431_p2),17));

    grp_fu_519_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_519_ce <= ap_const_logic_1;
        else 
            grp_fu_519_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_519_p0 <= grp_fu_519_p00(8 - 1 downto 0);
    grp_fu_519_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_1_fu_349_p4),16));
    grp_fu_519_p1 <= zext_ln1345_3_fu_368_p1(8 - 1 downto 0);
    grp_fu_519_p2 <= grp_fu_519_p20(16 - 1 downto 0);
    grp_fu_519_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_11_fu_418_p2),17));

    grp_fu_528_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_528_ce <= ap_const_logic_1;
        else 
            grp_fu_528_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_528_p0 <= grp_fu_528_p00(8 - 1 downto 0);
    grp_fu_528_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1345_1_fu_335_p4),16));
    grp_fu_528_p1 <= zext_ln1345_3_fu_368_p1(8 - 1 downto 0);
    grp_fu_528_p2 <= grp_fu_528_p20(16 - 1 downto 0);
    grp_fu_528_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_8_fu_405_p2),17));

    grp_fu_537_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_537_ce <= ap_const_logic_1;
        else 
            grp_fu_537_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_537_p0 <= grp_fu_537_p00(17 - 1 downto 0);
    grp_fu_537_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_528_p3),35));
    grp_fu_537_p1 <= ap_const_lv35_20203(19 - 1 downto 0);

    grp_fu_544_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_544_ce <= ap_const_logic_1;
        else 
            grp_fu_544_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_544_p0 <= grp_fu_544_p00(17 - 1 downto 0);
    grp_fu_544_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_519_p3),35));
    grp_fu_544_p1 <= ap_const_lv35_20203(19 - 1 downto 0);

    grp_fu_551_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_551_ce <= ap_const_logic_1;
        else 
            grp_fu_551_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_551_p0 <= grp_fu_551_p00(17 - 1 downto 0);
    grp_fu_551_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_510_p3),35));
    grp_fu_551_p1 <= ap_const_lv35_20203(19 - 1 downto 0);
    icmp_ln878_fu_247_p2 <= "1" when (x_reg_183 = mapchip_draw_xsize_read_reg_558) else "0";
    m_axi_dst_ARADDR <= ap_const_lv64_0;
    m_axi_dst_ARBURST <= ap_const_lv2_0;
    m_axi_dst_ARCACHE <= ap_const_lv4_0;
    m_axi_dst_ARID <= ap_const_lv1_0;
    m_axi_dst_ARLEN <= ap_const_lv32_0;
    m_axi_dst_ARLOCK <= ap_const_lv2_0;
    m_axi_dst_ARPROT <= ap_const_lv3_0;
    m_axi_dst_ARQOS <= ap_const_lv4_0;
    m_axi_dst_ARREGION <= ap_const_lv4_0;
    m_axi_dst_ARSIZE <= ap_const_lv3_0;
    m_axi_dst_ARUSER <= ap_const_lv1_0;
    m_axi_dst_ARVALID <= ap_const_logic_0;
    m_axi_dst_AWADDR <= dst_addr_reg_599;
    m_axi_dst_AWBURST <= ap_const_lv2_0;
    m_axi_dst_AWCACHE <= ap_const_lv4_0;
    m_axi_dst_AWID <= ap_const_lv1_0;
    m_axi_dst_AWLEN <= mapchip_draw_xsize_read_reg_558;
    m_axi_dst_AWLOCK <= ap_const_lv2_0;
    m_axi_dst_AWPROT <= ap_const_lv3_0;
    m_axi_dst_AWQOS <= ap_const_lv4_0;
    m_axi_dst_AWREGION <= ap_const_lv4_0;
    m_axi_dst_AWSIZE <= ap_const_lv3_0;
    m_axi_dst_AWUSER <= ap_const_lv1_0;

    m_axi_dst_AWVALID_assign_proc : process(m_axi_dst_AWREADY, ap_CS_fsm_state5)
    begin
        if (((m_axi_dst_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            m_axi_dst_AWVALID <= ap_const_logic_1;
        else 
            m_axi_dst_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_dst_BREADY_assign_proc : process(m_axi_dst_BVALID, ap_CS_fsm_state22)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state22) and (m_axi_dst_BVALID = ap_const_logic_1))) then 
            m_axi_dst_BREADY <= ap_const_logic_1;
        else 
            m_axi_dst_BREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_dst_RREADY <= ap_const_logic_0;
    m_axi_dst_WDATA <= std_logic_vector(IEEE.numeric_std.resize(unsigned(color_V_fu_477_p4),32));
    m_axi_dst_WID <= ap_const_lv1_0;
    m_axi_dst_WLAST <= ap_const_logic_0;
    m_axi_dst_WSTRB <= ap_const_lv4_F;
    m_axi_dst_WUSER <= ap_const_lv1_0;

    m_axi_dst_WVALID_assign_proc : process(ap_enable_reg_pp0_iter11, icmp_ln878_reg_617_pp0_iter10_reg, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln878_reg_617_pp0_iter10_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1))) then 
            m_axi_dst_WVALID <= ap_const_logic_1;
        else 
            m_axi_dst_WVALID <= ap_const_logic_0;
        end if; 
    end process;


    mapchip_draw_xsize_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, mapchip_draw_xsize_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            mapchip_draw_xsize_blk_n <= mapchip_draw_xsize_empty_n;
        else 
            mapchip_draw_xsize_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    mapchip_draw_xsize_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, mapchip_draw_xsize_empty_n, alpha_empty_n, y_empty_n, frame_size_empty_n, dstout_empty_n)
    begin
        if ((not(((dstout_empty_n = ap_const_logic_0) or (frame_size_empty_n = ap_const_logic_0) or (y_empty_n = ap_const_logic_0) or (mapchip_draw_xsize_empty_n = ap_const_logic_0) or (ap_const_logic_0 = alpha_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            mapchip_draw_xsize_read <= ap_const_logic_1;
        else 
            mapchip_draw_xsize_read <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln1364_1_fu_309_p0 <= mul_ln1364_1_fu_309_p00(8 - 1 downto 0);
    mul_ln1364_1_fu_309_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_reg_647),16));
    mul_ln1364_1_fu_309_p1 <= zext_ln63_reg_605(8 - 1 downto 0);
    mul_ln1364_2_fu_318_p0 <= mul_ln1364_2_fu_318_p00(8 - 1 downto 0);
    mul_ln1364_2_fu_318_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_g_V_reg_631),16));
    mul_ln1364_2_fu_318_p1 <= zext_ln63_reg_605(8 - 1 downto 0);
    mul_ln1364_fu_300_p0 <= mul_ln1364_fu_300_p00(8 - 1 downto 0);
    mul_ln1364_fu_300_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1_reg_642),16));
    mul_ln1364_fu_300_p1 <= zext_ln63_reg_605(8 - 1 downto 0);
    r_1_fu_349_p4 <= dst_V2_q0(15 downto 8);
    ret_11_fu_418_p0 <= ret_11_fu_418_p00(9 - 1 downto 0);
    ret_11_fu_418_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_reg_699),16));
    ret_11_fu_418_p1 <= zext_ln1345_1_fu_399_p1(8 - 1 downto 0);
    ret_13_fu_431_p0 <= ret_13_fu_431_p00(9 - 1 downto 0);
    ret_13_fu_431_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_reg_704),16));
    ret_13_fu_431_p1 <= zext_ln1345_1_fu_399_p1(8 - 1 downto 0);
    ret_8_fu_405_p0 <= ret_8_fu_405_p00(9 - 1 downto 0);
    ret_8_fu_405_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_reg_694),16));
    ret_8_fu_405_p1 <= zext_ln1345_1_fu_399_p1(8 - 1 downto 0);
    ret_9_fu_363_p2 <= (trunc_ln_reg_636_pp0_iter3_reg xor ap_const_lv8_FF);
        sext_ln329_fu_228_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln329_1_fu_218_p4),64));

    shl_ln329_1_fu_206_p3 <= (mul_i_i70_i_reg_594 & ap_const_lv2_0);
    src_V1_address0 <= zext_ln75_fu_252_p1(10 - 1 downto 0);

    src_V1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            src_V1_ce0 <= ap_const_logic_1;
        else 
            src_V1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    src_g_V_fu_257_p1 <= src_V1_q0(8 - 1 downto 0);
    trunc_ln1345_1_fu_335_p4 <= dst_V2_q0(23 downto 16);
    trunc_ln329_1_fu_218_p4 <= add_ln329_fu_213_p2(63 downto 2);

    y_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, y_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            y_blk_n <= y_empty_n;
        else 
            y_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    y_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, mapchip_draw_xsize_empty_n, alpha_empty_n, y_empty_n, frame_size_empty_n, dstout_empty_n)
    begin
        if ((not(((dstout_empty_n = ap_const_logic_0) or (frame_size_empty_n = ap_const_logic_0) or (y_empty_n = ap_const_logic_0) or (mapchip_draw_xsize_empty_n = ap_const_logic_0) or (ap_const_logic_0 = alpha_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            y_read <= ap_const_logic_1;
        else 
            y_read <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln1345_1_fu_399_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln_reg_636_pp0_iter5_reg),16));
    zext_ln1345_3_fu_368_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_9_fu_363_p2),16));
    zext_ln63_fu_238_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(alpha_read_reg_564),16));
    zext_ln75_fu_252_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_reg_183),64));
end behav;
