#ifndef battle_macro_h   /* prevent circular inclusions */
#define battle_macro_h   /* by using protection macros */


/*
 * ver1. 2021/07/20
 * バトル用仲間画像データのアニメーション番号を定義
 */
typedef enum
{
    BATTLE_HERO_CHIP_STAND,
    BATTLE_HERO_CHIP_RIGHT,
    BATTLE_HERO_CHIP_LEFT,
    BATTLE_HERO_CHIP_WAIT,
    BATTLE_HERO_CHIP_MAGIC_1,
    BATTLE_HERO_CHIP_MAGIC_2,
    BATTLE_HERO_CHIP_ACTION,
    BATTLE_HERO_CHIP_DAMAGE,
    BATTLE_HERO_CHIP_DYING,
    BATTLE_HERO_CHIP_DEATH_1,
    BATTLE_HERO_CHIP_DEATH_2,
    BATTLE_HERO_CHIP_GUARD,
    BATTLE_HERO_CHIP_NUMBER,
} BattleHeroChipID;


/*
 * ver1. 2021/07/20
 * バトルの現在の状況を定義
 */
typedef enum
{
    BATTLE_GAME_START,      // 開始時のアニメーション
    BATTLE_GAME_DEATH,      // 全滅
    BATTLE_GAME_VICTORY,    // 勝利
    BATTLE_GAME_PROGRESS,   // 戦闘中
    BATTLE_GAME_ESCAPE,     // 逃走
    BATTLE_GAME_RESULT,     // リザルト状態
    BATTLE_GAME_FINISH,     // 戦闘終了
} BattleFinishStateID;


/*
 * ver1. 2021/07/20
 * バトル中のサブウィンドウのコマンドの挙動を管理する表示IDを定義
 */
typedef enum
{
    BATTLE_WINDOW_SUB_MAGIC,    // わざウィンドウ
    BATTLE_WINDOW_SUB_ITEM,     // アイテムウィンドウ
    BATTLE_WINDOW_SUB_SWAP,     // キャラクター入れ替えウィンドウ
    BATTLE_WINDOW_SUB_TALK,     // 会話ウィンドウ
    BATTLE_WINDOW_SUB_CMD,      // バトル画面上のキャラクター選択コマンド
    BATTLE_WINDOW_SUB_NON,      // サブウィンドウを表示しない
} BattleSubWindowID;


/* ATBゲージの更新タイマー */
#define BATTLE_ENEMY_ATB_TIMER  (TM_500US_COUNT)
#define BATTLE_HERO_ATB_TIMER   (TM_550US_COUNT)
#define BATTLE_ATB_ENCHANT      (TM_50US_COUNT)


/* 魔法詠唱時の画像切替間隔 */
#define BATTLE_MAGIC_CHIP_TIMER (TM_200MS_COUNT)


/*
 * ver1. 2021/07/06
 * コンフィグ配列のシフト動作指定を定義
 */
#define BATTLE_CONFIG_SHIFT_ATB     (0)
#define BATTLE_CONFIG_SHIFT_EFFECT  (1)


/*
 * ver1. 2021/07/04
 * バトルの参加状況を管理を定義
 */
#define BATTLE_JOIN_CAN     (true)
#define BATTLE_JOIN_NOT     (false)

/* 仲間の生存状況 */
#define BATTLE_HERO_ALIVE   (true)
#define BATTLE_HERO_DEATH   (false)


/* アイテム使用時のリザルト値の描画を行うか判定 */
#define ITEM_RESULT_DRAW_OK    (true)
#define ITEM_RESULT_DRAW_NON   (false)


/*
 * ver1. 2021/07/04
 * バトルの行動順を定義
 * -
 * true  ATBゲージが貯まり行動可能になる
 * false 行動不可
 */
#define BATTLE_TRUN_ORDER_CAN   (true)
#define BATTLE_TRUN_ORDER_NOT   (false)


/*
 * ver1. 2021/07/06
 * エフェクトの起動チャンネルの起動状況を定義
 */
#define BATTLE_ACTION_TIMER_ON    (true)
#define BATTLE_ACTION_TIMER_OFF   (false)


/*
 * ver1. 2021/07/20
 * エフェクトのサウンドのONOFFを定義
 */
#define EFFECT_SOUND_ON             (true)
#define EFFECT_SOUND_OFF            (false)
#define TRUN_SOUND_ON               (true)
#define TRUN_SOUND_OFF              (false)


/*
 * ver1. 2021/08/03
 * バトル突入時の仲間のアニメーション開始座標
 */
#define UNIT_BATTLE_START_ANIME_XPOS    (96)
#define UNIT_BATTLE_START_ANIME_XADD    (16)    // 開始時の更新座標数


/*
 * ver1 . 2021/06/27
 * バトル用キャラクターの描画座標
 */

/* x座標の基準値、子の定数を変換させる */
#define UNIT_BATTLE_XSTART_FOR1         ((VIDEO_WIDTH - 100 - (MAPCHIP_WIDTH * 4)) << RGB_BYTE_SHIFT)
#define UNIT_BATTLE_XSTART_FOR2         ((VIDEO_WIDTH - 0  - (MAPCHIP_WIDTH * 4)) << RGB_BYTE_SHIFT)
#define UNIT_BATTLE_INIT_XPOS_INTERVAL  (8)

/* y座標の基準値 */
#define UNIT_BATTLE_INIT_YPOS_INTERVAL  (4)
#define UNIT_BATTLE_ADJUST_1            (((SIZE_UNIT_BATTLE_WIDTH * 0) - (UNIT_BATTLE_INIT_XPOS_INTERVAL * 0)) << RGB_BYTE_SHIFT)
#define UNIT_BATTLE_ADJUST_2            (((SIZE_UNIT_BATTLE_WIDTH * 1) - (UNIT_BATTLE_INIT_XPOS_INTERVAL * 1)) << RGB_BYTE_SHIFT)
#define UNIT_BATTLE_ADJUST_3            (((SIZE_UNIT_BATTLE_WIDTH * 2) - (UNIT_BATTLE_INIT_XPOS_INTERVAL * 2)) << RGB_BYTE_SHIFT)
#define UNIT_BATTLE_ADJUST_4            (((SIZE_UNIT_BATTLE_WIDTH * 3) - (UNIT_BATTLE_INIT_XPOS_INTERVAL * 3)) << RGB_BYTE_SHIFT)
#define UNIT_BATTLE_YPOS_INTERVAL       (32)
// #define UNIT_BATTLE_POS_1           (UNIT_BATTLE_XSTART_FOR1 + (MAX_V_WIDTH * ((UNIT_BATTLE_YPOS_INTERVAL * 1) + (SIZE_UNIT_BATTLE_HEIGHT * 0))))
// #define UNIT_BATTLE_POS_2           (UNIT_BATTLE_XSTART_FOR1 + (MAX_V_WIDTH * ((UNIT_BATTLE_YPOS_INTERVAL * 2) + (SIZE_UNIT_BATTLE_HEIGHT * 1))))
// #define UNIT_BATTLE_POS_3           (UNIT_BATTLE_XSTART_FOR1 + (MAX_V_WIDTH * ((UNIT_BATTLE_YPOS_INTERVAL * 3) + (SIZE_UNIT_BATTLE_HEIGHT * 2))))
// #define UNIT_BATTLE_POS_4           (UNIT_BATTLE_XSTART_FOR1 + (MAX_V_WIDTH * ((UNIT_BATTLE_YPOS_INTERVAL * 4) + (SIZE_UNIT_BATTLE_HEIGHT * 3))))

/* 仲間キャラの最終描画位置 */
#define UNIT_BATTLE_POS_1               (UNIT_BATTLE_XSTART_FOR1 + UNIT_BATTLE_ADJUST_1 + (MAX_V_WIDTH * ((UNIT_BATTLE_YPOS_INTERVAL * 3) + ((SIZE_UNIT_BATTLE_HEIGHT - (UNIT_BATTLE_INIT_YPOS_INTERVAL * 1)) * 1))))
#define UNIT_BATTLE_POS_2               (UNIT_BATTLE_XSTART_FOR1 + UNIT_BATTLE_ADJUST_2 + (MAX_V_WIDTH * ((UNIT_BATTLE_YPOS_INTERVAL * 3) + ((SIZE_UNIT_BATTLE_HEIGHT - (UNIT_BATTLE_INIT_YPOS_INTERVAL * 1)) * 2))))
#define UNIT_BATTLE_POS_3               (UNIT_BATTLE_XSTART_FOR1 + UNIT_BATTLE_ADJUST_3 + (MAX_V_WIDTH * ((UNIT_BATTLE_YPOS_INTERVAL * 3) + ((SIZE_UNIT_BATTLE_HEIGHT - (UNIT_BATTLE_INIT_YPOS_INTERVAL * 1)) * 3))))
#define UNIT_BATTLE_POS_4               (UNIT_BATTLE_XSTART_FOR1 + UNIT_BATTLE_ADJUST_4 + (MAX_V_WIDTH * ((UNIT_BATTLE_YPOS_INTERVAL * 3) + ((SIZE_UNIT_BATTLE_HEIGHT - (UNIT_BATTLE_INIT_YPOS_INTERVAL * 1)) * 4))))
#define UNIT_BATTLE_POS_5               (UNIT_BATTLE_XSTART_FOR2 + UNIT_BATTLE_ADJUST_1 + (MAX_V_WIDTH * ((UNIT_BATTLE_YPOS_INTERVAL * 3) + ((SIZE_UNIT_BATTLE_HEIGHT - (UNIT_BATTLE_INIT_YPOS_INTERVAL * 1)) * 1))))
#define UNIT_BATTLE_POS_6               (UNIT_BATTLE_XSTART_FOR2 + UNIT_BATTLE_ADJUST_2 + (MAX_V_WIDTH * ((UNIT_BATTLE_YPOS_INTERVAL * 3) + ((SIZE_UNIT_BATTLE_HEIGHT - (UNIT_BATTLE_INIT_YPOS_INTERVAL * 1)) * 2))))
#define UNIT_BATTLE_POS_7               (UNIT_BATTLE_XSTART_FOR2 + UNIT_BATTLE_ADJUST_3 + (MAX_V_WIDTH * ((UNIT_BATTLE_YPOS_INTERVAL * 3) + ((SIZE_UNIT_BATTLE_HEIGHT - (UNIT_BATTLE_INIT_YPOS_INTERVAL * 1)) * 3))))
#define UNIT_BATTLE_POS_8               (UNIT_BATTLE_XSTART_FOR2 + UNIT_BATTLE_ADJUST_4 + (MAX_V_WIDTH * ((UNIT_BATTLE_YPOS_INTERVAL * 3) + ((SIZE_UNIT_BATTLE_HEIGHT - (UNIT_BATTLE_INIT_YPOS_INTERVAL * 1)) * 4))))


/*
 * ver1. 2021/08/03
 * 行動選択中の仲間の枠の描画補正値
 */
#define BATTLE_FRAME_HERO_XPOS          (8 << RGB_BYTE_SHIFT)
#define BATTLE_FRAME_HERO_YPOS          (5 * MAX_V_WIDTH)
#define BATTLE_FRAME_HERO_ADJUST_POS    (BATTLE_FRAME_HERO_XPOS + BATTLE_FRAME_HERO_YPOS)


/*
 * ver1 . 2021/06/27
 * バトル用メニュー画面の枠線描画
 */

/* 枠の大きさ、表示位置、線の太さを変更する場合はこの定義を変更 */
#define BATTLE_STANDERD_LINE_XPOS   (5)
#define BATTLE_STANDERD_LINE_YPOS   (2)
#define BATTLE_STANDERD_LINE_BOLD   (1)

/* 白枠描画 */
#define BATTLE_MENU_LINE_Y          ((UNIT_BATTLE_YPOS_INTERVAL * 5) + (SIZE_UNIT_BATTLE_HEIGHT * 4) + BATTLE_STANDERD_LINE_YPOS)
#define BATTLE_MENU_LINE_XSTART     (BATTLE_STANDERD_LINE_XPOS)
#define BATTLE_MENU_LINE_WIDTH      (VIDEO_WIDTH - BATTLE_STANDERD_LINE_XPOS - BATTLE_MENU_LINE_XSTART)
#define BATTLE_MENU_LINE_YSTART     (BATTLE_MENU_LINE_Y)
#define BATTLE_MENU_LINE_HEIGHT     (VIDEO_HEIGHT - BATTLE_MENU_LINE_YSTART - BATTLE_STANDERD_LINE_XPOS)

/* 枠内塗りつぶし */
#define BATTLE_MENU_FILL_XSTART     (BATTLE_MENU_LINE_XSTART + BATTLE_STANDERD_LINE_BOLD)
#define BATTLE_MENU_FILL_WIDTH      (BATTLE_MENU_LINE_WIDTH  - BATTLE_STANDERD_LINE_BOLD - BATTLE_STANDERD_LINE_BOLD)
#define BATTLE_MENU_FILL_YSTART     (BATTLE_MENU_LINE_YSTART + BATTLE_STANDERD_LINE_BOLD)
#define BATTLE_MENU_FILL_HEIGHT     (BATTLE_MENU_LINE_HEIGHT - BATTLE_STANDERD_LINE_BOLD- BATTLE_STANDERD_LINE_BOLD)

/* 白区切り線 */
#define BATTLE_CMD_LINE_XSTART      (192)
#define BATTLE_CMD_LINE_WIDTH       (BATTLE_STANDERD_LINE_BOLD)
#define BATTLE_CMD_LINE_YSTART      (BATTLE_MENU_LINE_Y)
#define BATTLE_CMD_LINE_HEIGHT      (VIDEO_HEIGHT - BATTLE_CMD_LINE_YSTART - BATTLE_STANDERD_LINE_XPOS)
#define BATTLE_STAT_LINE_XSTART     (350)
#define BATTLE_STAT_LINE_WIDTH      (BATTLE_STANDERD_LINE_BOLD)
#define BATTLE_STAT_LINE_YSTART     (BATTLE_MENU_LINE_Y)
#define BATTLE_STAT_LINE_HEIGHT     (VIDEO_HEIGHT - BATTLE_STAT_LINE_YSTART - BATTLE_STANDERD_LINE_XPOS)

/* 文字列の左側に描画するアイコンと文字の間隔 */
#define ICON_INTERVAL_WIDTH         (SIZE_ICON_WIDTH + 4)
#define BATTLE_CURSOL_INTERVAL      (14)


/* バトル中のカーソルの表示位置 */
#define BATTLE_CURSOL_DEFAULT_POS       (((BATTLE_CMD_LINE_XSTART + 3) << RGB_BYTE_SHIFT) + ((BATTLE_MENU_LINE_Y + 3) * MAX_V_WIDTH))
#define BATTLE_CURSOL_INTERVAL_YPOS     (BATTLE_CURSOL_INTERVAL * MAX_V_WIDTH)


/*
 * バトル中のメニュ-文字列の表示開始位置
 * コマンドの左側にアイコンを描画するためアイコンの横幅分開けて描画
 */
#define BATTLE_CMD_DEFAULT_XPOS         (BATTLE_CMD_LINE_XSTART + ICON_INTERVAL_WIDTH)
#define BATTLE_CMD_DEFAULT_YPOS         (BATTLE_MENU_LINE_Y + 5)


/* バトル中の仲間の名前文字列表示開始位置 */
#define BATTLE_HERO_NAME_DEFAULT_XPOS   (BATTLE_STAT_LINE_XSTART + 5)
#define BATTLE_HERO_NAME_DEFAULT_YPOS   (BATTLE_CMD_DEFAULT_YPOS)


/*
 * バトル中の仲間のHPの文字列表示開始位置
 * 名前の表示位置から5文字分間隔をあけて描画
 */
#define BATTLE_HERO_ODD_HP_DEFAULT_XPOS     (BATTLE_HERO_NAME_DEFAULT_XPOS + (5 * SIZE_FONT_SJIS_WIDTH))
#define BATTLE_HERO_HP_DEFAULT_YPOS     (BATTLE_CMD_DEFAULT_YPOS)


/*
 * バトル中の仲間のHPの区切り部分開始位置
 * 最大HPが4桁のため4文字分の開始幅からスラッシュの描画を行う
 */
#define BATTLE_HERO_HP_SLASH_XPOS       (BATTLE_HERO_ODD_HP_DEFAULT_XPOS + (HP_MAX_NUMBER * SIZE_FONT_SJIS_WIDTH))


/* バトル中の最大HPの描画位置 */
#define BATTLE_HERO_HP_DEFAULT_XPOS (BATTLE_HERO_HP_SLASH_XPOS + SIZE_FONT_SJIS_WIDTH)


/* 敵の名前の描画位置 */
#define BATTLE_ENEMY_NAME_DRAW_XPOS (BATTLE_MENU_FILL_XSTART + (BATTLE_STANDERD_LINE_BOLD * 3))
#define BATTLE_ENEMY_NAME_DRAW_YPOS (BATTLE_CMD_DEFAULT_YPOS)


/*
 * ver108. 2021/08/04
 * ATB関連定数
 */
/* ATBゲージの最大値 */
#define ATB_GAUGE_MAX               (60)

/* ATBゲージの更新速度基準値、素早さの最大値 + 1の値*/
#define ATB_GAUGE_DEFAULT_NUM       (256)

/* ATBバーのサイズ */
#define ATB_LINE_SIZE               (1)
#define ATB_LINE_FILL_SIZE          (ATB_LINE_SIZE * 2)
#define ATB_LINE_WIDTH              (ATB_GAUGE_MAX - (ATB_GAUGE_MAX / 2) + (ATB_LINE_FILL_SIZE * 2))
#define ATB_LINE_HEIGHT             (12)

/* ATBバーの白い枠の塗りつぶし領域 */
#define ATB_BAR_XPOS_WHITE_FILL     (BATTLE_HERO_HP_DEFAULT_XPOS + (SIZE_FONT_SJIS_WIDTH * 4))
#define ATB_BAR_YPOS_WHITE_FILL     (BATTLE_HERO_NAME_DEFAULT_YPOS)
#define ATB_BAR_XLEN_WHITE_FILL     (ATB_LINE_WIDTH)
#define ATB_BAR_YLEN_WHITE_FILL     (ATB_LINE_HEIGHT)

/* ATBバーの白い枠の内側に描画する黒の塗りつぶし領域 */
#define ATB_BAR_XPOS_BLACK_FILL     (ATB_BAR_XPOS_WHITE_FILL + ATB_LINE_SIZE)
#define ATB_BAR_YPOS_BLACK_FILL     (ATB_BAR_YPOS_WHITE_FILL + ATB_LINE_SIZE)
#define ATB_BAR_XLEN_BLACK_FILL     (ATB_BAR_XLEN_WHITE_FILL - ATB_LINE_FILL_SIZE)
#define ATB_BAR_YLEN_BLACK_FILL     (ATB_BAR_YLEN_WHITE_FILL - ATB_LINE_FILL_SIZE)

/* ATBバーのゲージの塗りつぶし領域 */
#define ATB_BAR_XPOS_GAUGE_FILL     (ATB_BAR_XPOS_BLACK_FILL + ATB_LINE_SIZE)
#define ATB_BAR_YPOS_GAUGE_FILL     (ATB_BAR_YPOS_BLACK_FILL + ATB_LINE_SIZE)
#define ATB_BAR_XLEN_GAUGE_FILL     (ATB_BAR_XLEN_BLACK_FILL - ATB_LINE_FILL_SIZE)
#define ATB_BAR_YLEN_GAUGE_FILL     (ATB_BAR_YLEN_BLACK_FILL - ATB_LINE_FILL_SIZE)


/* アイテムのATBバー描画位置、アクションATBバーの描画サイズ + 見栄えの良い間隔の位置に描画する */
#define ATB_ITEM_DRAW_ADJUST_POS    (8)
#define ATB_ITEM_DRAW_XPOS          ((ATB_LINE_WIDTH + ATB_ITEM_DRAW_ADJUST_POS) << RGB_BYTE_SHIFT)


/*
 * ver1. 2021/97/20
 * サブウィンドウの描画位置
 */

/* 枠開始x座標、この値を変更するとサブウィンドウの描画位置が変更される */
#define BATTLE_SKILL_OVER_LINE              (SIZE_FONT_SJIS_HEIGHT * 3)
#define BATTLE_SKILL_XSTART_LINE            (130)
#define BATTLE_SKILL_YSTART_LINE            (BATTLE_CMD_LINE_YSTART - BATTLE_SKILL_OVER_LINE)

/* わざ選択白枠 */
#define BATTLE_SKILL_WINDOW_XSTART_WHITE    (BATTLE_SKILL_XSTART_LINE)
#define BATTLE_SKILL_WINDOW_WIDTH_WHITE     (BATTLE_STAT_LINE_XSTART  - BATTLE_SKILL_XSTART_LINE)
#define BATTLE_SKILL_WINDOW_YSTART_WHITE    (BATTLE_SKILL_YSTART_LINE)
#define BATTLE_SKILL_WINDOW_HEIGHT_WHITE    (BATTLE_STAT_LINE_HEIGHT + BATTLE_SKILL_OVER_LINE)

/* わざ選択青内 */
#define BATTLE_SKILL_WINDOW_XSTART_BLUE     (BATTLE_SKILL_WINDOW_XSTART_WHITE + BATTLE_STANDERD_LINE_BOLD)
#define BATTLE_SKILL_WINDOW_WIDTH_BLUE      (BATTLE_SKILL_WINDOW_WIDTH_WHITE  - BATTLE_STANDERD_LINE_BOLD - BATTLE_STANDERD_LINE_BOLD)
#define BATTLE_SKILL_WINDOW_YSTART_BLUE     (BATTLE_SKILL_WINDOW_YSTART_WHITE + BATTLE_STANDERD_LINE_BOLD)
#define BATTLE_SKILL_WINDOW_HEIGHT_BLUE     (BATTLE_SKILL_WINDOW_HEIGHT_WHITE - BATTLE_STANDERD_LINE_BOLD - BATTLE_STANDERD_LINE_BOLD)

/* スキル文字の基準位置 */
#define BATTLE_SKILL_CMD_DEFAULT_XPOS       (BATTLE_SKILL_WINDOW_XSTART_BLUE + ICON_INTERVAL_WIDTH)
#define BATTLE_SKILL_CMD_DEFAULT_YPOS       (BATTLE_SKILL_WINDOW_YSTART_BLUE + 2)

/* 消費SPの基準位置 */
#define BATTLE_SKILL_SP_DEFAULT_XPOS        (BATTLE_SKILL_CMD_DEFAULT_XPOS + BATTLE_SKILL_WINDOW_WIDTH_BLUE - (SIZE_FONT_SJIS_WIDTH * 4))

/* 残りSP描画位置 */
#define BATTLE_SKILL_ODDSP_STR_XPOS         (BATTLE_SKILL_SP_DEFAULT_XPOS - (SIZE_FONT_SJIS_WIDTH * 2))
#define BATTLE_SKILL_ODDSP_STR_YPOS         (BATTLE_SKILL_CMD_DEFAULT_YPOS + (11 * SIZE_FONT_SJIS_HEIGHT))
#define BATTLE_SKILL_ODDSP_NUM_XPOS         (BATTLE_SKILL_SP_DEFAULT_XPOS)
#define BATTLE_SKILL_ODDSP_NUM_YPOS         (BATTLE_SKILL_ODDSP_STR_YPOS)

/* スキル選択のカーソル基準位置 */
#define BATTLE_CURSOL_SKILL_DEFAULT_POS     (((BATTLE_SKILL_WINDOW_XSTART_BLUE + 1) << RGB_BYTE_SHIFT) + (BATTLE_SKILL_YSTART_LINE * MAX_V_WIDTH))



/*
 * ver1. 2021/07/28
 * アイテムウィンドウ枠サイズ定数
 */

/* アイテム選択白枠 */
#define ITEM_FRAME_SIZE_WHITE (4)
#define ITEM_FRAME_SIZE_BLUE  (ITEM_FRAME_SIZE_WHITE / 2)

#define BATTLE_ITEM_WINDOW_XSTART_WHITE (BATTLE_CMD_LINE_XSTART + 10)
#define BATTLE_ITEM_WINDOW_YSTART_WHITE (BATTLE_CMD_LINE_YSTART + (SIZE_FONT_SJIS_HEIGHT * 3) - (BATTLE_STANDERD_LINE_BOLD * ITEM_FRAME_SIZE_WHITE))
#define BATTLE_ITEM_WINDOW_HEIGHT_WHITE (SIZE_FONT_SJIS_HEIGHT + (BATTLE_STANDERD_LINE_BOLD * ITEM_FRAME_SIZE_WHITE))

/* アイテム選択青枠 */
#define BATTLE_ITEM_WINDOW_XSTART_BLUE  (BATTLE_ITEM_WINDOW_XSTART_WHITE + BATTLE_STANDERD_LINE_BOLD)
#define BATTLE_ITEM_WINDOW_YSTART_BLUE  (BATTLE_ITEM_WINDOW_YSTART_WHITE + BATTLE_STANDERD_LINE_BOLD)
#define BATTLE_ITEM_WINDOW_HEIGHT_BLUE  (SIZE_FONT_SJIS_HEIGHT + ITEM_FRAME_SIZE_BLUE)

/* アイテムコマンドの基準位置 */
#define BATTLE_ITEM_CMD_DEFAULT_XPOS    (BATTLE_ITEM_WINDOW_XSTART_BLUE + 1)
#define BATTLE_ITEM_CMD_DEFAULT_YPOS    (BATTLE_ITEM_WINDOW_YSTART_BLUE + 1)


/*
 * ver1. 2021/07/28
 * リザルトウィンドウ枠サイズ定数
 */

/* ウィンドウの描画サイズ、サイズ変更の場合子の定数を変える */
#define BATTLE_RESULT_OVER_WIDTH        (80)
#define BATTLE_RESULT_OVER_HEIGHT       (80)

/* 白枠開始位置 */
#define BATTLE_RESULT_XSTART_WHITE      ((VIDEO_WIDTH  >> 1) - (BATTLE_RESULT_OVER_WIDTH * 3))
#define BATTLE_RESULT_YSTART_WHITE      ((VIDEO_HEIGHT >> 1) - BATTLE_RESULT_OVER_HEIGHT)
#define BATTLE_RESULT_WIDTH_WHITE       (BATTLE_RESULT_OVER_WIDTH  * 2)
#define BATTLE_RESULT_HEIGHT_WHITE      (BATTLE_RESULT_OVER_HEIGHT * 2)

/* 青枠開始位置 */
#define BATTLE_RESULT_XSTART_BLUE       (BATTLE_RESULT_XSTART_WHITE + BATTLE_STANDERD_LINE_BOLD)
#define BATTLE_RESULT_YSTART_BLUE       (BATTLE_RESULT_YSTART_WHITE + BATTLE_STANDERD_LINE_BOLD)
#define BATTLE_RESULT_WIDTH_BLUE        (BATTLE_RESULT_WIDTH_WHITE  - (BATTLE_STANDERD_LINE_BOLD * 2))
#define BATTLE_RESULT_HEIGHT_BLUE       (BATTLE_RESULT_HEIGHT_WHITE - (BATTLE_STANDERD_LINE_BOLD * 2))

/* EXP文字描画開始位置 */
#define BATTLE_RESULT_EXP_XSTART        (BATTLE_RESULT_XSTART_BLUE + BATTLE_STANDERD_LINE_BOLD)
#define BATTLE_RESULT_EXP_YSTART        (BATTLE_RESULT_YSTART_BLUE + BATTLE_STANDERD_LINE_BOLD)

/* GOLD文字描画開始位置 */
#define BATTLE_RESULT_GOLD_XSTART       (BATTLE_RESULT_EXP_XSTART)
#define BATTLE_RESULT_GOLD_YSTART       (BATTLE_RESULT_EXP_YSTART + SIZE_FONT_SJIS_HEIGHT)

/* EXPとGOLDの値描画開始位置 */
#define BATTLE_RESULT_NUM_XSTART        (BATTLE_RESULT_EXP_XSTART + (SIZE_FONT_SJIS_WIDTH * 6))
#define BATTLE_RESULT_EXP_NUM_YSTART    (BATTLE_RESULT_EXP_YSTART)
#define BATTLE_RESULT_GOLD_NUM_YSTART   (BATTLE_RESULT_GOLD_YSTART)

/* レベルアップした仲間の描画開始位置 */
#define BATTLE_RESULT_LV_UP_XSTART      (BATTLE_RESULT_EXP_XSTART)
#define BATTLE_RESULT_LV_UP_YSTART      (BATTLE_RESULT_GOLD_NUM_YSTART + SIZE_FONT_SJIS_HEIGHT)

/* 新規習得技の仲間の描画開始位置 */



/*
 * ver1. 2021/08/02
 * 全滅時のウィンドウ作成座標定義
 */
/* 白枠開始位置 */
#define BATTLE_DEATH_OVER_WIDTH         (SIZE_FONT_SJIS_WIDTH * 4)
#define BATTLE_DEATH_OVER_HEIGHT        (SIZE_FONT_SJIS_HEIGHT + SIZE_FONT_SJIS_HEIGHT)
#define BATTLE_DEATH_XSTART_WHITE       ((VIDEO_WIDTH >> 1) - BATTLE_DEATH_OVER_WIDTH)
#define BATTLE_DEATH_YSTART_WHITE       (SIZE_FONT_SJIS_WIDTH)
#define BATTLE_DEATH_WIDTH_WHITE        (SIZE_FONT_SJIS_WIDTH * 8)
#define BATTLE_DEATH_HEIGHT_WHITE       (BATTLE_DEATH_OVER_HEIGHT)

/* 青枠開始位置 */
#define BATTLE_DEATH_XSTART_BLUE        (BATTLE_DEATH_XSTART_WHITE + BATTLE_STANDERD_LINE_BOLD)
#define BATTLE_DEATH_YSTART_BLUE        (BATTLE_DEATH_YSTART_WHITE + BATTLE_STANDERD_LINE_BOLD)
#define BATTLE_DEATH_WIDTH_BLUE         (BATTLE_DEATH_WIDTH_WHITE  - (BATTLE_STANDERD_LINE_BOLD * 2))
#define BATTLE_DEATH_HEIGHT_BLUE        (BATTLE_DEATH_HEIGHT_WHITE - (BATTLE_STANDERD_LINE_BOLD * 2))

/* 全滅メッセージ描画位置 */
#define BATTLE_DEATH_MSG_XSTART         (BATTLE_DEATH_XSTART_WHITE + SIZE_FONT_SJIS_WIDTH)
#define BATTLE_DEATH_MSG_YSTART         (BATTLE_DEATH_YSTART_WHITE + (SIZE_FONT_SJIS_HEIGHT >> 1))


/*
 * ver1. 2021/08/12
 * 逃走ウィンドウの作成座標定義
 */
/* 白枠開始位置 */
#define BATTLE_ESCAPE_OVER_WIDTH         (SIZE_FONT_SJIS_WIDTH * 4)
#define BATTLE_ESCAPE_OVER_HEIGHT        (SIZE_FONT_SJIS_HEIGHT + SIZE_FONT_SJIS_HEIGHT)
#define BATTLE_ESCAPE_XSTART_WHITE       ((VIDEO_WIDTH >> 1) - BATTLE_ESCAPE_OVER_WIDTH)
#define BATTLE_ESCAPE_YSTART_WHITE       (SIZE_FONT_SJIS_WIDTH)
#define BATTLE_ESCAPE_WIDTH_WHITE        (SIZE_FONT_SJIS_WIDTH * 8)
#define BATTLE_ESCAPE_HEIGHT_WHITE       (BATTLE_ESCAPE_OVER_HEIGHT)

/* 青枠開始位置 */
#define BATTLE_ESCAPE_XSTART_BLUE        (BATTLE_ESCAPE_XSTART_WHITE + BATTLE_STANDERD_LINE_BOLD)
#define BATTLE_ESCAPE_YSTART_BLUE        (BATTLE_ESCAPE_YSTART_WHITE + BATTLE_STANDERD_LINE_BOLD)
#define BATTLE_ESCAPE_WIDTH_BLUE         (BATTLE_ESCAPE_WIDTH_WHITE  - (BATTLE_STANDERD_LINE_BOLD * 2))
#define BATTLE_ESCAPE_HEIGHT_BLUE        (BATTLE_ESCAPE_HEIGHT_WHITE - (BATTLE_STANDERD_LINE_BOLD * 2))

/* 全滅メッセージ描画位置 */
#define BATTLE_ESCAPE_MSG_XSTART         (BATTLE_ESCAPE_XSTART_WHITE + (SIZE_FONT_SJIS_WIDTH >> 1))
#define BATTLE_ESCAPE_MSG_YSTART         (BATTLE_ESCAPE_YSTART_WHITE + (SIZE_FONT_SJIS_HEIGHT >> 1))





/*
 * ver1. 2021/08/11
 * 技発動時の名前表示ウィンドウのサイズ定義
 */
/* 白枠開始位置 */
#define BATTLE_EFFECT_OVER_WIDTH         (SIZE_FONT_SJIS_WIDTH * 10)
#define BATTLE_EFFECT_OVER_HEIGHT        (SIZE_FONT_SJIS_WIDTH + 12)

#define BATTLE_EFFECT_XSTART_WHITE       ((VIDEO_WIDTH >> 1) - BATTLE_EFFECT_OVER_WIDTH)
#define BATTLE_EFFECT_YSTART_WHITE       (SIZE_FONT_SJIS_WIDTH)
#define BATTLE_EFFECT_WIDTH_WHITE        (SIZE_FONT_SJIS_WIDTH * 20)
#define BATTLE_EFFECT_HEIGHT_WHITE       (BATTLE_EFFECT_OVER_HEIGHT)

/* 青枠開始位置 */
#define BATTLE_EFFECT_XSTART_BLUE        (BATTLE_EFFECT_XSTART_WHITE + BATTLE_STANDERD_LINE_BOLD)
#define BATTLE_EFFECT_YSTART_BLUE        (BATTLE_EFFECT_YSTART_WHITE + BATTLE_STANDERD_LINE_BOLD)
#define BATTLE_EFFECT_WIDTH_BLUE         (BATTLE_EFFECT_WIDTH_WHITE  - (BATTLE_STANDERD_LINE_BOLD * 2))
#define BATTLE_EFFECT_HEIGHT_BLUE        (BATTLE_EFFECT_HEIGHT_WHITE - (BATTLE_STANDERD_LINE_BOLD * 2))

/* 技名描画基本位置 */
#define BATTLE_EFFECT_MSG_XSTART         ((VIDEO_WIDTH >> 1))
#define BATTLE_EFFECT_MSG_YSTART         (BATTLE_EFFECT_YSTART_WHITE + (SIZE_FONT_SJIS_HEIGHT >> 1))


/*
 * ver1. 2021/08/12
 * 戦闘中の会話ウィンドウ描画位置
 */
/* 白枠開始位置 */
#define BATTLE_TALK_OVER_WIDTH         (10)
#define BATTLE_TALK_OVER_HEIGHT        (12 + 12)

#define BATTLE_TALK_XSTART_WHITE       (BATTLE_TALK_OVER_WIDTH)
#define BATTLE_TALK_YSTART_WHITE       (BATTLE_TALK_OVER_WIDTH)
#define BATTLE_TALK_WIDTH_WHITE        (VIDEO_WIDTH - (2 * BATTLE_TALK_XSTART_WHITE))
#define BATTLE_TALK_HEIGHT_WHITE       (BATTLE_TALK_OVER_HEIGHT)

/* 青枠開始位置 */
#define BATTLE_TALK_XSTART_BLUE        (BATTLE_TALK_XSTART_WHITE + BATTLE_STANDERD_LINE_BOLD)
#define BATTLE_TALK_YSTART_BLUE        (BATTLE_TALK_YSTART_WHITE + BATTLE_STANDERD_LINE_BOLD)
#define BATTLE_TALK_WIDTH_BLUE         (BATTLE_TALK_WIDTH_WHITE  - (BATTLE_STANDERD_LINE_BOLD * 2))
#define BATTLE_TALK_HEIGHT_BLUE        (BATTLE_TALK_HEIGHT_WHITE - (BATTLE_STANDERD_LINE_BOLD * 2))

/* メッセージ描画基本位置 */
#define BATTLE_TALK_MSG_XSTART         ((VIDEO_WIDTH >> 1))
#define BATTLE_TALK_MSG_YSTART         (BATTLE_EFFECT_YSTART_WHITE + (SIZE_FONT_SJIS_HEIGHT >> 1))


/*
 * ver1. 2021/08/12
 * 入れ替え選択時のウィンドウ描画位置
 */
/* 白枠開始位置 */
#define BATTLE_SWAP_XSTART_WHITE        (BATTLE_CMD_LINE_XSTART)
#define BATTLE_SWAP_YSTART_WHITE        (BATTLE_MENU_LINE_YSTART)
#define BATTLE_SWAP_WIDTH_WHITE         (350 - BATTLE_SWAP_XSTART_WHITE)
#define BATTLE_SWAP_HEIGHT_WHITE        (BATTLE_CMD_LINE_HEIGHT)

/* 青枠開始位置 */
#define BATTLE_SWAP_XSTART_BLUE         (BATTLE_SWAP_XSTART_WHITE + BATTLE_STANDERD_LINE_BOLD)
#define BATTLE_SWAP_YSTART_BLUE         (BATTLE_SWAP_YSTART_WHITE + BATTLE_STANDERD_LINE_BOLD)
#define BATTLE_SWAP_WIDTH_BLUE          (BATTLE_SWAP_WIDTH_WHITE  - (BATTLE_STANDERD_LINE_BOLD * 2))
#define BATTLE_SWAP_HEIGHT_BLUE         (BATTLE_SWAP_HEIGHT_WHITE - (BATTLE_STANDERD_LINE_BOLD * 2))

/* 入れ替え選択のカーソル位置 */
#define BATTLE_SWAP_DEFAULT_POS         (BATTLE_CURSOL_DEFAULT_POS)
#define BATTLE_SWAP_INTERVAL_YPOS       (BATTLE_CURSOL_INTERVAL_YPOS)

/* メッセージ描画基本位置 */
#define BATTLE_SWAP_MSG_XSTART          (BATTLE_CMD_DEFAULT_XPOS)
#define BATTLE_SWAP_MSG_YSTART          (BATTLE_CMD_DEFAULT_YPOS)




/*
 * ver1. 2021/06/27
 * バトル用キャラクター切り取りマップチップID
 */
typedef enum
{
    /* 穣子 */
    UNIT_BATTLE_MINORIKO_DEFAULT,
    UNIT_BATTLE_MINORIKO_WORK_1,
    UNIT_BATTLE_MINORIKO_WORK_2,
    UNIT_BATTLE_MINORIKO_PAUSE,
    UNIT_BATTLE_MINORIKO_MAGIC_1,
    UNIT_BATTLE_MINORIKO_MAGIC_2,
    UNIT_BATTLE_MINORIKO_MAGIC_3,
    UNIT_BATTLE_MINORIKO_DAMEGE,
    UNIT_BATTLE_MINORIKO_DYING,
    UNIT_BATTLE_MINORIKO_DYE_1,
    UNIT_BATTLE_MINORIKO_DYE_2,
    UNIT_BATTLE_MINORIKO_NULL,

    /* 静葉 */
    UNIT_BATTLE_SIZUHA_DEFAULT,
    UNIT_BATTLE_SIZUHA_WORK_1,
    UNIT_BATTLE_SIZUHA_WORK_2,
    UNIT_BATTLE_SIZUHA_PAUSE,
    UNIT_BATTLE_SIZUHA_MAGIC_1,
    UNIT_BATTLE_SIZUHA_MAGIC_2,
    UNIT_BATTLE_SIZUHA_MAGIC_3,
    UNIT_BATTLE_SIZUHA_DAMEGE,
    UNIT_BATTLE_SIZUHA_DYING,
    UNIT_BATTLE_SIZUHA_DYE_1,
    UNIT_BATTLE_SIZUHA_DYE_2,
    UNIT_BATTLE_SIZUHA_NULL,

    /* 神奈子 */
    UNIT_BATTLE_KANAKO_DEFAULT,
    UNIT_BATTLE_KANAKO_WORK_1,
    UNIT_BATTLE_KANAKO_WORK_2,
    UNIT_BATTLE_KANAKO_PAUSE,
    UNIT_BATTLE_KANAKO_MAGIC_1,
    UNIT_BATTLE_KANAKO_MAGIC_2,
    UNIT_BATTLE_KANAKO_MAGIC_3,
    UNIT_BATTLE_KANAKO_DAMEGE,
    UNIT_BATTLE_KANAKO_DYING,
    UNIT_BATTLE_KANAKO_DYE_1,
    UNIT_BATTLE_KANAKO_DYE_2,
    UNIT_BATTLE_KANAKO_NULL,

    /* 小傘 */
    UNIT_BATTLE_KOGASA_DEFAULT,
    UNIT_BATTLE_KOGASA_WORK_1,
    UNIT_BATTLE_KOGASA_WORK_2,
    UNIT_BATTLE_KOGASA_PAUSE,
    UNIT_BATTLE_KOGASA_MAGIC_1,
    UNIT_BATTLE_KOGASA_MAGIC_2,
    UNIT_BATTLE_KOGASA_MAGIC_3,
    UNIT_BATTLE_KOGASA_DAMEGE,
    UNIT_BATTLE_KOGASA_DYING,
    UNIT_BATTLE_KOGASA_DYE_1,
    UNIT_BATTLE_KOGASA_DYE_2,
    UNIT_BATTLE_KOGASA_NULL,

    /* 幽香 */
    UNIT_BATTLE_YUUKA_DEFAULT,
    UNIT_BATTLE_YUUKA_WORK_1,
    UNIT_BATTLE_YUUKA_WORK_2,
    UNIT_BATTLE_YUUKA_PAUSE,
    UNIT_BATTLE_YUUKA_MAGIC_1,
    UNIT_BATTLE_YUUKA_MAGIC_2,
    UNIT_BATTLE_YUUKA_MAGIC_3,
    UNIT_BATTLE_YUUKA_DAMEGE,
    UNIT_BATTLE_YUUKA_DYING,
    UNIT_BATTLE_YUUKA_DYE_1,
    UNIT_BATTLE_YUUKA_DYE_2,
    UNIT_BATTLE_YUUKA_NULL,

    /* レミリア */
    UNIT_BATTLE_REMIRIA_DEFAULT,
    UNIT_BATTLE_REMIRIA_WORK_1,
    UNIT_BATTLE_REMIRIA_WORK_2,
    UNIT_BATTLE_REMIRIA_PAUSE,
    UNIT_BATTLE_REMIRIA_MAGIC_1,
    UNIT_BATTLE_REMIRIA_MAGIC_2,
    UNIT_BATTLE_REMIRIA_MAGIC_3,
    UNIT_BATTLE_REMIRIA_DAMEGE,
    UNIT_BATTLE_REMIRIA_DYING,
    UNIT_BATTLE_REMIRIA_DYE_1,
    UNIT_BATTLE_REMIRIA_DYE_2,
    UNIT_BATTLE_REMIRIA_KARISUMA,

    /* さとり */
    UNIT_BATTLE_SATORI_DEFAULT,
    UNIT_BATTLE_SATORI_WORK_1,
    UNIT_BATTLE_SATORI_WORK_2,
    UNIT_BATTLE_SATORI_PAUSE,
    UNIT_BATTLE_SATORI_MAGIC_1,
    UNIT_BATTLE_SATORI_MAGIC_2,
    UNIT_BATTLE_SATORI_MAGIC_3,
    UNIT_BATTLE_SATORI_DAMEGE,
    UNIT_BATTLE_SATORI_DYING,
    UNIT_BATTLE_SATORI_DYE_1,
    UNIT_BATTLE_SATORI_DYE_2,
    UNIT_BATTLE_SATORI_NULL,

    /* 天子 */
    UNIT_BATTLE_TENKO_DEFAULT,
    UNIT_BATTLE_TENKO_WORK_1,
    UNIT_BATTLE_TENKO_WORK_2,
    UNIT_BATTLE_TENKO_PAUSE,
    UNIT_BATTLE_TENKO_MAGIC_1,
    UNIT_BATTLE_TENKO_MAGIC_2,
    UNIT_BATTLE_TENKO_MAGIC_3,
    UNIT_BATTLE_TENKO_DAMEGE,
    UNIT_BATTLE_TENKO_DYING,
    UNIT_BATTLE_TENKO_DYE_1,
    UNIT_BATTLE_TENKO_DYE_2,
    UNIT_BATTLE_TENKO_HISOUKEN,
} UnitBattleID;

#endif
