# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/app.runs/synth_1_copy_1/BraveFrontier.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1_copy_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/app.cache/wt [current_project]
set_property parent.project_path D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/app.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/app.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/src/Processor/AudioGenBlock/AudioGenBlock.v
  D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/src/common/CkeGenerator.v
  D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/src/common/DutyGenerator.v
  D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/src/Processor/GpioBlock/GpioBlock.v
  D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/src/Processor/GpioBlock/GpioCsr.v
  D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/src/Processor/GpioBlock/GpioUnit.v
  D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/src/Processor/I2CBlock/I2CBlock.v
  D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/src/Processor/I2CBlock/I2CCsr.v
  D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/src/Processor/I2CBlock/I2CUnit/I2CMaster.v
  D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/src/Processor/I2CBlock/I2CUnit/I2CMasterMux.v
  D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/src/Processor/I2CBlock/I2CUnit.v
  D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/src/Processor/MicroControllerBlock/MicroControllerBlock.v
  D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/src/Processor/MicroControllerBlock/MicroControllerCsr.v
  D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/src/PreProcessor/PreProcessor.v
  D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/src/Processor/Processor.v
  D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/src/Processor/SPIBlock/SPIBlock.v
  D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/src/Processor/SPIBlock/SPICsr.v
  D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/src/Processor/SPIBlock/SPIUnit/SPISignal.v
  D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/src/Processor/SPIBlock/SPIUnit/SPISignalMux.v
  D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/src/Processor/SPIBlock/SPIUnit.v
  D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/src/Processor/UltraSimpleInterfaceBus/UltraSimpleInterface.v
  D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/src/PreProcessor/ClockGenerateBlock/cgbWrapper.v
  D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/src/BraveFrontier.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/src/BraveFrontier.xdc
set_property used_in_implementation false [get_files D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/src/BraveFrontier.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental D:/workspace/Xilinx/workspace/CmodA7/BraveFrontierDemo/app.srcs/utils_1/imports/synth_1/BraveFrontier.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top BraveFrontier -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef BraveFrontier.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_copy_1_synth_report_utilization_0" "report_utilization -file BraveFrontier_utilization_synth.rpt -pb BraveFrontier_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1_copy_1" END { }
