// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module display_shift_dataflow_in_loop_display_shift_label0 (
        ap_clk,
        ap_rst,
        width,
        xstart,
        y_2,
        ystart,
        frame_size,
        ddr_copy,
        m_axi_copy_AWVALID,
        m_axi_copy_AWREADY,
        m_axi_copy_AWADDR,
        m_axi_copy_AWID,
        m_axi_copy_AWLEN,
        m_axi_copy_AWSIZE,
        m_axi_copy_AWBURST,
        m_axi_copy_AWLOCK,
        m_axi_copy_AWCACHE,
        m_axi_copy_AWPROT,
        m_axi_copy_AWQOS,
        m_axi_copy_AWREGION,
        m_axi_copy_AWUSER,
        m_axi_copy_WVALID,
        m_axi_copy_WREADY,
        m_axi_copy_WDATA,
        m_axi_copy_WSTRB,
        m_axi_copy_WLAST,
        m_axi_copy_WID,
        m_axi_copy_WUSER,
        m_axi_copy_ARVALID,
        m_axi_copy_ARREADY,
        m_axi_copy_ARADDR,
        m_axi_copy_ARID,
        m_axi_copy_ARLEN,
        m_axi_copy_ARSIZE,
        m_axi_copy_ARBURST,
        m_axi_copy_ARLOCK,
        m_axi_copy_ARCACHE,
        m_axi_copy_ARPROT,
        m_axi_copy_ARQOS,
        m_axi_copy_ARREGION,
        m_axi_copy_ARUSER,
        m_axi_copy_RVALID,
        m_axi_copy_RREADY,
        m_axi_copy_RDATA,
        m_axi_copy_RLAST,
        m_axi_copy_RID,
        m_axi_copy_RUSER,
        m_axi_copy_RRESP,
        m_axi_copy_BVALID,
        m_axi_copy_BREADY,
        m_axi_copy_BRESP,
        m_axi_copy_BID,
        m_axi_copy_BUSER,
        xend,
        yend,
        ddr_update,
        m_axi_update_AWVALID,
        m_axi_update_AWREADY,
        m_axi_update_AWADDR,
        m_axi_update_AWID,
        m_axi_update_AWLEN,
        m_axi_update_AWSIZE,
        m_axi_update_AWBURST,
        m_axi_update_AWLOCK,
        m_axi_update_AWCACHE,
        m_axi_update_AWPROT,
        m_axi_update_AWQOS,
        m_axi_update_AWREGION,
        m_axi_update_AWUSER,
        m_axi_update_WVALID,
        m_axi_update_WREADY,
        m_axi_update_WDATA,
        m_axi_update_WSTRB,
        m_axi_update_WLAST,
        m_axi_update_WID,
        m_axi_update_WUSER,
        m_axi_update_ARVALID,
        m_axi_update_ARREADY,
        m_axi_update_ARADDR,
        m_axi_update_ARID,
        m_axi_update_ARLEN,
        m_axi_update_ARSIZE,
        m_axi_update_ARBURST,
        m_axi_update_ARLOCK,
        m_axi_update_ARCACHE,
        m_axi_update_ARPROT,
        m_axi_update_ARQOS,
        m_axi_update_ARREGION,
        m_axi_update_ARUSER,
        m_axi_update_RVALID,
        m_axi_update_RREADY,
        m_axi_update_RDATA,
        m_axi_update_RLAST,
        m_axi_update_RID,
        m_axi_update_RUSER,
        m_axi_update_RRESP,
        m_axi_update_BVALID,
        m_axi_update_BREADY,
        m_axi_update_BRESP,
        m_axi_update_BID,
        m_axi_update_BUSER,
        width_ap_vld,
        xstart_ap_vld,
        y_2_ap_vld,
        ystart_ap_vld,
        frame_size_ap_vld,
        ddr_copy_ap_vld,
        xend_ap_vld,
        yend_ap_vld,
        ddr_update_ap_vld,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input   ap_clk;
input   ap_rst;
input  [31:0] width;
input  [31:0] xstart;
input  [31:0] y_2;
input  [31:0] ystart;
input  [31:0] frame_size;
input  [63:0] ddr_copy;
output   m_axi_copy_AWVALID;
input   m_axi_copy_AWREADY;
output  [63:0] m_axi_copy_AWADDR;
output  [0:0] m_axi_copy_AWID;
output  [31:0] m_axi_copy_AWLEN;
output  [2:0] m_axi_copy_AWSIZE;
output  [1:0] m_axi_copy_AWBURST;
output  [1:0] m_axi_copy_AWLOCK;
output  [3:0] m_axi_copy_AWCACHE;
output  [2:0] m_axi_copy_AWPROT;
output  [3:0] m_axi_copy_AWQOS;
output  [3:0] m_axi_copy_AWREGION;
output  [0:0] m_axi_copy_AWUSER;
output   m_axi_copy_WVALID;
input   m_axi_copy_WREADY;
output  [31:0] m_axi_copy_WDATA;
output  [3:0] m_axi_copy_WSTRB;
output   m_axi_copy_WLAST;
output  [0:0] m_axi_copy_WID;
output  [0:0] m_axi_copy_WUSER;
output   m_axi_copy_ARVALID;
input   m_axi_copy_ARREADY;
output  [63:0] m_axi_copy_ARADDR;
output  [0:0] m_axi_copy_ARID;
output  [31:0] m_axi_copy_ARLEN;
output  [2:0] m_axi_copy_ARSIZE;
output  [1:0] m_axi_copy_ARBURST;
output  [1:0] m_axi_copy_ARLOCK;
output  [3:0] m_axi_copy_ARCACHE;
output  [2:0] m_axi_copy_ARPROT;
output  [3:0] m_axi_copy_ARQOS;
output  [3:0] m_axi_copy_ARREGION;
output  [0:0] m_axi_copy_ARUSER;
input   m_axi_copy_RVALID;
output   m_axi_copy_RREADY;
input  [31:0] m_axi_copy_RDATA;
input   m_axi_copy_RLAST;
input  [0:0] m_axi_copy_RID;
input  [0:0] m_axi_copy_RUSER;
input  [1:0] m_axi_copy_RRESP;
input   m_axi_copy_BVALID;
output   m_axi_copy_BREADY;
input  [1:0] m_axi_copy_BRESP;
input  [0:0] m_axi_copy_BID;
input  [0:0] m_axi_copy_BUSER;
input  [31:0] xend;
input  [31:0] yend;
input  [63:0] ddr_update;
output   m_axi_update_AWVALID;
input   m_axi_update_AWREADY;
output  [63:0] m_axi_update_AWADDR;
output  [0:0] m_axi_update_AWID;
output  [31:0] m_axi_update_AWLEN;
output  [2:0] m_axi_update_AWSIZE;
output  [1:0] m_axi_update_AWBURST;
output  [1:0] m_axi_update_AWLOCK;
output  [3:0] m_axi_update_AWCACHE;
output  [2:0] m_axi_update_AWPROT;
output  [3:0] m_axi_update_AWQOS;
output  [3:0] m_axi_update_AWREGION;
output  [0:0] m_axi_update_AWUSER;
output   m_axi_update_WVALID;
input   m_axi_update_WREADY;
output  [31:0] m_axi_update_WDATA;
output  [3:0] m_axi_update_WSTRB;
output   m_axi_update_WLAST;
output  [0:0] m_axi_update_WID;
output  [0:0] m_axi_update_WUSER;
output   m_axi_update_ARVALID;
input   m_axi_update_ARREADY;
output  [63:0] m_axi_update_ARADDR;
output  [0:0] m_axi_update_ARID;
output  [31:0] m_axi_update_ARLEN;
output  [2:0] m_axi_update_ARSIZE;
output  [1:0] m_axi_update_ARBURST;
output  [1:0] m_axi_update_ARLOCK;
output  [3:0] m_axi_update_ARCACHE;
output  [2:0] m_axi_update_ARPROT;
output  [3:0] m_axi_update_ARQOS;
output  [3:0] m_axi_update_ARREGION;
output  [0:0] m_axi_update_ARUSER;
input   m_axi_update_RVALID;
output   m_axi_update_RREADY;
input  [31:0] m_axi_update_RDATA;
input   m_axi_update_RLAST;
input  [0:0] m_axi_update_RID;
input  [0:0] m_axi_update_RUSER;
input  [1:0] m_axi_update_RRESP;
input   m_axi_update_BVALID;
output   m_axi_update_BREADY;
input  [1:0] m_axi_update_BRESP;
input  [0:0] m_axi_update_BID;
input  [0:0] m_axi_update_BUSER;
input   width_ap_vld;
input   xstart_ap_vld;
input   y_2_ap_vld;
input   ystart_ap_vld;
input   frame_size_ap_vld;
input   ddr_copy_ap_vld;
input   xend_ap_vld;
input   yend_ap_vld;
input   ddr_update_ap_vld;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire   [31:0] copy_V_i_q0;
wire   [31:0] copy_V_t_q0;
wire    display_shift_label1_proc5_U0_ap_start;
wire    display_shift_label1_proc5_U0_ap_done;
wire    display_shift_label1_proc5_U0_ap_continue;
wire    display_shift_label1_proc5_U0_ap_idle;
wire    display_shift_label1_proc5_U0_ap_ready;
wire    display_shift_label1_proc5_U0_m_axi_copy_AWVALID;
wire   [63:0] display_shift_label1_proc5_U0_m_axi_copy_AWADDR;
wire   [0:0] display_shift_label1_proc5_U0_m_axi_copy_AWID;
wire   [31:0] display_shift_label1_proc5_U0_m_axi_copy_AWLEN;
wire   [2:0] display_shift_label1_proc5_U0_m_axi_copy_AWSIZE;
wire   [1:0] display_shift_label1_proc5_U0_m_axi_copy_AWBURST;
wire   [1:0] display_shift_label1_proc5_U0_m_axi_copy_AWLOCK;
wire   [3:0] display_shift_label1_proc5_U0_m_axi_copy_AWCACHE;
wire   [2:0] display_shift_label1_proc5_U0_m_axi_copy_AWPROT;
wire   [3:0] display_shift_label1_proc5_U0_m_axi_copy_AWQOS;
wire   [3:0] display_shift_label1_proc5_U0_m_axi_copy_AWREGION;
wire   [0:0] display_shift_label1_proc5_U0_m_axi_copy_AWUSER;
wire    display_shift_label1_proc5_U0_m_axi_copy_WVALID;
wire   [31:0] display_shift_label1_proc5_U0_m_axi_copy_WDATA;
wire   [3:0] display_shift_label1_proc5_U0_m_axi_copy_WSTRB;
wire    display_shift_label1_proc5_U0_m_axi_copy_WLAST;
wire   [0:0] display_shift_label1_proc5_U0_m_axi_copy_WID;
wire   [0:0] display_shift_label1_proc5_U0_m_axi_copy_WUSER;
wire    display_shift_label1_proc5_U0_m_axi_copy_ARVALID;
wire   [63:0] display_shift_label1_proc5_U0_m_axi_copy_ARADDR;
wire   [0:0] display_shift_label1_proc5_U0_m_axi_copy_ARID;
wire   [31:0] display_shift_label1_proc5_U0_m_axi_copy_ARLEN;
wire   [2:0] display_shift_label1_proc5_U0_m_axi_copy_ARSIZE;
wire   [1:0] display_shift_label1_proc5_U0_m_axi_copy_ARBURST;
wire   [1:0] display_shift_label1_proc5_U0_m_axi_copy_ARLOCK;
wire   [3:0] display_shift_label1_proc5_U0_m_axi_copy_ARCACHE;
wire   [2:0] display_shift_label1_proc5_U0_m_axi_copy_ARPROT;
wire   [3:0] display_shift_label1_proc5_U0_m_axi_copy_ARQOS;
wire   [3:0] display_shift_label1_proc5_U0_m_axi_copy_ARREGION;
wire   [0:0] display_shift_label1_proc5_U0_m_axi_copy_ARUSER;
wire    display_shift_label1_proc5_U0_m_axi_copy_RREADY;
wire    display_shift_label1_proc5_U0_m_axi_copy_BREADY;
wire   [9:0] display_shift_label1_proc5_U0_copy_V1_address0;
wire    display_shift_label1_proc5_U0_copy_V1_ce0;
wire    display_shift_label1_proc5_U0_copy_V1_we0;
wire   [31:0] display_shift_label1_proc5_U0_copy_V1_d0;
wire   [31:0] display_shift_label1_proc5_U0_width_out_din;
wire    display_shift_label1_proc5_U0_width_out_write;
wire   [31:0] display_shift_label1_proc5_U0_y_2_out_din;
wire    display_shift_label1_proc5_U0_y_2_out_write;
wire   [31:0] display_shift_label1_proc5_U0_frame_size_out_din;
wire    display_shift_label1_proc5_U0_frame_size_out_write;
wire   [31:0] display_shift_label1_proc5_U0_xend_out_din;
wire    display_shift_label1_proc5_U0_xend_out_write;
wire   [31:0] display_shift_label1_proc5_U0_yend_out_din;
wire    display_shift_label1_proc5_U0_yend_out_write;
wire   [63:0] display_shift_label1_proc5_U0_ddr_update_out_din;
wire    display_shift_label1_proc5_U0_ddr_update_out_write;
wire    ap_channel_done_copy_V;
wire    display_shift_label1_proc5_U0_copy_V1_full_n;
wire    display_shift_label2_proc_U0_ap_start;
wire    display_shift_label2_proc_U0_ap_done;
wire    display_shift_label2_proc_U0_ap_continue;
wire    display_shift_label2_proc_U0_ap_idle;
wire    display_shift_label2_proc_U0_ap_ready;
wire    display_shift_label2_proc_U0_width_read;
wire    display_shift_label2_proc_U0_xend_read;
wire    display_shift_label2_proc_U0_y_2_read;
wire    display_shift_label2_proc_U0_yend_read;
wire    display_shift_label2_proc_U0_frame_size_read;
wire   [9:0] display_shift_label2_proc_U0_copy_V1_address0;
wire    display_shift_label2_proc_U0_copy_V1_ce0;
wire    display_shift_label2_proc_U0_ddr_update_read;
wire    display_shift_label2_proc_U0_m_axi_update_AWVALID;
wire   [63:0] display_shift_label2_proc_U0_m_axi_update_AWADDR;
wire   [0:0] display_shift_label2_proc_U0_m_axi_update_AWID;
wire   [31:0] display_shift_label2_proc_U0_m_axi_update_AWLEN;
wire   [2:0] display_shift_label2_proc_U0_m_axi_update_AWSIZE;
wire   [1:0] display_shift_label2_proc_U0_m_axi_update_AWBURST;
wire   [1:0] display_shift_label2_proc_U0_m_axi_update_AWLOCK;
wire   [3:0] display_shift_label2_proc_U0_m_axi_update_AWCACHE;
wire   [2:0] display_shift_label2_proc_U0_m_axi_update_AWPROT;
wire   [3:0] display_shift_label2_proc_U0_m_axi_update_AWQOS;
wire   [3:0] display_shift_label2_proc_U0_m_axi_update_AWREGION;
wire   [0:0] display_shift_label2_proc_U0_m_axi_update_AWUSER;
wire    display_shift_label2_proc_U0_m_axi_update_WVALID;
wire   [31:0] display_shift_label2_proc_U0_m_axi_update_WDATA;
wire   [3:0] display_shift_label2_proc_U0_m_axi_update_WSTRB;
wire    display_shift_label2_proc_U0_m_axi_update_WLAST;
wire   [0:0] display_shift_label2_proc_U0_m_axi_update_WID;
wire   [0:0] display_shift_label2_proc_U0_m_axi_update_WUSER;
wire    display_shift_label2_proc_U0_m_axi_update_ARVALID;
wire   [63:0] display_shift_label2_proc_U0_m_axi_update_ARADDR;
wire   [0:0] display_shift_label2_proc_U0_m_axi_update_ARID;
wire   [31:0] display_shift_label2_proc_U0_m_axi_update_ARLEN;
wire   [2:0] display_shift_label2_proc_U0_m_axi_update_ARSIZE;
wire   [1:0] display_shift_label2_proc_U0_m_axi_update_ARBURST;
wire   [1:0] display_shift_label2_proc_U0_m_axi_update_ARLOCK;
wire   [3:0] display_shift_label2_proc_U0_m_axi_update_ARCACHE;
wire   [2:0] display_shift_label2_proc_U0_m_axi_update_ARPROT;
wire   [3:0] display_shift_label2_proc_U0_m_axi_update_ARQOS;
wire   [3:0] display_shift_label2_proc_U0_m_axi_update_ARREGION;
wire   [0:0] display_shift_label2_proc_U0_m_axi_update_ARUSER;
wire    display_shift_label2_proc_U0_m_axi_update_RREADY;
wire    display_shift_label2_proc_U0_m_axi_update_BREADY;
wire    ap_sync_continue;
wire    copy_V_i_full_n;
wire    copy_V_t_empty_n;
wire    width_c_full_n;
wire   [31:0] width_c_dout;
wire    width_c_empty_n;
wire    y_2_c_full_n;
wire   [31:0] y_2_c_dout;
wire    y_2_c_empty_n;
wire    frame_size_c_full_n;
wire   [31:0] frame_size_c_dout;
wire    frame_size_c_empty_n;
wire    xend_c_full_n;
wire   [31:0] xend_c_dout;
wire    xend_c_empty_n;
wire    yend_c_full_n;
wire   [31:0] yend_c_dout;
wire    yend_c_empty_n;
wire    ddr_update_c_full_n;
wire   [63:0] ddr_update_c_dout;
wire    ddr_update_c_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire    display_shift_label1_proc5_U0_start_full_n;
wire    display_shift_label1_proc5_U0_start_write;
wire    display_shift_label2_proc_U0_start_full_n;
wire    display_shift_label2_proc_U0_start_write;

display_shift_dataflow_in_loop_display_shift_label0_copy_V #(
    .DataWidth( 32 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
copy_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(display_shift_label1_proc5_U0_copy_V1_address0),
    .i_ce0(display_shift_label1_proc5_U0_copy_V1_ce0),
    .i_we0(display_shift_label1_proc5_U0_copy_V1_we0),
    .i_d0(display_shift_label1_proc5_U0_copy_V1_d0),
    .i_q0(copy_V_i_q0),
    .t_address0(display_shift_label2_proc_U0_copy_V1_address0),
    .t_ce0(display_shift_label2_proc_U0_copy_V1_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(copy_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(copy_V_i_full_n),
    .i_write(display_shift_label1_proc5_U0_ap_done),
    .t_empty_n(copy_V_t_empty_n),
    .t_read(display_shift_label2_proc_U0_ap_ready)
);

display_shift_display_shift_label1_proc5 display_shift_label1_proc5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(display_shift_label1_proc5_U0_ap_start),
    .ap_done(display_shift_label1_proc5_U0_ap_done),
    .ap_continue(display_shift_label1_proc5_U0_ap_continue),
    .ap_idle(display_shift_label1_proc5_U0_ap_idle),
    .ap_ready(display_shift_label1_proc5_U0_ap_ready),
    .width(width),
    .xstart(xstart),
    .y_2(y_2),
    .ystart(ystart),
    .frame_size(frame_size),
    .ddr_copy(ddr_copy),
    .m_axi_copy_AWVALID(display_shift_label1_proc5_U0_m_axi_copy_AWVALID),
    .m_axi_copy_AWREADY(1'b0),
    .m_axi_copy_AWADDR(display_shift_label1_proc5_U0_m_axi_copy_AWADDR),
    .m_axi_copy_AWID(display_shift_label1_proc5_U0_m_axi_copy_AWID),
    .m_axi_copy_AWLEN(display_shift_label1_proc5_U0_m_axi_copy_AWLEN),
    .m_axi_copy_AWSIZE(display_shift_label1_proc5_U0_m_axi_copy_AWSIZE),
    .m_axi_copy_AWBURST(display_shift_label1_proc5_U0_m_axi_copy_AWBURST),
    .m_axi_copy_AWLOCK(display_shift_label1_proc5_U0_m_axi_copy_AWLOCK),
    .m_axi_copy_AWCACHE(display_shift_label1_proc5_U0_m_axi_copy_AWCACHE),
    .m_axi_copy_AWPROT(display_shift_label1_proc5_U0_m_axi_copy_AWPROT),
    .m_axi_copy_AWQOS(display_shift_label1_proc5_U0_m_axi_copy_AWQOS),
    .m_axi_copy_AWREGION(display_shift_label1_proc5_U0_m_axi_copy_AWREGION),
    .m_axi_copy_AWUSER(display_shift_label1_proc5_U0_m_axi_copy_AWUSER),
    .m_axi_copy_WVALID(display_shift_label1_proc5_U0_m_axi_copy_WVALID),
    .m_axi_copy_WREADY(1'b0),
    .m_axi_copy_WDATA(display_shift_label1_proc5_U0_m_axi_copy_WDATA),
    .m_axi_copy_WSTRB(display_shift_label1_proc5_U0_m_axi_copy_WSTRB),
    .m_axi_copy_WLAST(display_shift_label1_proc5_U0_m_axi_copy_WLAST),
    .m_axi_copy_WID(display_shift_label1_proc5_U0_m_axi_copy_WID),
    .m_axi_copy_WUSER(display_shift_label1_proc5_U0_m_axi_copy_WUSER),
    .m_axi_copy_ARVALID(display_shift_label1_proc5_U0_m_axi_copy_ARVALID),
    .m_axi_copy_ARREADY(m_axi_copy_ARREADY),
    .m_axi_copy_ARADDR(display_shift_label1_proc5_U0_m_axi_copy_ARADDR),
    .m_axi_copy_ARID(display_shift_label1_proc5_U0_m_axi_copy_ARID),
    .m_axi_copy_ARLEN(display_shift_label1_proc5_U0_m_axi_copy_ARLEN),
    .m_axi_copy_ARSIZE(display_shift_label1_proc5_U0_m_axi_copy_ARSIZE),
    .m_axi_copy_ARBURST(display_shift_label1_proc5_U0_m_axi_copy_ARBURST),
    .m_axi_copy_ARLOCK(display_shift_label1_proc5_U0_m_axi_copy_ARLOCK),
    .m_axi_copy_ARCACHE(display_shift_label1_proc5_U0_m_axi_copy_ARCACHE),
    .m_axi_copy_ARPROT(display_shift_label1_proc5_U0_m_axi_copy_ARPROT),
    .m_axi_copy_ARQOS(display_shift_label1_proc5_U0_m_axi_copy_ARQOS),
    .m_axi_copy_ARREGION(display_shift_label1_proc5_U0_m_axi_copy_ARREGION),
    .m_axi_copy_ARUSER(display_shift_label1_proc5_U0_m_axi_copy_ARUSER),
    .m_axi_copy_RVALID(m_axi_copy_RVALID),
    .m_axi_copy_RREADY(display_shift_label1_proc5_U0_m_axi_copy_RREADY),
    .m_axi_copy_RDATA(m_axi_copy_RDATA),
    .m_axi_copy_RLAST(m_axi_copy_RLAST),
    .m_axi_copy_RID(m_axi_copy_RID),
    .m_axi_copy_RUSER(m_axi_copy_RUSER),
    .m_axi_copy_RRESP(m_axi_copy_RRESP),
    .m_axi_copy_BVALID(1'b0),
    .m_axi_copy_BREADY(display_shift_label1_proc5_U0_m_axi_copy_BREADY),
    .m_axi_copy_BRESP(2'd0),
    .m_axi_copy_BID(1'd0),
    .m_axi_copy_BUSER(1'd0),
    .copy_V1_address0(display_shift_label1_proc5_U0_copy_V1_address0),
    .copy_V1_ce0(display_shift_label1_proc5_U0_copy_V1_ce0),
    .copy_V1_we0(display_shift_label1_proc5_U0_copy_V1_we0),
    .copy_V1_d0(display_shift_label1_proc5_U0_copy_V1_d0),
    .xend(xend),
    .yend(yend),
    .ddr_update(ddr_update),
    .width_out_din(display_shift_label1_proc5_U0_width_out_din),
    .width_out_full_n(width_c_full_n),
    .width_out_write(display_shift_label1_proc5_U0_width_out_write),
    .y_2_out_din(display_shift_label1_proc5_U0_y_2_out_din),
    .y_2_out_full_n(y_2_c_full_n),
    .y_2_out_write(display_shift_label1_proc5_U0_y_2_out_write),
    .frame_size_out_din(display_shift_label1_proc5_U0_frame_size_out_din),
    .frame_size_out_full_n(frame_size_c_full_n),
    .frame_size_out_write(display_shift_label1_proc5_U0_frame_size_out_write),
    .xend_out_din(display_shift_label1_proc5_U0_xend_out_din),
    .xend_out_full_n(xend_c_full_n),
    .xend_out_write(display_shift_label1_proc5_U0_xend_out_write),
    .yend_out_din(display_shift_label1_proc5_U0_yend_out_din),
    .yend_out_full_n(yend_c_full_n),
    .yend_out_write(display_shift_label1_proc5_U0_yend_out_write),
    .ddr_update_out_din(display_shift_label1_proc5_U0_ddr_update_out_din),
    .ddr_update_out_full_n(ddr_update_c_full_n),
    .ddr_update_out_write(display_shift_label1_proc5_U0_ddr_update_out_write)
);

display_shift_display_shift_label2_proc display_shift_label2_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(display_shift_label2_proc_U0_ap_start),
    .ap_done(display_shift_label2_proc_U0_ap_done),
    .ap_continue(display_shift_label2_proc_U0_ap_continue),
    .ap_idle(display_shift_label2_proc_U0_ap_idle),
    .ap_ready(display_shift_label2_proc_U0_ap_ready),
    .width_dout(width_c_dout),
    .width_empty_n(width_c_empty_n),
    .width_read(display_shift_label2_proc_U0_width_read),
    .xend_dout(xend_c_dout),
    .xend_empty_n(xend_c_empty_n),
    .xend_read(display_shift_label2_proc_U0_xend_read),
    .y_2_dout(y_2_c_dout),
    .y_2_empty_n(y_2_c_empty_n),
    .y_2_read(display_shift_label2_proc_U0_y_2_read),
    .yend_dout(yend_c_dout),
    .yend_empty_n(yend_c_empty_n),
    .yend_read(display_shift_label2_proc_U0_yend_read),
    .frame_size_dout(frame_size_c_dout),
    .frame_size_empty_n(frame_size_c_empty_n),
    .frame_size_read(display_shift_label2_proc_U0_frame_size_read),
    .copy_V1_address0(display_shift_label2_proc_U0_copy_V1_address0),
    .copy_V1_ce0(display_shift_label2_proc_U0_copy_V1_ce0),
    .copy_V1_q0(copy_V_t_q0),
    .ddr_update_dout(ddr_update_c_dout),
    .ddr_update_empty_n(ddr_update_c_empty_n),
    .ddr_update_read(display_shift_label2_proc_U0_ddr_update_read),
    .m_axi_update_AWVALID(display_shift_label2_proc_U0_m_axi_update_AWVALID),
    .m_axi_update_AWREADY(m_axi_update_AWREADY),
    .m_axi_update_AWADDR(display_shift_label2_proc_U0_m_axi_update_AWADDR),
    .m_axi_update_AWID(display_shift_label2_proc_U0_m_axi_update_AWID),
    .m_axi_update_AWLEN(display_shift_label2_proc_U0_m_axi_update_AWLEN),
    .m_axi_update_AWSIZE(display_shift_label2_proc_U0_m_axi_update_AWSIZE),
    .m_axi_update_AWBURST(display_shift_label2_proc_U0_m_axi_update_AWBURST),
    .m_axi_update_AWLOCK(display_shift_label2_proc_U0_m_axi_update_AWLOCK),
    .m_axi_update_AWCACHE(display_shift_label2_proc_U0_m_axi_update_AWCACHE),
    .m_axi_update_AWPROT(display_shift_label2_proc_U0_m_axi_update_AWPROT),
    .m_axi_update_AWQOS(display_shift_label2_proc_U0_m_axi_update_AWQOS),
    .m_axi_update_AWREGION(display_shift_label2_proc_U0_m_axi_update_AWREGION),
    .m_axi_update_AWUSER(display_shift_label2_proc_U0_m_axi_update_AWUSER),
    .m_axi_update_WVALID(display_shift_label2_proc_U0_m_axi_update_WVALID),
    .m_axi_update_WREADY(m_axi_update_WREADY),
    .m_axi_update_WDATA(display_shift_label2_proc_U0_m_axi_update_WDATA),
    .m_axi_update_WSTRB(display_shift_label2_proc_U0_m_axi_update_WSTRB),
    .m_axi_update_WLAST(display_shift_label2_proc_U0_m_axi_update_WLAST),
    .m_axi_update_WID(display_shift_label2_proc_U0_m_axi_update_WID),
    .m_axi_update_WUSER(display_shift_label2_proc_U0_m_axi_update_WUSER),
    .m_axi_update_ARVALID(display_shift_label2_proc_U0_m_axi_update_ARVALID),
    .m_axi_update_ARREADY(1'b0),
    .m_axi_update_ARADDR(display_shift_label2_proc_U0_m_axi_update_ARADDR),
    .m_axi_update_ARID(display_shift_label2_proc_U0_m_axi_update_ARID),
    .m_axi_update_ARLEN(display_shift_label2_proc_U0_m_axi_update_ARLEN),
    .m_axi_update_ARSIZE(display_shift_label2_proc_U0_m_axi_update_ARSIZE),
    .m_axi_update_ARBURST(display_shift_label2_proc_U0_m_axi_update_ARBURST),
    .m_axi_update_ARLOCK(display_shift_label2_proc_U0_m_axi_update_ARLOCK),
    .m_axi_update_ARCACHE(display_shift_label2_proc_U0_m_axi_update_ARCACHE),
    .m_axi_update_ARPROT(display_shift_label2_proc_U0_m_axi_update_ARPROT),
    .m_axi_update_ARQOS(display_shift_label2_proc_U0_m_axi_update_ARQOS),
    .m_axi_update_ARREGION(display_shift_label2_proc_U0_m_axi_update_ARREGION),
    .m_axi_update_ARUSER(display_shift_label2_proc_U0_m_axi_update_ARUSER),
    .m_axi_update_RVALID(1'b0),
    .m_axi_update_RREADY(display_shift_label2_proc_U0_m_axi_update_RREADY),
    .m_axi_update_RDATA(32'd0),
    .m_axi_update_RLAST(1'b0),
    .m_axi_update_RID(1'd0),
    .m_axi_update_RUSER(1'd0),
    .m_axi_update_RRESP(2'd0),
    .m_axi_update_BVALID(m_axi_update_BVALID),
    .m_axi_update_BREADY(display_shift_label2_proc_U0_m_axi_update_BREADY),
    .m_axi_update_BRESP(m_axi_update_BRESP),
    .m_axi_update_BID(m_axi_update_BID),
    .m_axi_update_BUSER(m_axi_update_BUSER)
);

display_shift_fifo_w32_d2_S width_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(display_shift_label1_proc5_U0_width_out_din),
    .if_full_n(width_c_full_n),
    .if_write(display_shift_label1_proc5_U0_width_out_write),
    .if_dout(width_c_dout),
    .if_empty_n(width_c_empty_n),
    .if_read(display_shift_label2_proc_U0_width_read)
);

display_shift_fifo_w32_d2_S y_2_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(display_shift_label1_proc5_U0_y_2_out_din),
    .if_full_n(y_2_c_full_n),
    .if_write(display_shift_label1_proc5_U0_y_2_out_write),
    .if_dout(y_2_c_dout),
    .if_empty_n(y_2_c_empty_n),
    .if_read(display_shift_label2_proc_U0_y_2_read)
);

display_shift_fifo_w32_d2_S frame_size_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(display_shift_label1_proc5_U0_frame_size_out_din),
    .if_full_n(frame_size_c_full_n),
    .if_write(display_shift_label1_proc5_U0_frame_size_out_write),
    .if_dout(frame_size_c_dout),
    .if_empty_n(frame_size_c_empty_n),
    .if_read(display_shift_label2_proc_U0_frame_size_read)
);

display_shift_fifo_w32_d2_S xend_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(display_shift_label1_proc5_U0_xend_out_din),
    .if_full_n(xend_c_full_n),
    .if_write(display_shift_label1_proc5_U0_xend_out_write),
    .if_dout(xend_c_dout),
    .if_empty_n(xend_c_empty_n),
    .if_read(display_shift_label2_proc_U0_xend_read)
);

display_shift_fifo_w32_d2_S yend_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(display_shift_label1_proc5_U0_yend_out_din),
    .if_full_n(yend_c_full_n),
    .if_write(display_shift_label1_proc5_U0_yend_out_write),
    .if_dout(yend_c_dout),
    .if_empty_n(yend_c_empty_n),
    .if_read(display_shift_label2_proc_U0_yend_read)
);

display_shift_fifo_w64_d2_S ddr_update_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(display_shift_label1_proc5_U0_ddr_update_out_din),
    .if_full_n(ddr_update_c_full_n),
    .if_write(display_shift_label1_proc5_U0_ddr_update_out_write),
    .if_dout(ddr_update_c_dout),
    .if_empty_n(ddr_update_c_empty_n),
    .if_read(display_shift_label2_proc_U0_ddr_update_read)
);

assign ap_channel_done_copy_V = display_shift_label1_proc5_U0_ap_done;

assign ap_done = display_shift_label2_proc_U0_ap_done;

assign ap_idle = ((copy_V_t_empty_n ^ 1'b1) & display_shift_label2_proc_U0_ap_idle & display_shift_label1_proc5_U0_ap_idle);

assign ap_ready = display_shift_label1_proc5_U0_ap_ready;

assign ap_sync_continue = ap_continue;

assign ap_sync_done = display_shift_label2_proc_U0_ap_done;

assign ap_sync_ready = display_shift_label1_proc5_U0_ap_ready;

assign display_shift_label1_proc5_U0_ap_continue = copy_V_i_full_n;

assign display_shift_label1_proc5_U0_ap_start = ap_start;

assign display_shift_label1_proc5_U0_copy_V1_full_n = copy_V_i_full_n;

assign display_shift_label1_proc5_U0_start_full_n = 1'b1;

assign display_shift_label1_proc5_U0_start_write = 1'b0;

assign display_shift_label2_proc_U0_ap_continue = ap_continue;

assign display_shift_label2_proc_U0_ap_start = copy_V_t_empty_n;

assign display_shift_label2_proc_U0_start_full_n = 1'b1;

assign display_shift_label2_proc_U0_start_write = 1'b0;

assign m_axi_copy_ARADDR = display_shift_label1_proc5_U0_m_axi_copy_ARADDR;

assign m_axi_copy_ARBURST = display_shift_label1_proc5_U0_m_axi_copy_ARBURST;

assign m_axi_copy_ARCACHE = display_shift_label1_proc5_U0_m_axi_copy_ARCACHE;

assign m_axi_copy_ARID = display_shift_label1_proc5_U0_m_axi_copy_ARID;

assign m_axi_copy_ARLEN = display_shift_label1_proc5_U0_m_axi_copy_ARLEN;

assign m_axi_copy_ARLOCK = display_shift_label1_proc5_U0_m_axi_copy_ARLOCK;

assign m_axi_copy_ARPROT = display_shift_label1_proc5_U0_m_axi_copy_ARPROT;

assign m_axi_copy_ARQOS = display_shift_label1_proc5_U0_m_axi_copy_ARQOS;

assign m_axi_copy_ARREGION = display_shift_label1_proc5_U0_m_axi_copy_ARREGION;

assign m_axi_copy_ARSIZE = display_shift_label1_proc5_U0_m_axi_copy_ARSIZE;

assign m_axi_copy_ARUSER = display_shift_label1_proc5_U0_m_axi_copy_ARUSER;

assign m_axi_copy_ARVALID = display_shift_label1_proc5_U0_m_axi_copy_ARVALID;

assign m_axi_copy_AWADDR = 64'd0;

assign m_axi_copy_AWBURST = 2'd0;

assign m_axi_copy_AWCACHE = 4'd0;

assign m_axi_copy_AWID = 1'd0;

assign m_axi_copy_AWLEN = 32'd0;

assign m_axi_copy_AWLOCK = 2'd0;

assign m_axi_copy_AWPROT = 3'd0;

assign m_axi_copy_AWQOS = 4'd0;

assign m_axi_copy_AWREGION = 4'd0;

assign m_axi_copy_AWSIZE = 3'd0;

assign m_axi_copy_AWUSER = 1'd0;

assign m_axi_copy_AWVALID = 1'b0;

assign m_axi_copy_BREADY = 1'b0;

assign m_axi_copy_RREADY = display_shift_label1_proc5_U0_m_axi_copy_RREADY;

assign m_axi_copy_WDATA = 32'd0;

assign m_axi_copy_WID = 1'd0;

assign m_axi_copy_WLAST = 1'b0;

assign m_axi_copy_WSTRB = 4'd0;

assign m_axi_copy_WUSER = 1'd0;

assign m_axi_copy_WVALID = 1'b0;

assign m_axi_update_ARADDR = 64'd0;

assign m_axi_update_ARBURST = 2'd0;

assign m_axi_update_ARCACHE = 4'd0;

assign m_axi_update_ARID = 1'd0;

assign m_axi_update_ARLEN = 32'd0;

assign m_axi_update_ARLOCK = 2'd0;

assign m_axi_update_ARPROT = 3'd0;

assign m_axi_update_ARQOS = 4'd0;

assign m_axi_update_ARREGION = 4'd0;

assign m_axi_update_ARSIZE = 3'd0;

assign m_axi_update_ARUSER = 1'd0;

assign m_axi_update_ARVALID = 1'b0;

assign m_axi_update_AWADDR = display_shift_label2_proc_U0_m_axi_update_AWADDR;

assign m_axi_update_AWBURST = display_shift_label2_proc_U0_m_axi_update_AWBURST;

assign m_axi_update_AWCACHE = display_shift_label2_proc_U0_m_axi_update_AWCACHE;

assign m_axi_update_AWID = display_shift_label2_proc_U0_m_axi_update_AWID;

assign m_axi_update_AWLEN = display_shift_label2_proc_U0_m_axi_update_AWLEN;

assign m_axi_update_AWLOCK = display_shift_label2_proc_U0_m_axi_update_AWLOCK;

assign m_axi_update_AWPROT = display_shift_label2_proc_U0_m_axi_update_AWPROT;

assign m_axi_update_AWQOS = display_shift_label2_proc_U0_m_axi_update_AWQOS;

assign m_axi_update_AWREGION = display_shift_label2_proc_U0_m_axi_update_AWREGION;

assign m_axi_update_AWSIZE = display_shift_label2_proc_U0_m_axi_update_AWSIZE;

assign m_axi_update_AWUSER = display_shift_label2_proc_U0_m_axi_update_AWUSER;

assign m_axi_update_AWVALID = display_shift_label2_proc_U0_m_axi_update_AWVALID;

assign m_axi_update_BREADY = display_shift_label2_proc_U0_m_axi_update_BREADY;

assign m_axi_update_RREADY = 1'b0;

assign m_axi_update_WDATA = display_shift_label2_proc_U0_m_axi_update_WDATA;

assign m_axi_update_WID = display_shift_label2_proc_U0_m_axi_update_WID;

assign m_axi_update_WLAST = display_shift_label2_proc_U0_m_axi_update_WLAST;

assign m_axi_update_WSTRB = display_shift_label2_proc_U0_m_axi_update_WSTRB;

assign m_axi_update_WUSER = display_shift_label2_proc_U0_m_axi_update_WUSER;

assign m_axi_update_WVALID = display_shift_label2_proc_U0_m_axi_update_WVALID;

endmodule //display_shift_dataflow_in_loop_display_shift_label0
