// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module display_shift_display_shift_label2_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        width_dout,
        width_empty_n,
        width_read,
        xend_dout,
        xend_empty_n,
        xend_read,
        y_2_dout,
        y_2_empty_n,
        y_2_read,
        yend_dout,
        yend_empty_n,
        yend_read,
        frame_size_dout,
        frame_size_empty_n,
        frame_size_read,
        copy_V1_address0,
        copy_V1_ce0,
        copy_V1_q0,
        ddr_update_dout,
        ddr_update_empty_n,
        ddr_update_read,
        m_axi_update_AWVALID,
        m_axi_update_AWREADY,
        m_axi_update_AWADDR,
        m_axi_update_AWID,
        m_axi_update_AWLEN,
        m_axi_update_AWSIZE,
        m_axi_update_AWBURST,
        m_axi_update_AWLOCK,
        m_axi_update_AWCACHE,
        m_axi_update_AWPROT,
        m_axi_update_AWQOS,
        m_axi_update_AWREGION,
        m_axi_update_AWUSER,
        m_axi_update_WVALID,
        m_axi_update_WREADY,
        m_axi_update_WDATA,
        m_axi_update_WSTRB,
        m_axi_update_WLAST,
        m_axi_update_WID,
        m_axi_update_WUSER,
        m_axi_update_ARVALID,
        m_axi_update_ARREADY,
        m_axi_update_ARADDR,
        m_axi_update_ARID,
        m_axi_update_ARLEN,
        m_axi_update_ARSIZE,
        m_axi_update_ARBURST,
        m_axi_update_ARLOCK,
        m_axi_update_ARCACHE,
        m_axi_update_ARPROT,
        m_axi_update_ARQOS,
        m_axi_update_ARREGION,
        m_axi_update_ARUSER,
        m_axi_update_RVALID,
        m_axi_update_RREADY,
        m_axi_update_RDATA,
        m_axi_update_RLAST,
        m_axi_update_RID,
        m_axi_update_RUSER,
        m_axi_update_RRESP,
        m_axi_update_BVALID,
        m_axi_update_BREADY,
        m_axi_update_BRESP,
        m_axi_update_BID,
        m_axi_update_BUSER
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_pp0_stage0 = 11'd32;
parameter    ap_ST_fsm_state9 = 11'd64;
parameter    ap_ST_fsm_state10 = 11'd128;
parameter    ap_ST_fsm_state11 = 11'd256;
parameter    ap_ST_fsm_state12 = 11'd512;
parameter    ap_ST_fsm_state13 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] width_dout;
input   width_empty_n;
output   width_read;
input  [31:0] xend_dout;
input   xend_empty_n;
output   xend_read;
input  [31:0] y_2_dout;
input   y_2_empty_n;
output   y_2_read;
input  [31:0] yend_dout;
input   yend_empty_n;
output   yend_read;
input  [31:0] frame_size_dout;
input   frame_size_empty_n;
output   frame_size_read;
output  [9:0] copy_V1_address0;
output   copy_V1_ce0;
input  [31:0] copy_V1_q0;
input  [63:0] ddr_update_dout;
input   ddr_update_empty_n;
output   ddr_update_read;
output   m_axi_update_AWVALID;
input   m_axi_update_AWREADY;
output  [63:0] m_axi_update_AWADDR;
output  [0:0] m_axi_update_AWID;
output  [31:0] m_axi_update_AWLEN;
output  [2:0] m_axi_update_AWSIZE;
output  [1:0] m_axi_update_AWBURST;
output  [1:0] m_axi_update_AWLOCK;
output  [3:0] m_axi_update_AWCACHE;
output  [2:0] m_axi_update_AWPROT;
output  [3:0] m_axi_update_AWQOS;
output  [3:0] m_axi_update_AWREGION;
output  [0:0] m_axi_update_AWUSER;
output   m_axi_update_WVALID;
input   m_axi_update_WREADY;
output  [31:0] m_axi_update_WDATA;
output  [3:0] m_axi_update_WSTRB;
output   m_axi_update_WLAST;
output  [0:0] m_axi_update_WID;
output  [0:0] m_axi_update_WUSER;
output   m_axi_update_ARVALID;
input   m_axi_update_ARREADY;
output  [63:0] m_axi_update_ARADDR;
output  [0:0] m_axi_update_ARID;
output  [31:0] m_axi_update_ARLEN;
output  [2:0] m_axi_update_ARSIZE;
output  [1:0] m_axi_update_ARBURST;
output  [1:0] m_axi_update_ARLOCK;
output  [3:0] m_axi_update_ARCACHE;
output  [2:0] m_axi_update_ARPROT;
output  [3:0] m_axi_update_ARQOS;
output  [3:0] m_axi_update_ARREGION;
output  [0:0] m_axi_update_ARUSER;
input   m_axi_update_RVALID;
output   m_axi_update_RREADY;
input  [31:0] m_axi_update_RDATA;
input   m_axi_update_RLAST;
input  [0:0] m_axi_update_RID;
input  [0:0] m_axi_update_RUSER;
input  [1:0] m_axi_update_RRESP;
input   m_axi_update_BVALID;
output   m_axi_update_BREADY;
input  [1:0] m_axi_update_BRESP;
input  [0:0] m_axi_update_BID;
input  [0:0] m_axi_update_BUSER;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg width_read;
reg xend_read;
reg y_2_read;
reg yend_read;
reg frame_size_read;
reg copy_V1_ce0;
reg ddr_update_read;
reg m_axi_update_AWVALID;
reg m_axi_update_WVALID;
reg m_axi_update_BREADY;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    width_blk_n;
reg    xend_blk_n;
reg    y_2_blk_n;
reg    yend_blk_n;
reg    frame_size_blk_n;
reg    ddr_update_blk_n;
reg    update_blk_n_AW;
wire    ap_CS_fsm_state5;
reg    update_blk_n_W;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln878_reg_290;
reg   [0:0] icmp_ln878_reg_290_pp0_iter1_reg;
reg    update_blk_n_B;
wire    ap_CS_fsm_state13;
reg   [31:0] x_reg_144;
reg   [31:0] width_read_reg_238;
reg   [31:0] xend_read_reg_244;
reg   [31:0] frame_size_read_reg_249;
reg   [63:0] ddr_update_read_reg_254;
wire   [33:0] ret_3_i_fu_163_p2;
reg  signed [33:0] ret_3_i_reg_259;
wire    ap_CS_fsm_state2;
wire   [61:0] grp_fu_175_p2;
reg   [61:0] mul_ln534_reg_274;
wire    ap_CS_fsm_state3;
reg   [63:0] update_addr_reg_279;
wire    ap_CS_fsm_state4;
wire   [31:0] add_ln42_fu_222_p2;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state6_pp0_stage0_iter0;
wire    ap_block_state7_pp0_stage0_iter1;
wire    ap_block_state8_pp0_stage0_iter2;
reg    ap_block_state8_io;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln878_fu_228_p2;
reg   [31:0] copy_V1_load_reg_299;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state6;
reg    ap_enable_reg_pp0_iter1;
wire   [63:0] zext_ln42_fu_233_p1;
wire  signed [63:0] sext_ln329_fu_212_p1;
wire    ap_block_pp0_stage0_01001;
reg    ap_block_state1;
wire  signed [33:0] lhs_1_i_fu_155_p1;
wire   [33:0] rhs_3_i_fu_159_p1;
wire   [31:0] grp_fu_175_p1;
wire   [61:0] zext_ln534_1_fu_181_p1;
wire   [61:0] add_ln329_fu_184_p2;
wire   [63:0] shl_ln329_1_fu_189_p3;
wire   [63:0] add_ln329_1_fu_197_p2;
wire   [61:0] trunc_ln329_1_fu_202_p4;
reg   [10:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [61:0] grp_fu_175_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 11'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

display_shift_mul_34s_32ns_62_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 34 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 62 ))
mul_34s_32ns_62_2_1_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ret_3_i_reg_259),
    .din1(grp_fu_175_p1),
    .ce(1'b1),
    .dout(grp_fu_175_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state13) & (m_axi_update_BVALID == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state6) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((m_axi_update_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state6)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state6);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((m_axi_update_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((m_axi_update_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        x_reg_144 <= 32'd0;
    end else if (((icmp_ln878_fu_228_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_reg_144 <= add_ln42_fu_222_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln878_reg_290 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        copy_V1_load_reg_299 <= copy_V1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        ddr_update_read_reg_254 <= ddr_update_dout;
        frame_size_read_reg_249 <= frame_size_dout;
        ret_3_i_reg_259 <= ret_3_i_fu_163_p2;
        width_read_reg_238 <= width_dout;
        xend_read_reg_244 <= xend_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln878_reg_290 <= icmp_ln878_fu_228_p2;
        icmp_ln878_reg_290_pp0_iter1_reg <= icmp_ln878_reg_290;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mul_ln534_reg_274 <= grp_fu_175_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        update_addr_reg_279 <= sext_ln329_fu_212_p1;
    end
end

always @ (*) begin
    if ((icmp_ln878_fu_228_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state6 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) & (m_axi_update_BVALID == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) & (m_axi_update_BVALID == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        copy_V1_ce0 = 1'b1;
    end else begin
        copy_V1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ddr_update_blk_n = ddr_update_empty_n;
    end else begin
        ddr_update_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ddr_update_empty_n == 1'b0) | (frame_size_empty_n == 1'b0) | (yend_empty_n == 1'b0) | (y_2_empty_n == 1'b0) | (xend_empty_n == 1'b0) | (width_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ddr_update_read = 1'b1;
    end else begin
        ddr_update_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        frame_size_blk_n = frame_size_empty_n;
    end else begin
        frame_size_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ddr_update_empty_n == 1'b0) | (frame_size_empty_n == 1'b0) | (yend_empty_n == 1'b0) | (y_2_empty_n == 1'b0) | (xend_empty_n == 1'b0) | (width_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        frame_size_read = 1'b1;
    end else begin
        frame_size_read = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_update_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        m_axi_update_AWVALID = 1'b1;
    end else begin
        m_axi_update_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) & (m_axi_update_BVALID == 1'b1))) begin
        m_axi_update_BREADY = 1'b1;
    end else begin
        m_axi_update_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln878_reg_290_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        m_axi_update_WVALID = 1'b1;
    end else begin
        m_axi_update_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        update_blk_n_AW = m_axi_update_AWREADY;
    end else begin
        update_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        update_blk_n_B = m_axi_update_BVALID;
    end else begin
        update_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln878_reg_290_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        update_blk_n_W = m_axi_update_WREADY;
    end else begin
        update_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_blk_n = width_empty_n;
    end else begin
        width_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ddr_update_empty_n == 1'b0) | (frame_size_empty_n == 1'b0) | (yend_empty_n == 1'b0) | (y_2_empty_n == 1'b0) | (xend_empty_n == 1'b0) | (width_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_read = 1'b1;
    end else begin
        width_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        xend_blk_n = xend_empty_n;
    end else begin
        xend_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ddr_update_empty_n == 1'b0) | (frame_size_empty_n == 1'b0) | (yend_empty_n == 1'b0) | (y_2_empty_n == 1'b0) | (xend_empty_n == 1'b0) | (width_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        xend_read = 1'b1;
    end else begin
        xend_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_2_blk_n = y_2_empty_n;
    end else begin
        y_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ddr_update_empty_n == 1'b0) | (frame_size_empty_n == 1'b0) | (yend_empty_n == 1'b0) | (y_2_empty_n == 1'b0) | (xend_empty_n == 1'b0) | (width_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_2_read = 1'b1;
    end else begin
        y_2_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        yend_blk_n = yend_empty_n;
    end else begin
        yend_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ddr_update_empty_n == 1'b0) | (frame_size_empty_n == 1'b0) | (yend_empty_n == 1'b0) | (y_2_empty_n == 1'b0) | (xend_empty_n == 1'b0) | (width_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        yend_read = 1'b1;
    end else begin
        yend_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ddr_update_empty_n == 1'b0) | (frame_size_empty_n == 1'b0) | (yend_empty_n == 1'b0) | (y_2_empty_n == 1'b0) | (xend_empty_n == 1'b0) | (width_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((m_axi_update_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (icmp_ln878_fu_228_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)) & ~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter1 == 1'b0) & (icmp_ln878_fu_228_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (m_axi_update_BVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln329_1_fu_197_p2 = (ddr_update_read_reg_254 + shl_ln329_1_fu_189_p3);

assign add_ln329_fu_184_p2 = (mul_ln534_reg_274 + zext_ln534_1_fu_181_p1);

assign add_ln42_fu_222_p2 = (x_reg_144 + 32'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((1'b1 == ap_block_state8_io) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b1 == ap_block_state8_io) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_state1 = ((ddr_update_empty_n == 1'b0) | (frame_size_empty_n == 1'b0) | (yend_empty_n == 1'b0) | (y_2_empty_n == 1'b0) | (xend_empty_n == 1'b0) | (width_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign ap_block_state6_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_io = ((m_axi_update_WREADY == 1'b0) & (icmp_ln878_reg_290_pp0_iter1_reg == 1'd0));
end

assign ap_block_state8_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign copy_V1_address0 = zext_ln42_fu_233_p1;

assign grp_fu_175_p1 = grp_fu_175_p10;

assign grp_fu_175_p10 = frame_size_read_reg_249;

assign icmp_ln878_fu_228_p2 = ((x_reg_144 == width_read_reg_238) ? 1'b1 : 1'b0);

assign lhs_1_i_fu_155_p1 = $signed(y_2_dout);

assign m_axi_update_ARADDR = 64'd0;

assign m_axi_update_ARBURST = 2'd0;

assign m_axi_update_ARCACHE = 4'd0;

assign m_axi_update_ARID = 1'd0;

assign m_axi_update_ARLEN = 32'd0;

assign m_axi_update_ARLOCK = 2'd0;

assign m_axi_update_ARPROT = 3'd0;

assign m_axi_update_ARQOS = 4'd0;

assign m_axi_update_ARREGION = 4'd0;

assign m_axi_update_ARSIZE = 3'd0;

assign m_axi_update_ARUSER = 1'd0;

assign m_axi_update_ARVALID = 1'b0;

assign m_axi_update_AWADDR = update_addr_reg_279;

assign m_axi_update_AWBURST = 2'd0;

assign m_axi_update_AWCACHE = 4'd0;

assign m_axi_update_AWID = 1'd0;

assign m_axi_update_AWLEN = width_read_reg_238;

assign m_axi_update_AWLOCK = 2'd0;

assign m_axi_update_AWPROT = 3'd0;

assign m_axi_update_AWQOS = 4'd0;

assign m_axi_update_AWREGION = 4'd0;

assign m_axi_update_AWSIZE = 3'd0;

assign m_axi_update_AWUSER = 1'd0;

assign m_axi_update_RREADY = 1'b0;

assign m_axi_update_WDATA = copy_V1_load_reg_299;

assign m_axi_update_WID = 1'd0;

assign m_axi_update_WLAST = 1'b0;

assign m_axi_update_WSTRB = 4'd15;

assign m_axi_update_WUSER = 1'd0;

assign ret_3_i_fu_163_p2 = ($signed(lhs_1_i_fu_155_p1) + $signed(rhs_3_i_fu_159_p1));

assign rhs_3_i_fu_159_p1 = yend_dout;

assign sext_ln329_fu_212_p1 = $signed(trunc_ln329_1_fu_202_p4);

assign shl_ln329_1_fu_189_p3 = {{add_ln329_fu_184_p2}, {2'd0}};

assign trunc_ln329_1_fu_202_p4 = {{add_ln329_1_fu_197_p2[63:2]}};

assign zext_ln42_fu_233_p1 = x_reg_144;

assign zext_ln534_1_fu_181_p1 = xend_read_reg_244;

endmodule //display_shift_display_shift_label2_proc
