/*
 * Create 2021/08/15
 * Author koutakimura
 * OS     Ubuntu LTS 20.04
 * Editor VSCode ver1.57.1
 * Build  Vitis20.2
 * Borad  ArtyZ7-20
 * -
 * IC      XC7Z020-1CLG400C
 * ROM     256KB
 * RAM     512KB
 * L1Cache 32KB
 * -
 * メニュー画面を構成する定数を管理するヘッダーファイル
 * 
 * 定数内の計算で使われているマジックナンバーは、描画位置やサイズがちょうどいいと感じるための調整用である
 */
#ifndef menu_macro_h   /* prevent circular inclusions */
#define menu_macro_h   /* by using protection macros */

typedef enum
{
    MENU_TALK_WINDOW,
    MENU_PATY_WINDOW,
    MENU_COOK_WINDOW,
    MENU_SELECT_WINDOW,
    MENU_SELECT_END,
} MenuStateID;


/*
 * ver1. 2021/08/15
 * メニューウィンドウの選択画面のサイズ
 */

/* メニューウィンドウの線の太さ */
#define MENU_STANDERD_LINE_BOLD         (1)

/* アイコンと文字列の間隔 */
#define MENU_SELECT_INTERVAL_ICON       (4)

/* ウィンドウとオブジェクトの隙間 */
#define MENU_WINDOW_INTERVAL            (5)

/* カーソルの移動描画幅) */
#define MENU_SELECT_CURSOL_INTERVAL_YPOS (12 * MAX_V_WIDTH)

/* 白枠開始位置 */
#define MENU_SELECT_XSTART_WHITE        (32)
#define MENU_SELECT_YSTART_WHITE        (32)
#define MENU_SELECT_WIDTH_WHITE         ((SIZE_FONT_SJIS_WIDTH * 3) + MENU_WINDOW_INTERVAL + MENU_WINDOW_INTERVAL + MENU_SELECT_INTERVAL_ICON + SIZE_ICON_WIDTH)
#define MENU_SELECT_HEIGHT_WHITE        ((SIZE_FONT_SJIS_WIDTH * 3) + (MENU_STANDERD_LINE_BOLD * 6))

/* 黒枠開始位置 */
#define MENU_SELECT_XSTART_BLACK        (MENU_SELECT_XSTART_WHITE + MENU_STANDERD_LINE_BOLD)
#define MENU_SELECT_YSTART_BLACK        (MENU_SELECT_YSTART_WHITE + MENU_STANDERD_LINE_BOLD)
#define MENU_SELECT_WIDTH_BLACK         (MENU_SELECT_WIDTH_WHITE  - (MENU_STANDERD_LINE_BOLD * 2))
#define MENU_SELECT_HEIGHT_BLACK        (MENU_SELECT_HEIGHT_WHITE - (MENU_STANDERD_LINE_BOLD * 2))

/* メニューセレクト文字列描画開始位置 */
#define MENU_SELECT_MSG_XSTART          (MENU_SELECT_XSTART_BLACK + MENU_STANDERD_LINE_BOLD + SIZE_ICON_WIDTH + 1)
#define MENU_SELECT_MSG_YSTART          (MENU_SELECT_YSTART_BLACK + MENU_STANDERD_LINE_BOLD)

/* メニューセレクトのカーソル描画基本位置 */
#define MENU_SELECT_CURSOL_XSTART       (MENU_SELECT_XSTART_BLACK)
#define MENU_SELECT_CURSOL_YSTART       (MENU_SELECT_YSTART_BLACK-1)
#define MENU_SELECT_CURSOL_DEFAULT      ((MENU_SELECT_CURSOL_XSTART << RGB_BYTE_SHIFT) + (MENU_SELECT_CURSOL_YSTART * MAX_V_WIDTH))



/**
 * @brief   パーティメニューのウィンドウ描画設定一覧
 * @ingroup menu paty
 *
 * @note 
 *
 * @version 1.0 2021/08/28
 */
/* 大枠の外 */
#define MENU_PATY_MAIN_XSTART_OUTFRAME      (18)
#define MENU_PATY_MAIN_YSTART_OUTFRAME      (104)
#define MENU_PATY_MAIN_WIDTH_OUTFRAME       (604)
#define MENU_PATY_MAIN_HEIGHT_OUTFRAME      (258)

/* 大枠の内 */
#define MENU_PATY_MAIN_XSTART_INFRAME       (MENU_PATY_MAIN_XSTART_OUTFRAME + MENU_STANDERD_LINE_BOLD)
#define MENU_PATY_MAIN_YSTART_INFRAME       (MENU_PATY_MAIN_YSTART_OUTFRAME + MENU_STANDERD_LINE_BOLD)
#define MENU_PATY_MAIN_WIDTH_INFRAME        (MENU_PATY_MAIN_WIDTH_OUTFRAME  - (MENU_STANDERD_LINE_BOLD * 2))
#define MENU_PATY_MAIN_HEIGHT_INFRAME       (MENU_PATY_MAIN_HEIGHT_OUTFRAME - (MENU_STANDERD_LINE_BOLD * 2))

/* 仲間枠の開始位置 */
/* メニューの仲間マップチップの描画座標基本位置 */
#define MENU_PATY_HERO_DRAW_XPOS            (176 << RGB_BYTE_SHIFT)
#define MENU_PATY_HERO_DRAW_YPOS            ((MENU_PATY_MAIN_YSTART_OUTFRAME + 16) * MAX_V_WIDTH)
#define MENU_PATY_HERO_DRAW_POS             (MENU_PATY_HERO_DRAW_XPOS + MENU_PATY_HERO_DRAW_YPOS)

/* 装備枠の外 */
#define MENU_PATY_EQUIP_XSTART_OUTFRAME     (34)
#define MENU_PATY_EQUIP_YSTART_OUTFRAME     (MENU_PATY_MAIN_YSTART_OUTFRAME + 32 + 48)
#define MENU_PATY_EQUIP_WIDTH_OUTFRAME      (296)
#define MENU_PATY_EQUIP_HEIGHT_OUTFRAME     ((SIZE_FONT_SJIS_HEIGHT * 4) + (MENU_STANDERD_LINE_BOLD * 4))

/* 装備枠の内 */
#define MENU_PATY_EQUIP_XSTART_INFRAME      (MENU_PATY_EQUIP_XSTART_OUTFRAME + MENU_STANDERD_LINE_BOLD)
#define MENU_PATY_EQUIP_YSTART_INFRAME      (MENU_PATY_EQUIP_YSTART_OUTFRAME + MENU_STANDERD_LINE_BOLD)
#define MENU_PATY_EQUIP_WIDTH_INFRAME       (MENU_PATY_EQUIP_WIDTH_OUTFRAME  - (MENU_STANDERD_LINE_BOLD * 2))
#define MENU_PATY_EQUIP_HEIGHT_INFRAME      (MENU_PATY_EQUIP_HEIGHT_OUTFRAME - (MENU_STANDERD_LINE_BOLD * 2))

/* 説明枠の外 */
#define MENU_PATY_REVIEW_XSTART_OUTFRAME    (MENU_PATY_EQUIP_XSTART_OUTFRAME)
#define MENU_PATY_REVIEW_YSTART_OUTFRAME    (MENU_PATY_EQUIP_YSTART_OUTFRAME + MENU_PATY_EQUIP_HEIGHT_OUTFRAME + 16)
#define MENU_PATY_REVIEW_WIDTH_OUTFRAME     (MENU_PATY_EQUIP_WIDTH_OUTFRAME)
#define MENU_PATY_REVIEW_HEIGHT_OUTFRAME    (89)

/* 説明枠の内 */
#define MENU_PATY_REVIEW_XSTART_INFRAME     (MENU_PATY_REVIEW_XSTART_OUTFRAME + MENU_STANDERD_LINE_BOLD)
#define MENU_PATY_REVIEW_YSTART_INFRAME     (MENU_PATY_REVIEW_YSTART_OUTFRAME + MENU_STANDERD_LINE_BOLD)
#define MENU_PATY_REVIEW_WIDTH_INFRAME      (MENU_PATY_REVIEW_WIDTH_OUTFRAME  - (MENU_STANDERD_LINE_BOLD * 2))
#define MENU_PATY_REVIEW_HEIGHT_INFRAME     (MENU_PATY_REVIEW_HEIGHT_OUTFRAME - (MENU_STANDERD_LINE_BOLD * 2))


/* 一覧枠の外 */
#define MENU_PATY_LIST_XSTART_OUTFRAME      (MENU_PATY_EQUIP_XSTART_OUTFRAME + MENU_PATY_EQUIP_WIDTH_OUTFRAME + 16)
#define MENU_PATY_LIST_YSTART_OUTFRAME      (MENU_PATY_EQUIP_YSTART_OUTFRAME)
#define MENU_PATY_LIST_WIDTH_OUTFRAME       (260)
#define MENU_PATY_LIST_HEIGHT_OUTFRAME      (MENU_PATY_EQUIP_HEIGHT_OUTFRAME + 16 + MENU_PATY_REVIEW_HEIGHT_OUTFRAME)

/* 一覧枠の内 */
#define MENU_PATY_LIST_XSTART_INFRAME       (MENU_PATY_LIST_XSTART_OUTFRAME + MENU_STANDERD_LINE_BOLD)
#define MENU_PATY_LIST_YSTART_INFRAME       (MENU_PATY_LIST_YSTART_OUTFRAME + MENU_STANDERD_LINE_BOLD)
#define MENU_PATY_LIST_WIDTH_INFRAME        (MENU_PATY_LIST_WIDTH_OUTFRAME - (MENU_STANDERD_LINE_BOLD * 2))
#define MENU_PATY_LIST_HEIGHT_INFRAME       (MENU_PATY_LIST_HEIGHT_OUTFRAME - (MENU_STANDERD_LINE_BOLD * 2))

/* カーソルの描画位置 */
#define MENU_PATY_HERO_CURSOL_X             (MENU_PATY_HERO_DRAW_XPOS - (SIZE_ICON_WIDTH_HALF << RGB_BYTE_SHIFT))
#define MENU_PATY_HERO_CURSOL_Y             (MENU_PATY_HERO_DRAW_YPOS + ((24 - SIZE_ICON_HEIGHT_HALF) * MAX_V_WIDTH))
#define MENU_PATY_HERO_CURSOL_POS           (MENU_PATY_HERO_CURSOL_X + MENU_PATY_HERO_CURSOL_Y)

#define MENU_PATY_EQUIP_CURSOL_X            ((MENU_PATY_EQUIP_XSTART_INFRAME + 1) << RGB_BYTE_SHIFT)
#define MENU_PATY_EQUIP_CURSOL_Y            ((MENU_PATY_EQUIP_YSTART_INFRAME - 2) * MAX_V_WIDTH)
#define MENU_PATY_EQUIP_CURSOL_POS          (MENU_PATY_EQUIP_CURSOL_X + MENU_PATY_EQUIP_CURSOL_Y)

#define MENU_PATY_LIST_CURSOL_X             ((MENU_PATY_LIST_XSTART_INFRAME + 1) << RGB_BYTE_SHIFT)
#define MENU_PATY_LIST_CURSOL_Y             ((MENU_PATY_LIST_YSTART_INFRAME - 2) * MAX_V_WIDTH)
#define MENU_PATY_LIST_CURSOL_POS           (MENU_PATY_LIST_CURSOL_X + MENU_PATY_LIST_CURSOL_Y)

/* 仲間装備メニューの装備、アイテムの文字列描画位置 */
#define MENU_PATY_EQUIP_STR_X               (MENU_PATY_EQUIP_XSTART_INFRAME + SIZE_ICON_WIDTH + 1 + 1)
#define MENU_PATY_EQUIP_STR_Y               (MENU_PATY_EQUIP_YSTART_INFRAME + 1)
#define MENU_PATY_WEAPON_STR_X              (MENU_PATY_EQUIP_STR_X + (SIZE_FONT_SJIS_WIDTH * 3))
#define MENU_PATY_WEAPON_STR_Y              (MENU_PATY_EQUIP_STR_Y)
#define MENU_PATY_ARMOR_STR_X               (MENU_PATY_WEAPON_STR_X)
#define MENU_PATY_ARMOR_STR_Y               (MENU_PATY_WEAPON_STR_Y + SIZE_FONT_SJIS_HEIGHT)
#define MENU_PATY_AMULET_STR_X              (MENU_PATY_ARMOR_STR_X)
#define MENU_PATY_AMULET_STR_Y              (MENU_PATY_ARMOR_STR_Y + SIZE_FONT_SJIS_HEIGHT)
#define MENU_PATY_ITEM_STR_X                (MENU_PATY_AMULET_STR_X)
#define MENU_PATY_ITEM_STR_Y                (MENU_PATY_AMULET_STR_Y + SIZE_FONT_SJIS_HEIGHT)


/* 説明文の描画開始位置 */
#define MENU_PATY_REVIEW_STR_1_XSTART       (MENU_PATY_REVIEW_XSTART_INFRAME + MENU_STANDERD_LINE_BOLD)
#define MENU_PATY_REVIEW_STR_1_YSTART       (MENU_PATY_REVIEW_YSTART_INFRAME + MENU_STANDERD_LINE_BOLD)

/* 物攻、属性の文字の描画開始位置 */
#define MENU_PATY_REVIEW_STR_2_XSTART       (MENU_PATY_REVIEW_XSTART_INFRAME + MENU_STANDERD_LINE_BOLD)
#define MENU_PATY_REVIEW_STR_2_YSTART       (MENU_PATY_REVIEW_YSTART_INFRAME + MENU_STANDERD_LINE_BOLD + (SIZE_FONT_SJIS_HEIGHT * 5))

/* 防御、魔防の文字の描画開始位置 */
#define MENU_PATY_REVIEW_STR_3_XSTART       (MENU_PATY_REVIEW_STR_2_XSTART + (SIZE_FONT_SJIS_WIDTH * 11))
#define MENU_PATY_REVIEW_STR_3_YSTART       (MENU_PATY_REVIEW_STR_2_YSTART)

/* 物攻の数値の描画開始位置 */
#define MENU_PATY_REVIEW_STR_4_XSTART       (MENU_PATY_REVIEW_STR_2_XSTART + (SIZE_FONT_SJIS_WIDTH * 3))
#define MENU_PATY_REVIEW_STR_4_YSTART       (MENU_PATY_REVIEW_STR_2_YSTART)

/* 属性の数値の描画開始位置 */
#define MENU_PATY_REVIEW_STR_5_XSTART       (MENU_PATY_REVIEW_STR_2_XSTART + (SIZE_FONT_SJIS_WIDTH * 3))
#define MENU_PATY_REVIEW_STR_5_YSTART       (MENU_PATY_REVIEW_STR_2_YSTART + SIZE_FONT_SJIS_HEIGHT)

/* 防御の数値の描画開始位置 */
#define MENU_PATY_REVIEW_STR_6_XSTART       (MENU_PATY_REVIEW_STR_2_XSTART + (SIZE_FONT_SJIS_WIDTH * 14))
#define MENU_PATY_REVIEW_STR_6_YSTART       (MENU_PATY_REVIEW_STR_2_YSTART)

/* 魔防の数値の描画開始位置 */
#define MENU_PATY_REVIEW_STR_7_XSTART       (MENU_PATY_REVIEW_STR_2_XSTART + (SIZE_FONT_SJIS_WIDTH * 14))
#define MENU_PATY_REVIEW_STR_7_YSTART       (MENU_PATY_REVIEW_STR_2_YSTART + SIZE_FONT_SJIS_HEIGHT)


/* リストの文字列開始描画位置 */
#define MENU_PATY_LIST_STR_1_XSTART         (MENU_PATY_LIST_XSTART_INFRAME + MENU_STANDERD_LINE_BOLD)
#define MENU_PATY_LIST_STR_2_XSTART         (MENU_PATY_LIST_STR_1_XSTART + (SIZE_FONT_SJIS_WIDTH * 8))
#define MENU_PATY_LIST_STR_3_XSTART         (MENU_PATY_LIST_STR_1_XSTART + SIZE_ICON_WIDTH + 1 + 1)

#define MENU_PATY_LIST_STR_1_YSTART         (MENU_PATY_LIST_YSTART_INFRAME + MENU_STANDERD_LINE_BOLD)
#define MENU_PATY_LIST_STR_2_YSTART         (MENU_PATY_LIST_STR_1_YSTART   + SIZE_FONT_SJIS_HEIGHT)
#define MENU_PATY_LIST_STR_3_YSTART         (MENU_PATY_LIST_STR_2_YSTART   + SIZE_FONT_SJIS_HEIGHT)
#define MENU_PATY_LIST_STR_4_YSTART         (MENU_PATY_LIST_STR_3_YSTART   + SIZE_FONT_SJIS_HEIGHT)
#define MENU_PATY_LIST_STR_5_YSTART         (MENU_PATY_LIST_STR_4_YSTART   + SIZE_FONT_SJIS_HEIGHT)
#define MENU_PATY_LIST_STR_6_YSTART         (MENU_PATY_LIST_STR_5_YSTART   + SIZE_FONT_SJIS_HEIGHT)
#define MENU_PATY_LIST_STR_7_YSTART         (MENU_PATY_LIST_STR_6_YSTART   + SIZE_FONT_SJIS_HEIGHT)
#define MENU_PATY_LIST_STR_8_YSTART         (MENU_PATY_LIST_STR_7_YSTART   + SIZE_FONT_SJIS_HEIGHT)
#define MENU_PATY_LIST_STR_9_YSTART         (MENU_PATY_LIST_STR_8_YSTART   + SIZE_FONT_SJIS_HEIGHT)
#define MENU_PATY_LIST_STR_10_YSTART        (MENU_PATY_LIST_STR_9_YSTART   + SIZE_FONT_SJIS_HEIGHT)
#define MENU_PATY_LIST_STR_11_YSTART        (MENU_PATY_LIST_STR_10_YSTART  + SIZE_FONT_SJIS_HEIGHT)
#define MENU_PATY_LIST_STR_12_YSTART        (MENU_PATY_LIST_STR_11_YSTART  + SIZE_FONT_SJIS_HEIGHT)


/*
 * ver1. 2021/08/16
 * 料理メニューのウィンドウ描画サイズ
 */

/* 料理名の最大描画個数 */
#define MENU_COOK_MAX_NUMBER               (12)

/* 大枠の白枠開始位置 */
#define MENU_COOK_MAIN_XSTART_WHITE        (108)
#define MENU_COOK_MAIN_YSTART_WHITE        (108)
#define MENU_COOK_MAIN_WIDTH_WHITE         (392 + 32)
#define MENU_COOK_MAIN_HEIGHT_WHITE        (252)

/* 大枠の黒枠開始位置 */
#define MENU_COOK_MAIN_XSTART_BLACK        (MENU_COOK_MAIN_XSTART_WHITE + MENU_STANDERD_LINE_BOLD)
#define MENU_COOK_MAIN_YSTART_BLACK        (MENU_COOK_MAIN_YSTART_WHITE + MENU_STANDERD_LINE_BOLD)
#define MENU_COOK_MAIN_WIDTH_BLACK         (MENU_COOK_MAIN_WIDTH_WHITE  - (MENU_STANDERD_LINE_BOLD * 2))
#define MENU_COOK_MAIN_HEIGHT_BLACK        (MENU_COOK_MAIN_HEIGHT_WHITE - (MENU_STANDERD_LINE_BOLD * 2))


/* 料理画面の構成 */
/* 白枠開始位置 */
#define MENU_COOK_NAME_XSTART_WHITE        (140)
#define MENU_COOK_NAME_YSTART_WHITE        (MENU_COOK_MAIN_YSTART_WHITE + 16 + 48 + 16)
#define MENU_COOK_NAME_WIDTH_WHITE         (160)
#define MENU_COOK_NAME_HEIGHT_WHITE        (152)

/* 青枠開始位置 */
#define MENU_COOK_NAME_XSTART_BLACK        (MENU_COOK_NAME_XSTART_WHITE + MENU_STANDERD_LINE_BOLD)
#define MENU_COOK_NAME_YSTART_BLACK        (MENU_COOK_NAME_YSTART_WHITE + MENU_STANDERD_LINE_BOLD)
#define MENU_COOK_NAME_WIDTH_BLACK         (MENU_COOK_NAME_WIDTH_WHITE  - (MENU_STANDERD_LINE_BOLD * 2))
#define MENU_COOK_NAME_HEIGHT_BLACK        (MENU_COOK_NAME_HEIGHT_WHITE - (MENU_STANDERD_LINE_BOLD * 2))


/* 説明文画面の構成 */
/* 白枠開始位置 */
#define MENU_COOK_CONF_XSTART_WHITE        (MENU_COOK_NAME_XSTART_WHITE + MENU_COOK_NAME_WIDTH_WHITE + 32)
#define MENU_COOK_CONF_YSTART_WHITE        (MENU_COOK_NAME_YSTART_WHITE)
#define MENU_COOK_CONF_WIDTH_WHITE         (168)
#define MENU_COOK_CONF_HEIGHT_WHITE        (MENU_COOK_NAME_HEIGHT_WHITE)

/* 青枠開始位置 */
#define MENU_COOK_CONF_XSTART_BLACK        (MENU_COOK_CONF_XSTART_WHITE + MENU_STANDERD_LINE_BOLD)
#define MENU_COOK_CONF_YSTART_BLACK        (MENU_COOK_CONF_YSTART_WHITE + MENU_STANDERD_LINE_BOLD)
#define MENU_COOK_CONF_WIDTH_BLACK         (MENU_COOK_CONF_WIDTH_WHITE  - (MENU_STANDERD_LINE_BOLD * 2))
#define MENU_COOK_CONF_HEIGHT_BLACK        (MENU_COOK_CONF_HEIGHT_WHITE - (MENU_STANDERD_LINE_BOLD * 2))

/* メニューの仲間マップチップの描画座標基本位置 */
#define MENU_HERO_DRAW_XPOS             (176 << RGB_BYTE_SHIFT)
#define MENU_HERO_DRAW_YPOS             ((MENU_COOK_MAIN_YSTART_WHITE + 16) * MAX_V_WIDTH)
#define MENU_HERO_DRAW_POS              (MENU_HERO_DRAW_XPOS + MENU_HERO_DRAW_YPOS)

/* 料理画面のカーソルの描画位置 */
#define MENU_COOK_CURSOL_XSTART         (MENU_COOK_NAME_XSTART_BLACK)
#define MENU_COOK_CURSOL_YSTART         (MENU_COOK_NAME_YSTART_BLACK - 2)
#define MENU_COOK_CURSOL_DEFAULT        ((MENU_COOK_CURSOL_XSTART << RGB_BYTE_SHIFT) + (MENU_COOK_CURSOL_YSTART * MAX_V_WIDTH))

/* 料理名の描画位置 */
#define MENU_COOK_NAME_MSG_XSTART         (MENU_COOK_NAME_XSTART_BLACK + MENU_STANDERD_LINE_BOLD + SIZE_ICON_WIDTH + 1)
#define MENU_COOK_NAME_MSG_YSTART         (MENU_COOK_NAME_YSTART_BLACK + MENU_STANDERD_LINE_BOLD)

/* 料理説明文の描画位置 */
#define MENU_COOK_CONF_MSG_XSTART         (MENU_COOK_CONF_XSTART_BLACK + MENU_STANDERD_LINE_BOLD)
#define MENU_COOK_CONF_MSG_YSTART         (MENU_COOK_NAME_MSG_YSTART)

/* 熟練度の描画位置 */
#define MENU_COOK_MASTER_MSG_XSTART       (MENU_COOK_CONF_XSTART_WHITE + MENU_STANDERD_LINE_BOLD)
#define MENU_COOK_MASTER_MSG_YSTART       (MENU_COOK_NAME_MSG_YSTART + (10 * SIZE_FONT_SJIS_HEIGHT))
#define MENU_COOK_MASTER_NUM_XSTART       (MENU_COOK_CONF_XSTART_WHITE + MENU_STANDERD_LINE_BOLD)
#define MENU_COOK_MASTER_NUM_YSTART       (MENU_COOK_NAME_MSG_YSTART + (11 * SIZE_FONT_SJIS_HEIGHT) + 2)


/* 料理の成功、失敗画面のサイズ */

/* 枠の基本サイズ */
#define MENU_COOK_SUCCESS_WIDTH                 (60)
#define MENU_COOK_SUCCESS_HEIGHT                (32)

/* 外枠開始位置 */
#define MENU_COOK_SUCCESS_X_OUTSIDE       ((VIDEO_WIDTH >> 1)  - MENU_COOK_SUCCESS_WIDTH)
#define MENU_COOK_SUCCESS_Y_OUTSIDE       ((VIDEO_HEIGHT >> 1) - MENU_COOK_SUCCESS_HEIGHT)
#define MENU_COOK_SUCCESS_WIDTH_OUTSIDE   (MENU_COOK_SUCCESS_WIDTH * 2)
#define MENU_COOK_SUCCESS_HEIGHT_OUTSIDE  (MENU_COOK_SUCCESS_HEIGHT * 2)

/* 内枠開始位置 */
#define MENU_COOK_SUCCESS_X_INSIDE        (MENU_COOK_SUCCESS_X_OUTSIDE      + MENU_STANDERD_LINE_BOLD)
#define MENU_COOK_SUCCESS_Y_INSIDE        (MENU_COOK_SUCCESS_Y_OUTSIDE      + MENU_STANDERD_LINE_BOLD)
#define MENU_COOK_SUCCESS_WIDTH_INSIDE    (MENU_COOK_SUCCESS_WIDTH_OUTSIDE  - (MENU_STANDERD_LINE_BOLD * 2))
#define MENU_COOK_SUCCESS_HEIGHT_INSIDE   (MENU_COOK_SUCCESS_HEIGHT_OUTSIDE - (MENU_STANDERD_LINE_BOLD * 2))

/* 成功・失敗メッセージの描画位置 */
#define MENU_COOK_SUCCESS_MSG_X          (MENU_COOK_SUCCESS_X_OUTSIDE + MENU_COOK_SUCCESS_WIDTH  - (SIZE_FONT_SJIS_WIDTH * 4))
#define MENU_COOK_SUCCESS_MSG_Y          (MENU_COOK_SUCCESS_Y_OUTSIDE + MENU_COOK_SUCCESS_HEIGHT - (SIZE_FONT_SJIS_HEIGHT >> 1))

#endif