
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xmapchip.h"

/*
* The configuration table for devices
*/

XMapchip_Config XMapchip_ConfigTable[XPAR_XMAPCHIP_NUM_INSTANCES] =
{
	{
		XPAR_MAPCHIP_0_DEVICE_ID,
		XPAR_MAPCHIP_0_S_AXI_CONTROL_BASEADDR
	}
};


