/*-----------------------------------------------------------------------------
 * Create  2023/07/09
 * Author  kouta kimura
 * -
 * 周辺機器のアドレスマップ、コマンド定数を管理
 * 
 *-----------------------------------------------------------------------------*/
#ifndef periheral_macro_h
#define periheral_macro_h


/**-----------------------------------------------------------------------------
 * Soc Periheral Adrs
 *-----------------------------------------------------------------------------*/
#define ADRS_GPIO_0_IO_CTRL		(0xf8015000)
#define ADRS_GPIO_0_IO_CTRL_OUT (ADRS_GPIO_0_IO_CTRL + 4)
#define ADRS_GPIO_0_IO_CTRL_EN 	(ADRS_GPIO_0_IO_CTRL + 8)
#define ADRS_GPIO_1_IO_CTRL 	(0xf8018000)
#define ADRS_GPIO_1_IO_CTRL_OUT (ADRS_GPIO_1_IO_CTRL + 4)
#define ADRS_GPIO_1_IO_CTRL_EN 	(ADRS_GPIO_1_IO_CTRL + 8)

/**-----------------------------------------------------------------------------
 * Bus Cmd
 *-----------------------------------------------------------------------------*/
#define USI_BUS_SELECT		(0x20)
#define UFI_BUS_SELECT		(0x30)
#define USI_READ_CMD		(0x80000000)
#define USI_WRITE_CMD		(0x40000000)
//
#define UFI_ENABLE_CMD		(0x80000000)
#define UFI_READ_CMD		(0x40000000)
#define UFI_WRITE_CMD		(0x00000000)


/**-----------------------------------------------------------------------------
 * USI Block Base Adrs
 *-----------------------------------------------------------------------------*/
#define BASE_BLOCK_USI_ADRS_GPIO	(0x00000000)
#define BASE_BLOCK_USI_ADRS_SPI		(0x00010000)
#define BASE_BLOCK_USI_ADRS_SYNTH	(0x00020000)
#define BASE_BLOCK_USI_ADRS_AUDIO	(0x00020000)
#define BASE_BLOCK_USI_ADRS_RAM		(0x00030000)
#define BASE_BLOCK_USI_ADRS_TIMER	(0x00040000)
#define BASE_BLOCK_USI_ADRS_MCB		(0x00050000)
#define BASE_BLOCK_USI_ADRS_VTB		(0x00060000)
#define BASE_BLOCK_USI_ADRS_I2C		(0x00070000)
#define BASE_BLOCK_USI_ADRS_NULL	(0x0fffffff)

// GPIO Block Reg Map
#define GPIO_REG_OUT_CTRL	(BASE_BLOCK_USI_ADRS_GPIO + 0x0)
#define GPIO_REG_ALTNATE	(BASE_BLOCK_USI_ADRS_GPIO + 0x8)

// SPI Block Reg Map
#define FLASH_MEM_PAGE_LEN	(2048)
#define SPI_REG_DIV			(BASE_BLOCK_USI_ADRS_SPI + 0x14)
#define SPI_REG_CS			(BASE_BLOCK_USI_ADRS_SPI + 0x1C)
#define SPI_REG_GPIO_ALT	(BASE_BLOCK_USI_ADRS_SPI + 0x20)
#define SPI_REG_MOSI		(BASE_BLOCK_USI_ADRS_SPI + 0x18)
#define SPI_REG_ENABLE		(BASE_BLOCK_USI_ADRS_SPI + 0x10)
#define SPI_REG_MISO		(BASE_BLOCK_USI_ADRS_SPI + 0x84)
#define SPI_REG_DONE		(BASE_BLOCK_USI_ADRS_SPI + 0x88)

// Syn Reg Map
#define SYNTH_REG_I2S_RST			(BASE_BLOCK_USI_ADRS_SYNTH + 0x00)
#define SYNTH_REG_DMA_ENABLE		(BASE_BLOCK_USI_ADRS_SYNTH + 0x04)
#define SYNTH_REG_DMA_CYCLE_ENABLE	(BASE_BLOCK_USI_ADRS_SYNTH + 0x08)
#define SYNTH_REG_DMA_ADRS_START	(BASE_BLOCK_USI_ADRS_SYNTH + 0x0C)
#define SYNTH_REG_DMA_ADRS_END		(BASE_BLOCK_USI_ADRS_SYNTH + 0x10)
#define SYNTH_REG_DMA_ADRS_ADD		(BASE_BLOCK_USI_ADRS_SYNTH + 0x14)
#define SYNTH_REG_AUDIO_AMP_CH4321	(BASE_BLOCK_USI_ADRS_SYNTH + 0x60)
#define SYNTH_REG_AUDIO_FREQ		(BASE_BLOCK_USI_ADRS_SYNTH + 0x80)
#define SYNTH_REG_AUDIO_PLAY		(BASE_BLOCK_USI_ADRS_SYNTH + 0x84)
#define SYNTH_REG_ON_NOTE_NUMBER	(BASE_BLOCK_USI_ADRS_SYNTH + 0xC0)

// Audio Tx Block Reg Map
#define AUDIO_REG_IO_HIZ			(BASE_BLOCK_USI_ADRS_AUDIO + 0x00)
#define AUDIO_REG_SFM_ENABLE		(BASE_BLOCK_USI_ADRS_AUDIO + 0x04)
#define AUDIO_REG_SFM_CYCLE_ENABLE	(BASE_BLOCK_USI_ADRS_AUDIO + 0x08)
#define AUDIO_REG_SFM_CLK_DIV		(BASE_BLOCK_USI_ADRS_AUDIO + 0x0C)
#define AUDIO_REG_SFM_CS_HOLD_TIME	(BASE_BLOCK_USI_ADRS_AUDIO + 0x10)
#define AUDIO_REG_SFM_CPU_WD_1		(BASE_BLOCK_USI_ADRS_AUDIO + 0x14)
#define AUDIO_REG_SFM_CPU_ENABLE	(BASE_BLOCK_USI_ADRS_AUDIO + 0x18)
#define AUDIO_REG_SFM_CPU_CS_CTRL	(BASE_BLOCK_USI_ADRS_AUDIO + 0x1C)
#define AUDIO_REG_SFM_CPU_VALID		(BASE_BLOCK_USI_ADRS_AUDIO + 0x20)
#define AUDIO_REG_SFM_CPU_WD_2		(BASE_BLOCK_USI_ADRS_AUDIO + 0x24)
#define AUDIO_REG_SFM_CPU_WD_3		(BASE_BLOCK_USI_ADRS_AUDIO + 0x28)
#define AUDIO_REG_SFM_CPU_DONE		(BASE_BLOCK_USI_ADRS_AUDIO + 0x30)
#define AUDIO_REG_AAC_CPU_WD		(BASE_BLOCK_USI_ADRS_AUDIO + 0x34)
#define AUDIO_REG_AAC_CPU_WE		(BASE_BLOCK_USI_ADRS_AUDIO + 0x38)
#define AUDIO_REG_SFM_START_ADRS_1	(BASE_BLOCK_USI_ADRS_AUDIO + 0x60)
#define AUDIO_REG_SFM_END_ADRS_1	(BASE_BLOCK_USI_ADRS_AUDIO + 0x64)
#define AUDIO_REG_SFM_START_ADRS_2	(BASE_BLOCK_USI_ADRS_AUDIO + 0x68)
#define AUDIO_REG_SFM_END_ADRS_2	(BASE_BLOCK_USI_ADRS_AUDIO + 0x6C)
#define AUDIO_REG_SFM_START_ADRS_3	(BASE_BLOCK_USI_ADRS_AUDIO + 0x70)
#define AUDIO_REG_SFM_END_ADRS_3	(BASE_BLOCK_USI_ADRS_AUDIO + 0x74)
#define AUDIO_REG_SFM_CPU_RD_1		(BASE_BLOCK_USI_ADRS_AUDIO + 0x90)
#define AUDIO_REG_SFM_CPU_RD_2		(BASE_BLOCK_USI_ADRS_AUDIO + 0x94)
#define AUDIO_REG_SFM_CPU_RD_3		(BASE_BLOCK_USI_ADRS_AUDIO + 0x98)
#define AUDIO_REG_AAC_ALERT			(BASE_BLOCK_USI_ADRS_AUDIO + 0x9C)
#define AUDIO_REG_SFM_ADD_ADRS_1	(BASE_BLOCK_USI_ADRS_AUDIO + 0xA0)
#define AUDIO_REG_SFM_ADD_ADRS_2	(BASE_BLOCK_USI_ADRS_AUDIO + 0xA4)
#define AUDIO_REG_SFM_ADD_ADRS_3	(BASE_BLOCK_USI_ADRS_AUDIO + 0xA8)

// RAM Block Reg Map
#define RAM_REG_RAM_RST				(BASE_BLOCK_USI_ADRS_RAM + 0x00)
#define RAM_REG_HDC_SEQ				(BASE_BLOCK_USI_ADRS_RAM + 0x01)
#define RAM_REG_HDC_WDQ				(BASE_BLOCK_USI_ADRS_RAM + 0x02)
#define RAM_REG_HDC_CMD_ADRS_L		(BASE_BLOCK_USI_ADRS_RAM + 0x03)
#define RAM_REG_HDC_CMD_ADRS_H		(BASE_BLOCK_USI_ADRS_RAM + 0x04)
//
#define RAM_REG_HDC_CAP_DQ			(BASE_BLOCK_USI_ADRS_RAM + 0x41)


// Timer Block Reg Map
#define TIMER_REG_DIV1	    (BASE_BLOCK_USI_ADRS_TIMER + 0x00)
#define TIMER_REG_DIV2	    (BASE_BLOCK_USI_ADRS_TIMER + 0x04)
#define TIMER_REG_DIV3	    (BASE_BLOCK_USI_ADRS_TIMER + 0x08)
#define TIMER_REG_ENABLE	(BASE_BLOCK_USI_ADRS_TIMER + 0x0C)
#define TIMER_REG_COUNT1	(BASE_BLOCK_USI_ADRS_TIMER + 0x40)
#define TIMER_REG_COUNT2	(BASE_BLOCK_USI_ADRS_TIMER + 0x44)
#define TIMER_REG_COUNT3	(BASE_BLOCK_USI_ADRS_TIMER + 0x48)

// MCB Reg Map
#define MCB_REG_RAM_WD			(BASE_BLOCK_USI_ADRS_MCB + 0x00)
#define MCB_REG_RAM_ADRS		(BASE_BLOCK_USI_ADRS_MCB + 0x04)
#define MCB_REG_RAM_ENABLE		(BASE_BLOCK_USI_ADRS_MCB + 0x08)
#define MCB_REG_RAM_BURST_RUN	(BASE_BLOCK_USI_ADRS_MCB + 0x0C)
#define MCB_REG_RAM_RAM_STATUS	(BASE_BLOCK_USI_ADRS_MCB + 0x40)
#define MCB_REG_RAM_RD			(BASE_BLOCK_USI_ADRS_MCB + 0x44)
#define MCB_REG_RAM_RD_VD		(BASE_BLOCK_USI_ADRS_MCB + 0x48)

// Video Tx Block Reg Map
#define VIDEO_REG_DOT_SQUARE_COLOR1	(BASE_BLOCK_USI_ADRS_VTB + 0x200)
#define VIDEO_REG_DOT_SQUARE_LEFT1	(BASE_BLOCK_USI_ADRS_VTB + 0x201)
#define VIDEO_REG_DOT_SQUARE_RIGHT1	(BASE_BLOCK_USI_ADRS_VTB + 0x202)
#define VIDEO_REG_DOT_SQUARE_TOP1	(BASE_BLOCK_USI_ADRS_VTB + 0x203)
#define VIDEO_REG_DOT_SQUARE_UNDER1	(BASE_BLOCK_USI_ADRS_VTB + 0x204)
#define VIDEO_REG_DOT_SQUARE_COLOR2	(BASE_BLOCK_USI_ADRS_VTB + 0x205)
#define VIDEO_REG_DOT_SQUARE_LEFT2	(BASE_BLOCK_USI_ADRS_VTB + 0x206)
#define VIDEO_REG_DOT_SQUARE_RIGHT2	(BASE_BLOCK_USI_ADRS_VTB + 0x207)
#define VIDEO_REG_DOT_SQUARE_TOP2	(BASE_BLOCK_USI_ADRS_VTB + 0x208)
#define VIDEO_REG_DOT_SQUARE_UNDER2	(BASE_BLOCK_USI_ADRS_VTB + 0x209)
#define VIDEO_REG_DOT_SQUARE_COLOR3	(BASE_BLOCK_USI_ADRS_VTB + 0x20a)
#define VIDEO_REG_DOT_SQUARE_LEFT3	(BASE_BLOCK_USI_ADRS_VTB + 0x20b)
#define VIDEO_REG_DOT_SQUARE_RIGHT3	(BASE_BLOCK_USI_ADRS_VTB + 0x20c)
#define VIDEO_REG_DOT_SQUARE_TOP3	(BASE_BLOCK_USI_ADRS_VTB + 0x20d)
#define VIDEO_REG_DOT_SQUARE_UNDER3	(BASE_BLOCK_USI_ADRS_VTB + 0x20e)
#define VIDEO_REG_DOT_SQUARE_COLOR4	(BASE_BLOCK_USI_ADRS_VTB + 0x20f)
#define VIDEO_REG_DOT_SQUARE_LEFT4	(BASE_BLOCK_USI_ADRS_VTB + 0x210)
#define VIDEO_REG_DOT_SQUARE_RIGHT4	(BASE_BLOCK_USI_ADRS_VTB + 0x211)
#define VIDEO_REG_DOT_SQUARE_TOP4	(BASE_BLOCK_USI_ADRS_VTB + 0x212)
#define VIDEO_REG_DOT_SQUARE_UNDER4	(BASE_BLOCK_USI_ADRS_VTB + 0x213)
#define VIDEO_REG_DOT_SQUARE_COLOR5	(BASE_BLOCK_USI_ADRS_VTB + 0x214)
#define VIDEO_REG_DOT_SQUARE_LEFT5	(BASE_BLOCK_USI_ADRS_VTB + 0x215)
#define VIDEO_REG_DOT_SQUARE_RIGHT5	(BASE_BLOCK_USI_ADRS_VTB + 0x216)
#define VIDEO_REG_DOT_SQUARE_TOP5	(BASE_BLOCK_USI_ADRS_VTB + 0x217)
#define VIDEO_REG_DOT_SQUARE_UNDER5	(BASE_BLOCK_USI_ADRS_VTB + 0x218)
#define VIDEO_REG_DOT_SQUARE_COLOR6	(BASE_BLOCK_USI_ADRS_VTB + 0x219)
#define VIDEO_REG_DOT_SQUARE_LEFT6	(BASE_BLOCK_USI_ADRS_VTB + 0x21a)
#define VIDEO_REG_DOT_SQUARE_RIGHT6	(BASE_BLOCK_USI_ADRS_VTB + 0x21b)
#define VIDEO_REG_DOT_SQUARE_TOP6	(BASE_BLOCK_USI_ADRS_VTB + 0x21c)
#define VIDEO_REG_DOT_SQUARE_UNDER6	(BASE_BLOCK_USI_ADRS_VTB + 0x21d)
#define VIDEO_REG_DOT_SQUARE_COLOR7	(BASE_BLOCK_USI_ADRS_VTB + 0x21e)
#define VIDEO_REG_DOT_SQUARE_LEFT7	(BASE_BLOCK_USI_ADRS_VTB + 0x21f)
#define VIDEO_REG_DOT_SQUARE_RIGHT7	(BASE_BLOCK_USI_ADRS_VTB + 0x220)
#define VIDEO_REG_DOT_SQUARE_TOP7	(BASE_BLOCK_USI_ADRS_VTB + 0x221)
#define VIDEO_REG_DOT_SQUARE_UNDER7	(BASE_BLOCK_USI_ADRS_VTB + 0x222)
//
#define VIDEO_REG_PDP_HPOS			(BASE_BLOCK_USI_ADRS_VTB + 0x400)
#define VIDEO_REG_PDP_VPOS			(BASE_BLOCK_USI_ADRS_VTB + 0x401)

// I2C Block Reg Map
#define I2C_REG_SLAVE_READ_DATA		(BASE_BLOCK_USI_ADRS_I2C + 0x40)


/**-----------------------------------------------------------------------------
 * UFI Block Base Adrs
 *-----------------------------------------------------------------------------*/
#define BASE_UFI_BLOCK_ADRS_MCB	(0x00000000)
#define BASE_UFI_BLOCK_ADRS_VTB	(0x02000000)


#define MCB_CACHE_READ			(BASE_UFI_BLOCK_ADRS_MCB | UFI_READ_CMD)


#endif