#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed May 26 10:51:31 JST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim TEST_behav -key {Behavioral:sim_1:Functional:TEST} -tclbatch TEST.tcl -view /home/koutakimura/workspace/ProjectFolder/Xilinx/workspace/Arty_z7_20/SW/SW_NOIZE/TEST_behav.wcfg -log simulate.log"
xsim TEST_behav -key {Behavioral:sim_1:Functional:TEST} -tclbatch TEST.tcl -view /home/koutakimura/workspace/ProjectFolder/Xilinx/workspace/Arty_z7_20/SW/SW_NOIZE/TEST_behav.wcfg -log simulate.log

