/*-----------------------------------------------------------------------------
 * Create  2024/06/16
 * Author  kouta kimura
 * -
 * 周辺機器のアドレスマップ、コマンド定数を管理
 * 
 *-----------------------------------------------------------------------------*/
#ifndef trypad_fpga_macro_h
#define trypad_fpga_macro_h


/**-----------------------------------------------------------------------------
 * Bus Cmd
 *-----------------------------------------------------------------------------*/
#define USI_BUS_SELECT		(0x20)
#define UFI_BUS_SELECT		(0x30)
#define USI_READ_CMD		(0x80000000)
#define USI_WRITE_CMD		(0x40000000)
//
#define UFI_ENABLE_CMD		(0x80000000)
#define UFI_READ_CMD		(0x40000000)
#define UFI_WRITE_CMD		(0x00000000)


/**-----------------------------------------------------------------------------
 * USI Block Base Adrs MACRO
 *-----------------------------------------------------------------------------*/
#define BASE_BLOCK_USI_ADRS_GPIO	(0x00000000)
#define BASE_BLOCK_USI_ADRS_SPI		(0x00010000)
#define BASE_BLOCK_USI_ADRS_SYNTH	(0x00020000)
#define BASE_BLOCK_USI_ADRS_AUDIO	(0x00020000)
#define BASE_BLOCK_USI_ADRS_RAM		(0x00030000)
#define BASE_BLOCK_USI_ADRS_TIMER	(0x00040000)
#define BASE_BLOCK_USI_ADRS_MCB		(0x00050000)
#define BASE_BLOCK_USI_ADRS_VTB		(0x00060000)
#define BASE_BLOCK_USI_ADRS_I2C		(0x00070000)
#define BASE_BLOCK_USI_ADRS_NULL	(0x0fffffff)

// GPIO Block Reg Map
#define GPIO_REG_OUT_CTRL			(BASE_BLOCK_USI_ADRS_GPIO + 0x0)
#define GPIO_REG_ALTNATE			(BASE_BLOCK_USI_ADRS_GPIO + 0x8)
#define GPIO_REG_VIDEO_GPIO_OE		(BASE_BLOCK_USI_ADRS_GPIO + 0x10)
#define GPIO_REG_AUDIO_GPIO_OE		(BASE_BLOCK_USI_ADRS_GPIO + 0x14)
#define GPIO_REG_ROM_GPIO_OE		(BASE_BLOCK_USI_ADRS_GPIO + 0x18)
#define GPIO_REG_CFG_ROM_GPIO_OE	(BASE_BLOCK_USI_ADRS_GPIO + 0x1C)
#define GPIO_REG_PUSH_SW			(BASE_BLOCK_USI_ADRS_GPIO + 0x41)
#define GPIO_REG_EDGE_SW			(BASE_BLOCK_USI_ADRS_GPIO + 0x42)
#define GPIO_REG_LONG_SW			(BASE_BLOCK_USI_ADRS_GPIO + 0x43)

// SPI Block Reg Map
#define FLASH_MEM_PAGE_LEN			(2048)
#define SPI_REG_IO_HIZ				(BASE_BLOCK_USI_ADRS_SPI + 0x00)
#define SPI_REG_SFM_ENABLE			(BASE_BLOCK_USI_ADRS_SPI + 0x04)
#define SPI_REG_SFM_CYCLE_ENABLE	(BASE_BLOCK_USI_ADRS_SPI + 0x08)
#define SPI_REG_SFM_CLK_DIV			(BASE_BLOCK_USI_ADRS_SPI + 0x0C)
#define SPI_REG_SFM_CS_HOLD_TIME	(BASE_BLOCK_USI_ADRS_SPI + 0x10)
#define SPI_REG_SFM_CPU_WD_1		(BASE_BLOCK_USI_ADRS_SPI + 0x14)
#define SPI_REG_SFM_CPU_ENABLE		(BASE_BLOCK_USI_ADRS_SPI + 0x18)
#define SPI_REG_SFM_CPU_CS_CTRL		(BASE_BLOCK_USI_ADRS_SPI + 0x1C)
#define SPI_REG_SFM_CPU_VALID		(BASE_BLOCK_USI_ADRS_SPI + 0x20)
#define SPI_REG_SFM_CPU_WD_2		(BASE_BLOCK_USI_ADRS_SPI + 0x24)
#define SPI_REG_SFM_CPU_WD_3		(BASE_BLOCK_USI_ADRS_SPI + 0x28)
#define SPI_REG_SFM_CPU_DONE		(BASE_BLOCK_USI_ADRS_SPI + 0x30)
#define SPI_REG_SSP_DEVICE_SEL		(BASE_BLOCK_USI_ADRS_SPI + 0x34)
#define SPI_REG_SFM_START_ADRS_1	(BASE_BLOCK_USI_ADRS_SPI + 0x60)
#define SPI_REG_SFM_END_ADRS_1		(BASE_BLOCK_USI_ADRS_SPI + 0x64)
#define SPI_REG_SFM_START_ADRS_2	(BASE_BLOCK_USI_ADRS_SPI + 0x68)
#define SPI_REG_SFM_END_ADRS_2		(BASE_BLOCK_USI_ADRS_SPI + 0x6C)
#define SPI_REG_SFM_START_ADRS_3	(BASE_BLOCK_USI_ADRS_SPI + 0x70)
#define SPI_REG_SFM_END_ADRS_3		(BASE_BLOCK_USI_ADRS_SPI + 0x74)
#define SPI_REG_SFM_CPU_RD_1		(BASE_BLOCK_USI_ADRS_SPI + 0x90)
#define SPI_REG_SFM_CPU_RD_2		(BASE_BLOCK_USI_ADRS_SPI + 0x94)
#define SPI_REG_SFM_CPU_RD_3		(BASE_BLOCK_USI_ADRS_SPI + 0x98)
#define SPI_REG_AAC_ALERT			(BASE_BLOCK_USI_ADRS_SPI + 0x9C)
#define SPI_REG_SFM_ADD_ADRS_1		(BASE_BLOCK_USI_ADRS_SPI + 0xA0)
#define SPI_REG_SFM_ADD_ADRS_2		(BASE_BLOCK_USI_ADRS_SPI + 0xA4)
#define SPI_REG_SFM_ADD_ADRS_3		(BASE_BLOCK_USI_ADRS_SPI + 0xA8)

// Syn Reg Map
#define SYNTH_REG_I2S_RST			(BASE_BLOCK_USI_ADRS_SYNTH + 0x00)
#define SYNTH_REG_DMA_ENABLE		(BASE_BLOCK_USI_ADRS_SYNTH + 0x04)
#define SYNTH_REG_DMA_CYCLE_ENABLE	(BASE_BLOCK_USI_ADRS_SYNTH + 0x08)
#define SYNTH_REG_DMA_ADRS_START	(BASE_BLOCK_USI_ADRS_SYNTH + 0x0C)
#define SYNTH_REG_DMA_ADRS_END		(BASE_BLOCK_USI_ADRS_SYNTH + 0x10)
#define SYNTH_REG_DMA_ADRS_ADD		(BASE_BLOCK_USI_ADRS_SYNTH + 0x14)
#define SYNTH_REG_AUDIO_AMP_CH4321	(BASE_BLOCK_USI_ADRS_SYNTH + 0x60)
#define SYNTH_REG_AUDIO_FREQ		(BASE_BLOCK_USI_ADRS_SYNTH + 0x80)
#define SYNTH_REG_AUDIO_PLAY		(BASE_BLOCK_USI_ADRS_SYNTH + 0x84)
#define SYNTH_REG_ON_NOTE_NUMBER	(BASE_BLOCK_USI_ADRS_SYNTH + 0xC0)

// Audio Tx Block Reg Map
#define AUDIO_REG_IO_HIZ			(BASE_BLOCK_USI_ADRS_AUDIO + 0x00)
#define AUDIO_REG_SFM_ENABLE		(BASE_BLOCK_USI_ADRS_AUDIO + 0x04)
#define AUDIO_REG_SFM_CYCLE_ENABLE	(BASE_BLOCK_USI_ADRS_AUDIO + 0x08)
#define AUDIO_REG_SFM_CLK_DIV		(BASE_BLOCK_USI_ADRS_AUDIO + 0x0C)
#define AUDIO_REG_SFM_CS_HOLD_TIME	(BASE_BLOCK_USI_ADRS_AUDIO + 0x10)
#define AUDIO_REG_SFM_CPU_WD_1		(BASE_BLOCK_USI_ADRS_AUDIO + 0x14)
#define AUDIO_REG_SFM_CPU_ENABLE	(BASE_BLOCK_USI_ADRS_AUDIO + 0x18)
#define AUDIO_REG_SFM_CPU_CS_CTRL	(BASE_BLOCK_USI_ADRS_AUDIO + 0x1C)
#define AUDIO_REG_SFM_CPU_VALID		(BASE_BLOCK_USI_ADRS_AUDIO + 0x20)
#define AUDIO_REG_SFM_CPU_WD_2		(BASE_BLOCK_USI_ADRS_AUDIO + 0x24)
#define AUDIO_REG_SFM_CPU_WD_3		(BASE_BLOCK_USI_ADRS_AUDIO + 0x28)
#define AUDIO_REG_SFM_CPU_DONE		(BASE_BLOCK_USI_ADRS_AUDIO + 0x30)
#define AUDIO_REG_AAC_CPU_WD		(BASE_BLOCK_USI_ADRS_AUDIO + 0x34)
#define AUDIO_REG_AAC_CPU_WE		(BASE_BLOCK_USI_ADRS_AUDIO + 0x38)
#define AUDIO_REG_SFM_START_ADRS_1	(BASE_BLOCK_USI_ADRS_AUDIO + 0x60)
#define AUDIO_REG_SFM_END_ADRS_1	(BASE_BLOCK_USI_ADRS_AUDIO + 0x64)
#define AUDIO_REG_SFM_START_ADRS_2	(BASE_BLOCK_USI_ADRS_AUDIO + 0x68)
#define AUDIO_REG_SFM_END_ADRS_2	(BASE_BLOCK_USI_ADRS_AUDIO + 0x6C)
#define AUDIO_REG_SFM_START_ADRS_3	(BASE_BLOCK_USI_ADRS_AUDIO + 0x70)
#define AUDIO_REG_SFM_END_ADRS_3	(BASE_BLOCK_USI_ADRS_AUDIO + 0x74)
#define AUDIO_REG_SFM_CPU_RD_1		(BASE_BLOCK_USI_ADRS_AUDIO + 0x90)
#define AUDIO_REG_SFM_CPU_RD_2		(BASE_BLOCK_USI_ADRS_AUDIO + 0x94)
#define AUDIO_REG_SFM_CPU_RD_3		(BASE_BLOCK_USI_ADRS_AUDIO + 0x98)
#define AUDIO_REG_AAC_ALERT			(BASE_BLOCK_USI_ADRS_AUDIO + 0x9C)
#define AUDIO_REG_SFM_ADD_ADRS_1	(BASE_BLOCK_USI_ADRS_AUDIO + 0xA0)
#define AUDIO_REG_SFM_ADD_ADRS_2	(BASE_BLOCK_USI_ADRS_AUDIO + 0xA4)
#define AUDIO_REG_SFM_ADD_ADRS_3	(BASE_BLOCK_USI_ADRS_AUDIO + 0xA8)

// RAM Block Reg Map
#define RAM_REG_RAM_CFG_CMD			(BASE_BLOCK_USI_ADRS_RAM + 0x00)
#define RAM_REG_RAM_CFG_ENABLE		(BASE_BLOCK_USI_ADRS_RAM + 0x01)
#define RAM_REG_RAM_CFG_RST			(BASE_BLOCK_USI_ADRS_RAM + 0x02)
#define RAM_REG_RAM_MAT_ENABLE		(BASE_BLOCK_USI_ADRS_RAM + 0x10)
#define RAM_REG_RAM_MAT_RST			(BASE_BLOCK_USI_ADRS_RAM + 0x11)
#define RAM_REG_RAM_MAT_MEM_WD		(BASE_BLOCK_USI_ADRS_RAM + 0x12)
#define RAM_REG_RAM_MAT_MEM_WD_OE	(BASE_BLOCK_USI_ADRS_RAM + 0x13)
#define RAM_REG_RAM_MAT_MEM_WA		(BASE_BLOCK_USI_ADRS_RAM + 0x14)
#define RAM_REG_RAM_MAT_MEM_WE		(BASE_BLOCK_USI_ADRS_RAM + 0x15)
#define RAM_REG_RAM_MAT_MEM_RA		(BASE_BLOCK_USI_ADRS_RAM + 0x16)
#define RAM_REG_RAM_MEM_CLK_DIV		(BASE_BLOCK_USI_ADRS_RAM + 0x30)
//
#define RAM_REG_RAM_CFG_DONE		(BASE_BLOCK_USI_ADRS_RAM + 0x40)
#define RAM_REG_RAM_MAT_DONE		(BASE_BLOCK_USI_ADRS_RAM + 0x50)
#define RAM_REG_RAM_MAT_MEM_RD		(BASE_BLOCK_USI_ADRS_RAM + 0x51)

// Timer Block Reg Map
#define TIMER_REG_DIV1				(BASE_BLOCK_USI_ADRS_TIMER + 0x00)
#define TIMER_REG_DIV2				(BASE_BLOCK_USI_ADRS_TIMER + 0x04)
#define TIMER_REG_DIV3				(BASE_BLOCK_USI_ADRS_TIMER + 0x08)
#define TIMER_REG_ENABLE			(BASE_BLOCK_USI_ADRS_TIMER + 0x0C)
#define TIMER_REG_COUNT1			(BASE_BLOCK_USI_ADRS_TIMER + 0x40)
#define TIMER_REG_COUNT2			(BASE_BLOCK_USI_ADRS_TIMER + 0x44)
#define TIMER_REG_COUNT3			(BASE_BLOCK_USI_ADRS_TIMER + 0x48)

// MCB Reg Map
#define MCB_REG_RAM_WD				(BASE_BLOCK_USI_ADRS_MCB + 0x00)
#define MCB_REG_RAM_ADRS			(BASE_BLOCK_USI_ADRS_MCB + 0x04)
#define MCB_REG_RAM_ENABLE			(BASE_BLOCK_USI_ADRS_MCB + 0x08)
#define MCB_REG_RAM_BURST_RUN		(BASE_BLOCK_USI_ADRS_MCB + 0x0C)
#define MCB_REG_RAM_RAM_STATUS		(BASE_BLOCK_USI_ADRS_MCB + 0x40)
#define MCB_REG_RAM_RD				(BASE_BLOCK_USI_ADRS_MCB + 0x44)
#define MCB_REG_RAM_RD_VD			(BASE_BLOCK_USI_ADRS_MCB + 0x48)
#define MCB_REG_FPGA_VERSION		(BASE_BLOCK_USI_ADRS_MCB + 0xF0)
#define MCB_REG_CUSTOM_CODE			(BASE_BLOCK_USI_ADRS_MCB + 0xF4)

// Video Tx Block Reg Map
#define VIDEO_REG_VSG_RST			(BASE_BLOCK_USI_ADRS_VTB + 0x020)

#define VIDEO_REG_TFT_DATA			(BASE_BLOCK_USI_ADRS_VTB + 0x050)
#define VIDEO_REG_TFT_WR			(BASE_BLOCK_USI_ADRS_VTB + 0x051)
#define VIDEO_REG_TFT_DCX			(BASE_BLOCK_USI_ADRS_VTB + 0x052)
#define VIDEO_REG_TFT_RD			(BASE_BLOCK_USI_ADRS_VTB + 0x053)
#define VIDEO_REG_TFT_CS			(BASE_BLOCK_USI_ADRS_VTB + 0x054)
#define VIDEO_REG_TFT_RST			(BASE_BLOCK_USI_ADRS_VTB + 0x055)
#define VIDEO_REG_TFT_IM			(BASE_BLOCK_USI_ADRS_VTB + 0x056)
#define VIDEO_REG_TFT_GATE			(BASE_BLOCK_USI_ADRS_VTB + 0x057)
#define VIDEO_REG_VTU_CONVERTER_RST	(BASE_BLOCK_USI_ADRS_VTB + 0x058)

#define VIDEO_REG_DOT_SQUARE_COLOR1	(BASE_BLOCK_USI_ADRS_VTB + 0x200)
#define VIDEO_REG_DOT_SQUARE_LEFT1	(BASE_BLOCK_USI_ADRS_VTB + 0x201)
#define VIDEO_REG_DOT_SQUARE_RIGHT1	(BASE_BLOCK_USI_ADRS_VTB + 0x202)
#define VIDEO_REG_DOT_SQUARE_TOP1	(BASE_BLOCK_USI_ADRS_VTB + 0x203)
#define VIDEO_REG_DOT_SQUARE_UNDER1	(BASE_BLOCK_USI_ADRS_VTB + 0x204)
#define VIDEO_REG_DOT_SQUARE_COLOR2	(BASE_BLOCK_USI_ADRS_VTB + 0x205)
#define VIDEO_REG_DOT_SQUARE_LEFT2	(BASE_BLOCK_USI_ADRS_VTB + 0x206)
#define VIDEO_REG_DOT_SQUARE_RIGHT2	(BASE_BLOCK_USI_ADRS_VTB + 0x207)
#define VIDEO_REG_DOT_SQUARE_TOP2	(BASE_BLOCK_USI_ADRS_VTB + 0x208)
#define VIDEO_REG_DOT_SQUARE_UNDER2	(BASE_BLOCK_USI_ADRS_VTB + 0x209)
#define VIDEO_REG_DOT_SQUARE_COLOR3	(BASE_BLOCK_USI_ADRS_VTB + 0x20a)
#define VIDEO_REG_DOT_SQUARE_LEFT3	(BASE_BLOCK_USI_ADRS_VTB + 0x20b)
#define VIDEO_REG_DOT_SQUARE_RIGHT3	(BASE_BLOCK_USI_ADRS_VTB + 0x20c)
#define VIDEO_REG_DOT_SQUARE_TOP3	(BASE_BLOCK_USI_ADRS_VTB + 0x20d)
#define VIDEO_REG_DOT_SQUARE_UNDER3	(BASE_BLOCK_USI_ADRS_VTB + 0x20e)
#define VIDEO_REG_DOT_SQUARE_COLOR4	(BASE_BLOCK_USI_ADRS_VTB + 0x20f)
#define VIDEO_REG_DOT_SQUARE_LEFT4	(BASE_BLOCK_USI_ADRS_VTB + 0x210)
#define VIDEO_REG_DOT_SQUARE_RIGHT4	(BASE_BLOCK_USI_ADRS_VTB + 0x211)
#define VIDEO_REG_DOT_SQUARE_TOP4	(BASE_BLOCK_USI_ADRS_VTB + 0x212)
#define VIDEO_REG_DOT_SQUARE_UNDER4	(BASE_BLOCK_USI_ADRS_VTB + 0x213)
#define VIDEO_REG_DOT_SQUARE_COLOR5	(BASE_BLOCK_USI_ADRS_VTB + 0x214)
#define VIDEO_REG_DOT_SQUARE_LEFT5	(BASE_BLOCK_USI_ADRS_VTB + 0x215)
#define VIDEO_REG_DOT_SQUARE_RIGHT5	(BASE_BLOCK_USI_ADRS_VTB + 0x216)
#define VIDEO_REG_DOT_SQUARE_TOP5	(BASE_BLOCK_USI_ADRS_VTB + 0x217)
#define VIDEO_REG_DOT_SQUARE_UNDER5	(BASE_BLOCK_USI_ADRS_VTB + 0x218)
#define VIDEO_REG_DOT_SQUARE_COLOR6	(BASE_BLOCK_USI_ADRS_VTB + 0x219)
#define VIDEO_REG_DOT_SQUARE_LEFT6	(BASE_BLOCK_USI_ADRS_VTB + 0x21a)
#define VIDEO_REG_DOT_SQUARE_RIGHT6	(BASE_BLOCK_USI_ADRS_VTB + 0x21b)
#define VIDEO_REG_DOT_SQUARE_TOP6	(BASE_BLOCK_USI_ADRS_VTB + 0x21c)
#define VIDEO_REG_DOT_SQUARE_UNDER6	(BASE_BLOCK_USI_ADRS_VTB + 0x21d)
#define VIDEO_REG_DOT_SQUARE_COLOR7	(BASE_BLOCK_USI_ADRS_VTB + 0x21e)
#define VIDEO_REG_DOT_SQUARE_LEFT7	(BASE_BLOCK_USI_ADRS_VTB + 0x21f)
#define VIDEO_REG_DOT_SQUARE_RIGHT7	(BASE_BLOCK_USI_ADRS_VTB + 0x220)
#define VIDEO_REG_DOT_SQUARE_TOP7	(BASE_BLOCK_USI_ADRS_VTB + 0x221)
#define VIDEO_REG_DOT_SQUARE_UNDER7	(BASE_BLOCK_USI_ADRS_VTB + 0x222)
//
#define VIDEO_REG_PDP_HPOS			(BASE_BLOCK_USI_ADRS_VTB + 0x400)
#define VIDEO_REG_PDP_VPOS			(BASE_BLOCK_USI_ADRS_VTB + 0x401)

// I2C Block Reg Map
#define I2C_REG_SLAVE_READ_DATA		(BASE_BLOCK_USI_ADRS_I2C + 0x40)


/**-----------------------------------------------------------------------------
 * UFI Block Base Adrs
 *-----------------------------------------------------------------------------*/
#define BASE_UFI_BLOCK_ADRS_MCB	(0x00000000)
#define BASE_UFI_BLOCK_ADRS_VTB	(0x02000000)

#define MCB_CACHE_READ			(BASE_UFI_BLOCK_ADRS_MCB | UFI_READ_CMD)

/**-----------------------------------------------------------------------------
 * SW Bit
 *-----------------------------------------------------------------------------*/
#define SW_RDOWN				(0x001)
#define SW_X					(0x002)
#define SW_RUP					(0x004)
#define SW_Y					(0x008)
#define SW_B					(0x010)
#define SW_A					(0x020)
#define SW_LDOWN				(0x040)
#define SW_LEFT 				(0x080)
#define SW_LUP					(0x100)
#define SW_UP					(0x200)
#define SW_DOWN					(0x400)
#define SW_RIGHT				(0x800)

#endif