/*
 * Create 2021/07/02
 * Author koutakimura
 * OS     Ubuntu LTS 20.04
 * Editor VSCode ver1.57.1
 * -
 * イベント時に発生するメッセージ描画文字列を管理するヘッダーファイル
 * sjisのフォントデータを使用するためファイルのエンコード設定をsjisに変更する
 */
#ifndef effect_msg_macro_h   /* prevent circular inclusions */
#define effect_msg_macro_h   /* by using protection macros */

/*
#define EFFECT_MSG1     ("じぶんの攻撃力を上げる")
#define EFFECT_MSG2     ("")
#define EFFECT_MSG3     ("")
#define EFFECT_MSG4     ("")
#define EFFECT_MSG5     ("")
#define EFFECT_MSG6     ("")
#define EFFECT_MSG7     ("")
#define EFFECT_MSG8     ("")
#define EFFECT_MSG9     ("")
#define EFFECT_MSG10    ("")
#define EFFECT_MSG11    ("")
#define EFFECT_MSG12    ("")
#define EFFECT_MSG13    ("")
#define EFFECT_MSG14    ("")
#define EFFECT_MSG15    ("")
#define EFFECT_MSG16    ("")
#define EFFECT_MSG17    ("")
#define EFFECT_MSG18    ("")
#define EFFECT_MSG19    ("")
#define EFFECT_MSG20    ("")
#define EFFECT_MSG21    ("")
#define EFFECT_MSG22    ("")
#define EFFECT_MSG23    ("")
#define EFFECT_MSG24    ("")
#define EFFECT_MSG25    ("")
#define EFFECT_MSG26    ("")
#define EFFECT_MSG27    ("")
#define EFFECT_MSG28    ("")
#define EFFECT_MSG29    ("")
#define EFFECT_MSG30    ("")
#define EFFECT_MSG31    ("")
#define EFFECT_MSG32    ("")
#define EFFECT_MSG33    ("")
#define EFFECT_MSG34    ("")
#define EFFECT_MSG35    ("")
#define EFFECT_MSG36    ("")
#define EFFECT_MSG37    ("")
#define EFFECT_MSG38    ("")
#define EFFECT_MSG39    ("")
#define EFFECT_MSG40    ("")
#define EFFECT_MSG41    ("")
#define EFFECT_MSG42    ("")
#define EFFECT_MSG43    ("")
#define EFFECT_MSG44    ("")
#define EFFECT_MSG45    ("")
#define EFFECT_MSG46    ("")
#define EFFECT_MSG47    ("")
#define EFFECT_MSG48    ("")
#define EFFECT_MSG49    ("")
#define EFFECT_MSG50    ("")
#define EFFECT_MSG51    ("")
#define EFFECT_MSG52    ("")
#define EFFECT_MSG53    ("")
#define EFFECT_MSG54    ("")
#define EFFECT_MSG55    ("")
#define EFFECT_MSG56    ("")
#define EFFECT_MSG57    ("")
#define EFFECT_MSG58    ("")
#define EFFECT_MSG59    ("")
#define EFFECT_MSG60    ("")
#define EFFECT_MSG61    ("")
#define EFFECT_MSG62    ("")
#define EFFECT_MSG63    ("")
#define EFFECT_MSG64    ("")
#define EFFECT_MSG65    ("")
#define EFFECT_MSG66    ("")
#define EFFECT_MSG67    ("")
#define EFFECT_MSG68    ("")
#define EFFECT_MSG69    ("")
#define EFFECT_MSG70    ("")
#define EFFECT_MSG71    ("")
#define EFFECT_MSG72    ("")
#define EFFECT_MSG73    ("")
#define EFFECT_MSG74    ("")
#define EFFECT_MSG75    ("")
#define EFFECT_MSG76    ("")
#define EFFECT_MSG77    ("")
#define EFFECT_MSG78    ("")
#define EFFECT_MSG79    ("")
#define EFFECT_MSG80    ("")
#define EFFECT_MSG81    ("")
#define EFFECT_MSG82    ("")
#define EFFECT_MSG83    ("")
#define EFFECT_MSG84    ("")
#define EFFECT_MSG85    ("")
#define EFFECT_MSG86    ("")
#define EFFECT_MSG87    ("")
#define EFFECT_MSG88    ("")
#define EFFECT_MSG89    ("")
#define EFFECT_MSG90    ("")
*/
#endif