/*
 * 城と街中の当たり判定を管理
 */

#ifndef direct_build_struct_h   /* prevent circular inclusions */
#define direct_build_struct_h   /* by using protection macros */


/*
 * 構造体の要素数
 */
#define SUBMAP_DIRECT_DB_SIZE ((sizeof (submap_direct))/(sizeof (SubmapDirect)))


/*
 * ver2. 2021/06/22
 * データベースのアクセス用にスタートIDの行を追加
 * スタートIDと一致した行から連番でアクセスするためデータの並び順に注意すること
 *
 * ver1. 2021/06/10
 * サブマップ内の固定座標でイベントが起こる個所のID名を指定
 * event_id
 *
 * イベントの種類を指定
 * event_type
 * 
 * 次のシステムの動作方法を指定
 * next_gamesystem
 * 
 * 次の描画方法を指定
 * next_drawtype
 * 
 * マップの当たり判定座標を指定
 * xpos, ypos
 * 
 * 当たり判定の確認方法を固定座標又は範囲内で選択
 * VARIABLEの場合 xpos, yposは0を指定
 * point
 */
typedef struct
{
	uint32_t event_id;
	uint32_t event_type;
	uint32_t next_system;
	uint8_t next_drawtype;
	uint8_t xpos;
	uint8_t ypos;
	uint8_t point;
} SubmapDirect;


/* TODO
 * サブマップ内の可変イベント処理はどうするか考える
 *
 * 〇可変イベント処理とは？
 * 宝箱のような固定イベントではなく、NPCが町中を徘徊していたりするイベントのこと
 * 
 * ver1. 2021/06/10
 * サブマップのイベントのすべてを管理するデータベース
 * 座標に応じてウィンドウの表示方法、イベントの種類、そのイベントのIDを取得
 */

static const SubmapDirect submap_direct[] =
{
	{DIRECT_ROMEN_ID_START,	 	 EVENT_TYPE_NULL, 					SYSTEM_NULL,					DISPLAY_NULL_DRAW,			0,	0,	DIRECT_POINT_NULL		},
	{DIRECT_ROMEN_ID_EXIT,	 	 EVENT_TYPE_WORLD_STATE_OTHER_MAP, 	SYSTEM_MAP_DARKENING_WINDOW,	DISPLAY_DARKENING_DRAW,		0,  0,	DIRECT_POINT_VARIABLE	},
	{DIRECT_ROMEN_ID_HOUSE1,	 EVENT_TYPE_SAMEMAP_MOVE,  			SYSTEM_MAP_DARKENING_SUBMAP,	DISPLAY_DARKENING_DRAW,     41, 20, DIRECT_POINT_FIXED		},
	{DIRECT_ROMEN_ID_HOUSE2,	 EVENT_TYPE_SAMEMAP_MOVE,  			SYSTEM_MAP_DARKENING_SUBMAP,	DISPLAY_DARKENING_DRAW,     11, 12, DIRECT_POINT_FIXED		},
	{DIRECT_ROMEN_ID_ITEM_SHOP,  EVENT_TYPE_TOOLS_SHOP, 			SYSTEM_SHOP_WINDOW,				DISPLAY_FIELD_CENTER_DRAW,	10, 10,	DIRECT_POINT_FIXED		},
	{DIRECT_ROMEN_ID_WEPON_SHOP, EVENT_TYPE_TOOLS_SHOP, 			SYSTEM_SHOP_WINDOW,				DISPLAY_FIELD_CENTER_DRAW,	10, 10,	DIRECT_POINT_FIXED		},/* テーブルの向こう側にいる場合処理 */
	{DIRECT_ROMEN_ID_ITEM1,	 	 EVENT_TYPE_TREASURE_GET,  			SYSTEM_MSG_WINDOW,				DISPLAY_FIELD_CENTER_DRAW, 	18, 11,	DIRECT_POINT_FIXED		},
	{DIRECT_ROMEN_ID_ITEM2,	 	 EVENT_TYPE_TREASURE_GET,  			SYSTEM_MSG_WINDOW,				DISPLAY_FIELD_CENTER_DRAW, 	18, 39,	DIRECT_POINT_FIXED		},
	{DIRECT_ROMEN_ID_ITEM3,	 	 EVENT_TYPE_ITEM_GET,   			SYSTEM_MSG_WINDOW,				DISPLAY_FIELD_CENTER_DRAW, 	30, 11,	DIRECT_POINT_FIXED		},
	{DIRECT_ROMEN_ID_KANBAN1, 	 EVENT_TYPE_MSG_TORK,   			SYSTEM_MSG_WINDOW,				DISPLAY_FIELD_CENTER_DRAW, 	17, 41,	DIRECT_POINT_FIXED		},
	{DIRECT_ROMEN_ID_KANBAN3_1,	 EVENT_TYPE_MSG_TORK,   			SYSTEM_MSG_WINDOW,				DISPLAY_FIELD_CENTER_DRAW, 	31, 26,	DIRECT_POINT_FIXED		},
	{DIRECT_ROMEN_ID_KANBAN3_2,	 EVENT_TYPE_MSG_TORK,   			SYSTEM_MSG_WINDOW,				DISPLAY_FIELD_CENTER_DRAW, 	32, 26,	DIRECT_POINT_FIXED		},
	{DIRECT_ROMEN_ID_KANBAN4, 	 EVENT_TYPE_MSG_TORK,   			SYSTEM_MSG_WINDOW,				DISPLAY_FIELD_CENTER_DRAW, 	24, 15,	DIRECT_POINT_FIXED		},
	{DIRECT_ROMEN_ID_KANBAN5, 	 EVENT_TYPE_MSG_TORK,   			SYSTEM_MSG_WINDOW,				DISPLAY_FIELD_CENTER_DRAW, 	29, 15,	DIRECT_POINT_FIXED		},
	{DIRECT_ROMEN_ID_LOOM1_START,EVENT_TYPE_NULL, 					SYSTEM_NULL,					DISPLAY_NULL_DRAW,			0,	0,	DIRECT_POINT_NULL		},
	{DIRECT_ROMEN_ID_LOOM1,	 	 EVENT_TYPE_SAMEMAP_MOVE,  			SYSTEM_MAP_DARKENING_SUBMAP,	DISPLAY_DARKENING_DRAW, 	12, 10,	DIRECT_POINT_FIXED		},
	{DIRECT_ROMEN_ID_LOOM2_START,EVENT_TYPE_NULL, 					SYSTEM_NULL,					DISPLAY_NULL_DRAW,			0,	0,	DIRECT_POINT_NULL		},
	{DIRECT_ROMEN_ID_LOOM2,	 	 EVENT_TYPE_SAMEMAP_MOVE,  			SYSTEM_MAP_DARKENING_SUBMAP,	DISPLAY_DARKENING_DRAW, 	12, 10,	DIRECT_POINT_FIXED		},

};


#endif
